// @ts-nocheck
// ─── EATSAFE KONSTANTER ─────────────────────────────────────────────────────

export const SUPABASE_URL = "https://jegrpcflyguadyxialkm.supabase.co";

export const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplZ3JwY2ZseWd1YWR5eGlhbGttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkxNjY5NjQsImV4cCI6MjA5NDc0Mjk2NH0.QErfbw2xmsdYjTZCS1WUOUwQHv6G2PKQRldyj8rdGq8";

// ─── KONSTANTER ──────────────────────────────────────────────────────────────



// ─── EATSAFE LOGO KOMPONENT ──────────────────────────────────────────────────

export const E_CATEGORIES = [
  { id:"farve",    label:"Farvestoffer",          range:"E100–E199", min:100,  max:199,  popular:["E102","E110","E122","E129","E150d","E171","E120","E127"] },
  { id:"konserv",  label:"Konserveringsmidler",   range:"E200–E299", min:200,  max:299,  popular:["E202","E211","E220","E250","E251","E252","E282","E290"] },
  { id:"antioxid", label:"Antioxidanter",         range:"E300–E399", min:300,  max:399,  popular:["E300","E306","E320","E321","E322","E330"] },
  { id:"emulg",    label:"Emulgatorer",           range:"E400–E499", min:400,  max:499,  popular:["E407","E412","E415","E440","E471","E476","E433"] },
  { id:"smags",    label:"Smagsforstærkere",      range:"E600–E699", min:600,  max:699,  popular:["E621","E627","E631","E635","E620"] },
  { id:"diverse",  label:"Diverse (E700–E949)",   range:"E700–E949", min:700,  max:949,  popular:["E901","E904","E920","E942"] },
  { id:"sode",     label:"Sødestoffer",            range:"E950–E999", min:950,  max:999,  popular:["E950","E951","E954","E955","E960","E965","E967","E968"] },
  { id:"stivelse", label:"Stivelse & overflader",  range:"E1000+",    min:1000, max:9999, popular:["E1200","E1400","E1404","E1412","E1422","E1440"] },
];

export const E_NUMBERS = {
  "E100": "Curcumin — naturlig gul farve fra gurkemeje",
  "E101": "Riboflavin (B2) — gul-orange farve, findes naturligt i mælk",
  "E102": "Tartrazin — syntetisk gul azo-farve, kan give hyperaktivitet hos børn",
  "E103": "Alkannin — rød-brun farve (ikke godkendt i EU)",
  "E104": "Quinolingul — syntetisk gul-grøn farve",
  "E105": "Fast Yellow AB — syntetisk gul farve (ikke godkendt i EU)",
  "E107": "Yellow 2G — syntetisk gul farve",
  "E110": "Solsikkegul FCF — syntetisk orange-gul azo-farve",
  "E111": "Orange GGN — syntetisk orange farve (ikke godkendt i EU)",
  "E120": "Cochenille/Karminsyre — rød farve fra skjoldlus",
  "E121": "Orcein — rød-lilla farve (ikke godkendt i EU)",
  "E122": "Azorubine/Karmoisin — syntetisk rød azo-farve",
  "E123": "Amaranth — syntetisk rød azo-farve (ikke godkendt i EU)",
  "E124": "Ponceau 4R — syntetisk rød azo-farve",
  "E125": "Scarlet GN — syntetisk rød farve (ikke godkendt i EU)",
  "E126": "Ponceau 6R — syntetisk rød azo-farve (ikke godkendt i EU)",
  "E127": "Erythrosin — syntetisk lyserød/rød farve",
  "E128": "Red 2G — syntetisk rød azo-farve",
  "E129": "Allura Rød AC — syntetisk rød azo-farve",
  "E131": "Patent Blå V — syntetisk blå farve",
  "E132": "Indigokarmin — syntetisk blå farve",
  "E133": "Brilliant Blå FCF — syntetisk blå farve",
  "E140": "Klorofyller — naturlig grøn farve fra planter",
  "E141": "Klorofylkomplekser med kobber — grøn farve",
  "E142": "Grøn S — syntetisk grøn farve",
  "E150a": "Karamelfarve, alm. — brun farve lavet ved opvarmning af sukker",
  "E150b": "Karamelfarve, sulfit — brun farve fremstillet med sulfit",
  "E150c": "Karamelfarve, ammoniak — brun farve fremstillet med ammoniak",
  "E150d": "Karamelfarve, ammoniumsulfit — brun farve i cola og øl",
  "E151": "Brilliant Sort BN — syntetisk sort azo-farve",
  "E152": "Carbon Black — sort farve (ikke godkendt i EU)",
  "E153": "Vegetabilsk kul — sort farve fra forkullet plantemateriale",
  "E154": "Brown FK — syntetisk brun azo-farve",
  "E155": "Brown HT — syntetisk brun azo-farve",
  "E160a": "Alfa-, beta-, gamma-karoten — orange farve, forstadium til A-vitamin",
  "E160b": "Annatto/Bixin/Norbixin — orange-rød farve fra annattobusk",
  "E160c": "Paprikaekstrakt/Capsanthin — rød-orange farve fra paprika",
  "E160d": "Lykopen — rød farve fra tomat",
  "E160e": "Beta-apo-8-carotenal — orange farve",
  "E160f": "Beta-apo-8-carotensyreethylester — orange farve",
  "E161a": "Flavoxanthin — gul farve (ikke godkendt i EU)",
  "E161b": "Lutein — gul farve fra blomster og æg",
  "E161c": "Kryptoxanthin — gul-orange farve (ikke godkendt i EU)",
  "E161d": "Rubixanthin — gul-orange farve (ikke godkendt i EU)",
  "E161e": "Violaxanthin — gul farve (ikke godkendt i EU)",
  "E161f": "Rhodoxanthin — rød farve (ikke godkendt i EU)",
  "E162": "Rødbetarød/Betanin — rød farve fra rødbede",
  "E163": "Anthocyaniner — rød-lilla farve fra bær og druer",
  "E170": "Calciumkarbonat — hvid farve/fyldsoftf, også kalk",
  "E171": "Titandioxid — hvid farve, bruges i slik og tandpasta",
  "E172": "Jernoxider og jernhydroxider — gul, rød og sort farve",
  "E173": "Aluminium — sølvfarve til konfekture",
  "E174": "Sølv — sølvfarve til konfekture",
  "E175": "Guld — guldfarve til konfekture",
  "E180": "Litholrubine BK — rød farve til osteskorper",
  "E200": "Sorbinsyre — konserverer mod skimmelsvamp i ost og bagværk",
  "E201": "Natriumsorbat — konservering mod skimmel",
  "E202": "Kaliumsorbat — meget udbredt konservering mod skimmel og gær",
  "E203": "Calciumsorbat — konservering mod skimmel",
  "E210": "Benzoesyre — konservering i saft, marmelade og drikkevarer",
  "E211": "Natriumbenzoat — udbredt konservering i sodavand og saucer",
  "E212": "Kaliumbenzoat — konservering mod gær og bakterier",
  "E213": "Calciumbenzoat — konservering mod mikrober",
  "E214": "Ethylparahydroxybenzoat — konservering (parabener)",
  "E215": "Natriumethylparahydroxybenzoat — konservering (parabener)",
  "E218": "Methylparahydroxybenzoat — konservering (parabener)",
  "E219": "Natriummethylparahydroxybenzoat — konservering (parabener)",
  "E220": "Svovldioxid — konservering i vin, frugt og tørrede frugter",
  "E221": "Natriumsulfit — konservering, forhindrer brunfarvning",
  "E222": "Natriumhydrogensulfit — konservering i vin og frugtprodukter",
  "E223": "Natriumdisulfit — konservering og blegemiddel",
  "E224": "Kaliumdisulfit — konservering i vin",
  "E225": "Kaliumsulfit — konservering",
  "E226": "Calciumsulfit — konservering og fasthedsmiddel",
  "E227": "Calciumhydrogensulfit — konservering i øl",
  "E228": "Kaliumhydrogensulfit — konservering i vin",
  "E230": "Biphenyl/Diphenyl — konservering på citrusskaller",
  "E231": "Orthophenylphenol — konservering på citrusskaller",
  "E232": "Natriumorthophenylphenol — konservering på citrusskaller",
  "E234": "Nisin — naturlig antibiotisk konservering i ost",
  "E235": "Natamycin — naturlig antibiotisk konservering mod skimmel",
  "E239": "Hexamethylentetramin — konservering i syltet fisk",
  "E242": "Dimethyldicarbonat — konservering i drikkevarer",
  "E249": "Kaliumnitrit — konservering og rødfarvning af kødprodukter",
  "E250": "Natriumnitrit — konservering i pålæg og bacon, kan danne nitrosaminer",
  "E251": "Natriumnitrat — konservering i kødprodukter og ost",
  "E252": "Kaliumnitrat — konservering i kødprodukter og ost",
  "E260": "Eddikesyre — konservering og smagsgiver, naturlig i eddike",
  "E261": "Kaliumacetat — konservering og surheds regulering",
  "E262": "Natriumacetat — konservering og smagsgiver",
  "E263": "Calciumacetat — konservering og fasthedsmiddel",
  "E270": "Mælkesyre — konservering, naturlig i fermenterede produkter",
  "E280": "Propionsyre — konservering mod skimmel i brød",
  "E281": "Natriumpropionat — konservering i brød og bagværk",
  "E282": "Calciumpropionat — konservering i brød og bagværk",
  "E283": "Kaliumpropionat — konservering i brød",
  "E284": "Borsyre — konservering i kaviar",
  "E285": "Natriumtetraborat — konservering i kaviar",
  "E290": "Kuldioxid — kulsyre i drikkevarer og emballage",
  "E296": "Æblesyre — konservering og smagsgiver",
  "E297": "Fumarsyre — konservering og syrningsagent",
  "E300": "Ascorbinsyre (C-vitamin) — antioxidant, forhindrer brunfarvning",
  "E301": "Natriumascorbat — antioxidant, C-vitaminsalt",
  "E302": "Calciumascorbat — antioxidant, C-vitaminsalt",
  "E304": "Fedtsyreestere af ascorbinsyre — fedtopløselig antioxidant",
  "E306": "Tokoferoler (E-vitamin) — naturlig antioxidant fra vegetabilske olier",
  "E307": "Alfa-tokoferol — syntetisk E-vitamin, antioxidant",
  "E308": "Gamma-tokoferol — syntetisk E-vitamin",
  "E309": "Delta-tokoferol — syntetisk E-vitamin",
  "E310": "Propylgallat — antioxidant i fedtstoffer og olier",
  "E311": "Octylgallat — antioxidant i fedtstoffer",
  "E312": "Dodecylgallat — antioxidant i fedtstoffer",
  "E315": "Erythorbinsyre — antioxidant i kødprodukter",
  "E316": "Natriumerythorbat — antioxidant i kødprodukter",
  "E319": "TBHQ — antioxidant i vegetabilske olier og chips",
  "E320": "BHA (Butylhydroxyanisol) — kontroversiel antioxidant i fedtstoffer",
  "E321": "BHT (Butylhydroxytoluen) — kontroversiel antioxidant i fedtstoffer",
  "E322": "Lecitiner — emulgator og antioxidant, ofte fra soja eller solsikke",
  "E325": "Natriumlactat — antioxidantsynergist og fugtighedsbeholder",
  "E326": "Kaliumlactat — antioxidantsynergist",
  "E327": "Calciumlactat — antioxidantsynergist og fasthedsmiddel",
  "E328": "Ammoniumlactat — antioxidantsynergist",
  "E329": "Magnesiumlactat — antioxidantsynergist",
  "E330": "Citronsyre — antioxidant og syrningsagent, naturlig i citrusfrugter",
  "E331": "Natriumcitrat — antioxidantsynergist og emulgator",
  "E332": "Kaliumcitrat — antioxidantsynergist og regulering af surhedsgrad",
  "E333": "Calciumcitrat — antioxidantsynergist og fasthedsmiddel",
  "E334": "Vinsyre (L-tartrat) — antioxidant og syrningsagent i vin",
  "E335": "Natriumtartrat — antioxidantsynergist",
  "E336": "Kaliumtartrat — antioxidantsynergist og bagepulver",
  "E337": "Natriumkaliumtartrat — antioxidantsynergist",
  "E338": "Fosforsyre — antioxidantsynergist og surhedsregulering i cola",
  "E339": "Natriumfosfater — antioxidantsynergist og emulgator",
  "E340": "Kaliumfosfater — antioxidantsynergist og hævemiddel",
  "E341": "Calciumfosfater — antioxidantsynergist og hævemiddel",
  "E343": "Magnesiumfosfater — antioxidantsynergist",
  "E350": "Natriummalat — antioxidantsynergist",
  "E351": "Kaliummalat — antioxidantsynergist",
  "E352": "Calciummalat — antioxidantsynergist",
  "E353": "Metavinsyre — antioxidantsynergist i vin",
  "E354": "Calciumtartrat — antioxidantsynergist",
  "E355": "Adipinsyre — antioxidantsynergist og syrningsagent",
  "E356": "Natriumadipinat — antioxidantsynergist",
  "E357": "Kaliumadipinat — antioxidantsynergist",
  "E363": "Ravsyre — antioxidantsynergist",
  "E380": "Triammoniumcitrat — antioxidantsynergist",
  "E385": "Calciumdinatrium-EDTA — antioxidantsynergist og sekvestringsmiddel",
  "E392": "Ekstrakter af rosmarin — naturlig antioxidant",
  "E393": "Ekstrakter af rig-ekstrakt (Quillaja) — naturlig antioxidant",
  "E400": "Alginsyre — fortykningsmiddel fra brunalger",
  "E401": "Natriumalginat — fortykningsmiddel fra brunalger",
  "E402": "Kaliumalginat — fortykningsmiddel fra brunalger",
  "E403": "Ammoniumalginat — fortykningsmiddel fra brunalger",
  "E404": "Calciumalginat — fortykningsmiddel, gelerende middel",
  "E405": "Propylenglycolalginat — emulgator og stabilisator",
  "E406": "Agar — gelerende middel fra rødalger, vegansk gelatine",
  "E407": "Carrageenan — fortykningsmiddel fra rødalger, bruges i mælkeprodukter",
  "E407a": "Bearbejdet Eucheuma-alger — fortykningsmiddel",
  "E408": "Karayagummi — fortykningsmiddel",
  "E410": "Johannesbrødkernmel — fortykningsmiddel fra johannesbrødtræ",
  "E411": "Havrekernmel — fortykningsmiddel",
  "E412": "Guargummi — fortykningsmiddel fra guarbønne",
  "E413": "Tragant — fortykningsmiddel fra tornebusk",
  "E414": "Arabiagummi — fortykningsmiddel, naturlig harpiks",
  "E415": "Xanthangummi — fortykningsmiddel fra fermentering",
  "E416": "Karayagummi — fortykningsmiddel fra karayabusk",
  "E417": "Tarakernmel — fortykningsmiddel fra tarafrø",
  "E418": "Gellangummi — fortykningsmiddel fra fermentering",
  "E419": "Ghatti gummi — fortykningsmiddel",
  "E420": "Sorbitol/Sorbitolsirup — sødemiddel og fugtighedsbeholder",
  "E421": "Mannitol — sødemiddel og anti-klumpningsmiddel",
  "E422": "Glycerol — fugtighedsbeholder og opløsningsmiddel",
  "E423": "Octylgallat — antioxidant",
  "E425": "Konjac — fortykningsmiddel og gelerende middel",
  "E426": "Sojabønne-hemicellulose — emulgator",
  "E427": "Cassie gummi — fortykningsmiddel",
  "E430": "Polyoxyethylen(8)stearat — emulgator",
  "E431": "Polyoxyethylen(40)stearat — emulgator",
  "E432": "Polyoxyethylensobitanmonolaurat (Polysorbat 20) — emulgator",
  "E433": "Polyoxyethylensorbitanmonooleat (Polysorbat 80) — emulgator",
  "E434": "Polyoxyethylensorbitanmonopalmitat (Polysorbat 40) — emulgator",
  "E435": "Polyoxyethylensorbitanmonostearat (Polysorbat 60) — emulgator",
  "E436": "Polyoxyethylensorbitantristearat (Polysorbat 65) — emulgator",
  "E440": "Pektiner — gelerende middel fra citrusskaller og æbler",
  "E442": "Ammoniumfosfatider — emulgator i chokolade",
  "E444": "Saccharoseacetoisobutyrat — emulgator i drikkevarer",
  "E445": "Glycerolestere af træharpiks — emulgator i drikkevarer",
  "E450": "Diphosphater — hæve- og bindemiddel i bagværk",
  "E451": "Triphosphater — bindemiddel i kødprodukter",
  "E452": "Polyphosphater — bindemiddel, vandholdenhed i kød",
  "E459": "Beta-cyclodextrin — indkapslingsmiddel",
  "E460": "Cellulose — fyldsotf og anti-klumpningsmiddel",
  "E461": "Methylcellulose — fortykningsmiddel og emulgator",
  "E462": "Ethylcellulose — bindemiddel",
  "E463": "Hydroxypropylcellulose — fortykningsmiddel",
  "E464": "Hydroxypropylmethylcellulose — fortykningsmiddel og emulgator",
  "E465": "Ethylmethylcellulose — fortykningsmiddel",
  "E466": "Carboxymethylcellulose — fortykningsmiddel og stabilisator",
  "E468": "Crosslinket natriumcarboxymethylcellulose — stabilisator",
  "E469": "Enzymatisk hydrolyseret carboxymethylcellulose — stabilisator",
  "E470a": "Natriumsalte af fedtsyrer — emulgator",
  "E470b": "Magnesiumsalte af fedtsyrer — emulgator og anti-klumpningsmiddel",
  "E471": "Mono- og diglycerider af fedtsyrer — emulgator i brød og margarine",
  "E472a": "Eddikesyreestere af mono- og diglycerider — emulgator",
  "E472b": "Mælkesyreestere af mono- og diglycerider — emulgator",
  "E472c": "Citronsyreestere af mono- og diglycerider — emulgator",
  "E472d": "Vinsyreestere af mono- og diglycerider — emulgator",
  "E472e": "Diacetyltartrat- og eddikesyreestere af mono- og diglycerider — emulgator",
  "E472f": "Blandede eddike- og vinsyreestere af mono- og diglycerider — emulgator",
  "E473": "Saccharosefedtsyreestere — emulgator",
  "E474": "Saccharoglycerider — emulgator",
  "E475": "Polyglycerolestere af fedtsyrer — emulgator",
  "E476": "Polyglycerolpolyricinoleat — emulgator i chokolade",
  "E477": "Propylenglycolestere af fedtsyrer — emulgator",
  "E479b": "Varmebehandlet sojaolieinteraktion med mono- og diglycerider — emulgator",
  "E481": "Natriumstearoyl-2-lactylat — emulgator i brød",
  "E482": "Calciumstearoyl-2-lactylat — emulgator i brød",
  "E483": "Stearoyltartrat — emulgator",
  "E484": "Stearylcitrat — emulgator",
  "E491": "Sorbitanmonostearat — emulgator",
  "E492": "Sorbitantristearat — emulgator",
  "E493": "Sorbitanmonolauarat — emulgator",
  "E494": "Sorbitanmonooleat — emulgator",
  "E495": "Sorbitanmonopalmitat — emulgator",
  "E620": "L-Glutaminsyre — naturlig smagsforstærker, findes i tomat og ost",
  "E621": "Mononatriumglutamat (MSG) — syntetisk smagsforstærker, omdiskuteret",
  "E622": "Monokaliumglutamat — smagsforstærker",
  "E623": "Calciumdiglutamat — smagsforstærker",
  "E624": "Monoammoniumglutamat — smagsforstærker",
  "E625": "Magnesiumdiglutamat — smagsforstærker",
  "E626": "Guanylsyre — smagsforstærker",
  "E627": "Dinatriumguanylat — smagsforstærker, forstærker MSG-effekt",
  "E628": "Dikaliumguanylat — smagsforstærker",
  "E629": "Calciumguanylat — smagsforstærker",
  "E630": "Inosinsyre — smagsforstærker",
  "E631": "Dinatriuminosinat — smagsforstærker, forstærker MSG-effekt",
  "E632": "Dikaliuminosinat — smagsforstærker",
  "E633": "Calciuminosinat — smagsforstærker",
  "E634": "Calcium-5-ribonukleotider — smagsforstærker",
  "E635": "Dinatrium-5-ribonukleotider — smagsforstærker, kombination af E627+E631",
  "E636": "Maltol — smagsforstærker og aromasoftf",
  "E637": "Ethylmaltol — smagsforstærker, forstærker sød smag",
  "E640": "Glycin og natriumsalt — smagsforstærker",
  "E650": "Zinkacetat — smagsforstærker i tyggegummi",
  "E900": "Dimethylpolysiloxan — anti-skummiddel i fedtstoffer og juice",
  "E901": "Bivoks — glaseringsmiddel på frugt og slik",
  "E902": "Candelillavoks — glaseringsmiddel, vegansk alternativ til bivoks",
  "E903": "Carnaubavoks — glaseringsmiddel fra palmeblade",
  "E904": "Shellac — glaseringsmiddel fra skjoldlus",
  "E905": "Mikrokrystallinsk voks — glaseringsmiddel",
  "E907": "Raffineret mikrokrystallinsk voks — glaseringsmiddel",
  "E912": "Montan-syreestere — glaseringsmiddel",
  "E914": "Oxideret polyethylenvoks — glaseringsmiddel",
  "E920": "L-Cystein — mel-forbedrer i bagværk",
  "E927b": "Carbamid (urinstof) — mel-forbedrer",
  "E938": "Argon — emballeringsgas",
  "E939": "Helium — emballeringsgas",
  "E941": "Kvælstof — emballeringsgas, forlænger holdbarheden",
  "E942": "Lattergas — drivgas i flødeskum",
  "E943a": "Butan — drivgas",
  "E943b": "Isobutan — drivgas",
  "E944": "Propan — drivgas",
  "E948": "Oxygen — emballeringsgas",
  "E949": "Hydrogen — emballeringsgas",
  "E950": "Acesulfam K — sødemiddel, ca. 200x sødere end sukker",
  "E951": "Aspartam — sødemiddel, 200x sødere end sukker, indeholder phenylalanin",
  "E952": "Cyclaminsyre/Cyclamat — sødemiddel, forbudt i USA",
  "E953": "Isomalt — sødemiddel og fyldsoftf fra sukker",
  "E954": "Saccharin og salte — ældste kunstige sødemiddel, 300-500x sødere",
  "E955": "Sucralose — sødemiddel, 600x sødere end sukker",
  "E957": "Thaumatin — naturlig proteinsødemiddel fra afrikansk frugt",
  "E958": "Glycyrrhizin — naturlig sødemiddel fra lakrids",
  "E959": "Neohesperidindihydrochalcon — sødemiddel fra citrus",
  "E960": "Steviolglykosider (Stevia) — naturlig sødemiddel fra steviaplante",
  "E961": "Neotam — sødemiddel, 7000-13000x sødere end sukker",
  "E962": "Aspartam-acesulfamsalt — sødemiddel",
  "E965": "Maltitol/Maltitolsirup — sødemiddel og fugtighedsbeholder",
  "E966": "Lactitol — sødemiddel, afledt af laktose",
  "E967": "Xylitol — sødemiddel fra birkebark, godt for tænder",
  "E968": "Erythritol — sødemiddel, naturligt i frugt og fermenterede fødevarer",
  "E969": "Advantam — sødemiddel, 20000x sødere end sukker",
  "E999": "Quillajaekstrakt — skumdannende middel i drikkevarer",
  "E161g": "Canthaxanthin — orange farve, bruges i lakseopdræt",
};


export const ALLERGENS = [
  { id:"gluten",        label:"Gluten",           emoji:"🥖" },
  { id:"hvede",         label:"Hvede",             emoji:"🌾" },
  { id:"maelkeallergi", label:"Mælk",              emoji:"🥛" },
  { id:"laktose",       label:"Laktoseintolerance",emoji:"🍬" },
  { id:"aeg",           label:"Æg",               emoji:"🥚" },
  { id:"noedder",       label:"Nødder",            emoji:"🌰" },
  { id:"jordnoedder",   label:"Jordnødder",        emoji:"🥜" },
  { id:"soja",          label:"Soja",              emoji:"🫛" },
  { id:"fisk",          label:"Fisk",              emoji:"🐟" },
  { id:"skaldyr",       label:"Skaldyr",           emoji:"🦐" },
  { id:"selleri",       label:"Selleri",           emoji:"🥬" },
  { id:"sennep",        label:"Sennep",            emoji:"🟡" },
  { id:"sesam",         label:"Sesam",             emoji:"🌿" },
  { id:"svovl",         label:"Sulfitter",         emoji:"🍷" },
  { id:"lupin",         label:"Lupin",             emoji:"🌸" },
  { id:"bloeddyr",      label:"Bløddyr",           emoji:"🦑" },
];

export const DEMO_CODES = [
  { code:"3017620422003", label:"Nutella" },
  { code:"5449000054227", label:"Coca-Cola" },
  { code:"7394376616566", label:"Oatly" },
  { code:"5701029015306", label:"Lurpak" },
];

export const SCREENS = {
  WELCOME:"welcome", LOGIN:"login", ONBOARD:"onboard",
  HOME:"home", SEARCH:"search",
  LIST:"list", PROFILE:"profile", FAMILY:"family",
  RESULT:"result", HISTORY:"history",
  NOTFOUND:"notfound", SUBMITTED:"submitted",
  ADMIN:"admin", FAVORITES:"favorites",
  MADPAS:"madpas", RECIPES:"recipes", EDITPROFILE:"editprofile", SUGGEST_EDIT:"suggest_edit",
};

export const PAGE_IDS = {
  welcome:"SCR-01", login:"SCR-02", onboard:"SCR-03",
  home:"SCR-04", search:"SCR-06",
  list:"SCR-07", profile:"SCR-08", family:"SCR-09",
  result:"SCR-10", history:"SCR-11", notfound:"SCR-12",
  submitted:"SCR-13", admin:"SCR-14", favorites:"SCR-15",
  madpas:"SCR-16", recipes:"SCR-17", editprofile:"SCR-18",
};

export const DUMMY_PRODUCT = {
  code: "3017620422003",
  ean: "3017620422003",
  name: "Nutella",
  brand: "Ferrero",
  image_url: "https://images.openfoodfacts.org/images/products/301/762/042/2003/front_en.820.400.jpg",
  category: "Chokolade",
  status: "danger",
  headline: "Indeholder allergen",
  summary: "Produktet indeholder Laktose, Nødder.",
  source: "open_food_facts",
  verified_status: "unverified",
  hasUnknown: false,
  matchedDanger: ["laktose", "noedder"],
  matchedWarning: ["soja"],
  familyImpact: [],
  allergen_flags: {
    gluten: "no", laktose: "yes", aeg: "no",
    noedder: "yes", jordnoedder: "no", soja: "traces",
    fisk: "no", skaldyr: "no", selleri: "no",
    sennep: "no", sesam: "no", svovl: "no",
    lupin: "no", bloeddyr: "no",
  },
  ingredients: "Sucre, huile de palme, NOISETTES 13%, cacao maigre 7,4%, LAIT écrémé en poudre 6,6%, LACTOSERUM en poudre, émulsifiants: lécithines (SOJA), vanilline.",
  tags: ["vegetarian"],
  nutrition: {
    energy_kcal: 539,
    fat: 30.9,
    saturated_fat: 10.6,
    carbohydrates: 57.5,
    sugars: 56.3,
    fiber: 3.4,
    protein: 6.3,
    salt: 0.11,
  },
  flags: [
    { type:"bad", text:"Indeholder Laktose" },
    { type:"bad", text:"Indeholder Nødder" },
    { type:"maybe", text:"Kan indeholde spor af Soja" },
  ],
  timestamp: Date.now(),
};

// Mock produkter med fuld data til test

export const MOCK_PRODUCTS = [
  {
    id: "mock-1", ean: "5701029015306", name: "Lurpak Smør", brand: "Lurpak",
    category: "Mejeri", verified_status: "verified", source: "verified",
    image_url: null,
    allergen_flags: { gluten:"no", laktose:"yes", aeg:"no", noedder:"no", jordnoedder:"no", soja:"no", fisk:"no", skaldyr:"no", selleri:"no", sennep:"no", sesam:"no", svovl:"no", lupin:"no", bloeddyr:"no" },
    ingredients: "Pasteuriseret fløde (mælk), salt.",
    nutrition: { energy_kcal:717, fat:80, saturated_fat:52, carbohydrates:0.6, sugars:0.6, fiber:0, protein:0.6, salt:1.5 },
    tags: ["vegetarian"],
  },
  {
    id: "mock-2", ean: "5000112546415", name: "Coca-Cola Original", brand: "Coca-Cola",
    category: "Drikkevarer", verified_status: "verified", source: "verified",
    image_url: null,
    allergen_flags: { gluten:"no", laktose:"no", aeg:"no", noedder:"no", jordnoedder:"no", soja:"no", fisk:"no", skaldyr:"no", selleri:"no", sennep:"no", sesam:"no", svovl:"no", lupin:"no", bloeddyr:"no" },
    ingredients: "Vand, sukker, kuldioxid, farve (E150d), surheds regulerende middel (E338), naturlige aromaer inkl. koffein.",
    nutrition: { energy_kcal:42, fat:0, saturated_fat:0, carbohydrates:10.6, sugars:10.6, fiber:0, protein:0, salt:0 },
    tags: ["vegan", "vegetarian"],
  },
  {
    id: "mock-3", ean: "7394376616566", name: "Oatly Havredrik", brand: "Oatly",
    category: "Plantebaseret", verified_status: "verified", source: "verified",
    image_url: null,
    allergen_flags: { gluten:"traces", laktose:"no", aeg:"no", noedder:"no", jordnoedder:"no", soja:"no", fisk:"no", skaldyr:"no", selleri:"no", sennep:"no", sesam:"no", svovl:"no", lupin:"no", bloeddyr:"no" },
    ingredients: "Vand, havre 10%, rapsolie, calcium, vitaminer (D2, riboflavin, B12), salt.",
    nutrition: { energy_kcal:46, fat:1.5, saturated_fat:0.2, carbohydrates:6.7, sugars:4, fiber:0.8, protein:1, salt:0.07 },
    tags: ["vegan", "vegetarian"],
  },
];

export const ALLERGEN_EXAMPLES = {
  gluten: {
    products: { da:["Brød","Pasta","Øl","Sojasauce"], en:["Bread","Pasta","Beer","Soy sauce"], de:["Brot","Pasta","Bier","Sojasoße"], fr:["Pain","Pâtes","Bière","Sauce soja"], es:["Pan","Pasta","Cerveza","Salsa de soja"], it:["Pane","Pasta","Birra","Salsa di soia"], nl:["Brood","Pasta","Bier","Sojasaus"], pt:["Pão","Massa","Cerveja","Molho de soja"], pl:["Chleb","Makaron","Piwo","Sos sojowy"], sv:["Bröd","Pasta","Öl","Sojasås"], no:["Brød","Pasta","Øl","Soyasaus"], ja:["パン","パスタ","ビール","醤油"], zh:["面包","面食","啤酒","酱油"], ar:["خبز","معكرونة","بيرة","صلصة الصويا"], tr:["Ekmek","Makarna","Bira","Soya sosu"], th:["ขนมปัง","พาสต้า","เบียร์","ซีอิ้ว"], el:["Ψωμί","Ζυμαρικά","Μπύρα","Σάλτσα σόγιας"] },
    ingredients: { da:["Hvede","Rug","Byg","Havre","Spelt"], en:["Wheat","Rye","Barley","Oats","Spelt"], de:["Weizen","Roggen","Gerste","Hafer","Dinkel"], fr:["Blé","Seigle","Orge","Avoine","Épeautre"], es:["Trigo","Centeno","Cebada","Avena","Espelta"], it:["Frumento","Segale","Orzo","Avena","Farro"], nl:["Tarwe","Rogge","Gerst","Haver","Spelt"], pt:["Trigo","Centeio","Cevada","Aveia","Espelta"], pl:["Pszenica","Żyto","Jęczmień","Owies","Orkisz"], sv:["Vete","Råg","Korn","Havre","Dinkel"], no:["Hvete","Rug","Bygg","Havre","Spelt"], ja:["小麦","ライ麦","大麦","燕麦","スペルト"], zh:["小麦","黑麦","大麦","燕麦","斯佩尔特"], ar:["قمح","جاودار","شعير","شوفان","كاموت"], tr:["Buğday","Çavdar","Arpa","Yulaf","Kavılca"], th:["ข้าวสาลี","ข้าวไรย์","ข้าวบาร์เลย์","ข้าวโอ๊ต"], el:["Σιτάρι","Σίκαλη","Κριθάρι","Βρώμη","Ζέα"] },
  },
  laktose: {
    products: { da:["Mælk","Ost","Smør","Is","Yoghurt"], en:["Milk","Cheese","Butter","Ice cream","Yoghurt"], de:["Milch","Käse","Butter","Eis","Joghurt"], fr:["Lait","Fromage","Beurre","Glace","Yaourt"], es:["Leche","Queso","Mantequilla","Helado","Yogur"], it:["Latte","Formaggio","Burro","Gelato","Yogurt"], nl:["Melk","Kaas","Boter","Ijs","Yoghurt"], pt:["Leite","Queijo","Manteiga","Gelado","Iogurte"], pl:["Mleko","Ser","Masło","Lody","Jogurt"], sv:["Mjölk","Ost","Smör","Glass","Yoghurt"], no:["Melk","Ost","Smør","Is","Yoghurt"], ja:["牛乳","チーズ","バター","アイスクリーム","ヨーグルト"], zh:["牛奶","奶酪","黄油","冰淇淋","酸奶"], ar:["حليب","جبن","زبدة","آيس كريم","زبادي"], tr:["Süt","Peynir","Tereyağı","Dondurma","Yoğurt"], th:["นม","ชีส","เนย","ไอศกรีม","โยเกิร์ต"], el:["Γάλα","Τυρί","Βούτυρο","Παγωτό","Γιαούρτι"] },
    ingredients: { da:["Laktose","Valle","Kasein","Fløde","Skummetmælk"], en:["Lactose","Whey","Casein","Cream","Skimmed milk"], de:["Laktose","Molke","Kasein","Sahne","Magermilch"], fr:["Lactose","Lactosérum","Caséine","Crème","Lait écrémé"], es:["Lactosa","Suero","Caseína","Nata","Leche desnatada"], it:["Lattosio","Siero","Caseina","Panna","Latte scremato"], nl:["Lactose","Wei","Caseïne","Room","Magere melk"], pt:["Lactose","Soro","Caseína","Natas","Leite desnatado"], pl:["Laktoza","Serwatka","Kazeina","Śmietana","Mleko odtłuszczone"], sv:["Laktos","Vassle","Kasein","Grädde","Skummjölk"], no:["Laktose","Myse","Kasein","Fløte","Skummet melk"], ja:["乳糖","乳清","カゼイン","クリーム","脱脂乳"], zh:["乳糖","乳清","酪蛋白","奶油","脱脂奶"], ar:["لاكتوز","مصل اللبن","كازين","كريمة","حليب خالي الدسم"], tr:["Laktoz","Peynir altı suyu","Kazein","Krema","Yağsız süt"], th:["แลคโตส","เวย์","เคซีน","ครีม","นมพร่องมันเนย"], el:["Λακτόζη","Ορός γάλακτος","Καζεΐνη","Κρέμα","Αποβουτυρωμένο γάλα"] },
  },
  aeg: {
    products: { da:["Mayonnaise","Pasta","Kage","Aioli","Vafler"], en:["Mayonnaise","Pasta","Cake","Aioli","Waffles"], de:["Mayonnaise","Pasta","Kuchen","Aioli","Waffeln"], fr:["Mayonnaise","Pâtes","Gâteau","Aïoli","Gaufres"], es:["Mayonesa","Pasta","Tarta","Alioli","Gofres"], it:["Maionese","Pasta","Torta","Aioli","Cialde"], nl:["Mayonaise","Pasta","Cake","Aioli","Wafels"], pt:["Maionese","Massa","Bolo","Aioli","Waffles"], pl:["Majonez","Makaron","Ciasto","Aioli","Gofry"], sv:["Majonnäs","Pasta","Kaka","Aioli","Våfflor"], no:["Majones","Pasta","Kake","Aioli","Vafler"], ja:["マヨネーズ","パスタ","ケーキ","アイオリ","ワッフル"], zh:["蛋黄酱","面食","蛋糕","蒜泥蛋黄酱","华夫饼"], ar:["مايونيز","معكرونة","كعكة","أيولي","وافل"], tr:["Mayonez","Makarna","Kek","Aioli","Waffle"], th:["มายองเนส","พาสต้า","เค้ก","ไอโอลี่","วาฟเฟิล"], el:["Μαγιονέζα","Ζυμαρικά","Κέικ","Αϊολί","Βάφλες"] },
    ingredients: { da:["Æg","Æggehvide","Æggeblomme","Tørret æg"], en:["Egg","Egg white","Egg yolk","Dried egg"], de:["Ei","Eiweiß","Eigelb","Trockenei"], fr:["Œuf","Blanc d'œuf","Jaune d'œuf","Œuf en poudre"], es:["Huevo","Clara de huevo","Yema","Huevo en polvo"], it:["Uovo","Albume","Tuorlo","Uovo essiccato"], nl:["Ei","Eiwit","Eigeel","Gedroogd ei"], pt:["Ovo","Clara","Gema","Ovo em pó"], pl:["Jajo","Białko jaja","Żółtko","Jajo suszone"], sv:["Ägg","Äggvita","Äggula","Torkat ägg"], no:["Egg","Eggehvite","Eggeplomme","Tørket egg"], ja:["卵","卵白","卵黄","乾燥卵"], zh:["鸡蛋","蛋清","蛋黄","干燥蛋"], ar:["بيض","بياض البيض","صفار البيض","بيض مجفف"], tr:["Yumurta","Yumurta beyazı","Yumurta sarısı","Kurutulmuş yumurta"], th:["ไข่","ไข่ขาว","ไข่แดง","ไข่แห้ง"], el:["Αυγό","Ασπράδι","Κρόκος","Αποξηραμένο αυγό"] },
  },
  noedder: {
    products: { da:["Pesto","Chokolade","Muesli","Nougat","Marcipan"], en:["Pesto","Chocolate","Muesli","Nougat","Marzipan"], de:["Pesto","Schokolade","Müsli","Nougat","Marzipan"], fr:["Pesto","Chocolat","Muesli","Nougat","Massepain"], es:["Pesto","Chocolate","Muesli","Turrón","Mazapán"], it:["Pesto","Cioccolato","Muesli","Torrone","Marzapane"], nl:["Pesto","Chocolade","Muesli","Nougat","Marsepein"], pt:["Pesto","Chocolate","Muesli","Nougat","Maçapão"], pl:["Pesto","Czekolada","Muesli","Nugat","Marcepan"], sv:["Pesto","Choklad","Müsli","Nougat","Marsipan"], no:["Pesto","Sjokolade","Müsli","Nougat","Marsipan"], ja:["ペスト","チョコレート","ミューズリー","ヌガー","マジパン"], zh:["香蒜酱","巧克力","麦片","牛轧糖","杏仁膏"], ar:["بيستو","شوكولاتة","موسلي","نوغا","لوز الحلوى"], tr:["Pesto","Çikolata","Müsli","Nuga","Badem ezmesi"], th:["เพสโต้","ช็อกโกแลต","มูสลี่","นูกัต","มาร์ซิปัน"], el:["Πέστο","Σοκολάτα","Μούσλι","Νουγκά","Μαρτσιπάνι"] },
    ingredients: { da:["Mandler","Hasselnødder","Valnødder","Cashew","Pistacienødder"], en:["Almonds","Hazelnuts","Walnuts","Cashews","Pistachios"], de:["Mandeln","Haselnüsse","Walnüsse","Cashews","Pistazien"], fr:["Amandes","Noisettes","Noix","Noix de cajou","Pistaches"], es:["Almendras","Avellanas","Nueces","Anacardos","Pistachos"], it:["Mandorle","Nocciole","Noci","Anacardi","Pistacchi"], nl:["Amandelen","Hazelnoten","Walnoten","Cashewnoten","Pistachenoten"], pt:["Amêndoas","Avelãs","Nozes","Cajus","Pistáchios"], pl:["Migdały","Orzechy laskowe","Orzechy włoskie","Nerkowce","Pistacje"], sv:["Mandlar","Hasselnötter","Valnötter","Cashewnötter","Pistaschnötter"], no:["Mandler","Hasselnøtter","Valnøtter","Cashewnøtter","Pistasjnøtter"], ja:["アーモンド","ヘーゼルナッツ","クルミ","カシューナッツ","ピスタチオ"], zh:["杏仁","榛子","核桃","腰果","开心果"], ar:["لوز","بندق","جوز","كاجو","فستق"], tr:["Badem","Fındık","Ceviz","Kaju","Antep fıstığı"], th:["อัลมอนด์","เฮเซลนัท","วอลนัท","มะม่วงหิมพานต์","พิสตาชิโอ"], el:["Αμύγδαλα","Φουντούκια","Καρύδια","Κάσιους","Φιστίκια"] },
  },
  jordnoedder: {
    products: { da:["Jordnøddesmør","Satay sauce","Snacks","Cookies"], en:["Peanut butter","Satay sauce","Snacks","Cookies"], de:["Erdnussbutter","Satay-Sauce","Snacks","Kekse"], fr:["Beurre de cacahuète","Sauce satay","Snacks","Cookies"], es:["Mantequilla de cacahuete","Salsa satay","Snacks","Galletas"], it:["Burro di arachidi","Salsa satay","Snack","Biscotti"], nl:["Pindakaas","Satésaus","Snacks","Koekjes"], pt:["Manteiga de amendoim","Molho satay","Snacks","Bolachas"], pl:["Masło orzechowe","Sos satay","Przekąski","Ciastka"], sv:["Jordnötssmör","Sataysås","Snacks","Kakor"], no:["Peanøttsmør","Sataysaus","Snacks","Kjeks"], ja:["ピーナッツバター","サテソース","スナック","クッキー"], zh:["花生酱","沙爹酱","零食","饼干"], ar:["زبدة الفول السوداني","صلصة الساتيه","وجبات خفيفة","بسكويت"], tr:["Fıstık ezmesi","Satay sosu","Atıştırmalık","Kurabiye"], th:["เนยถั่ว","ซอสสะเต๊ะ","ขนมขบเคี้ยว","คุกกี้"], el:["Βούτυρο φιστικιών","Σάλτσα σατέ","Σνακ","Μπισκότα"] },
    ingredients: { da:["Jordnødder","Peanuts","Arachis hypogaea"], en:["Peanuts","Groundnuts","Arachis hypogaea"], de:["Erdnüsse","Erdnuss","Arachis hypogaea"], fr:["Arachides","Cacahuètes","Arachis hypogaea"], es:["Cacahuetes","Maníes","Arachis hypogaea"], it:["Arachidi","Noccioline","Arachis hypogaea"], nl:["Pinda's","Grondnoten","Arachis hypogaea"], pt:["Amendoins","Arachis hypogaea"], pl:["Orzeszki ziemne","Orzeszki arachidowe"], sv:["Jordnötter","Arachis hypogaea"], no:["Peanøtter","Jordnøtter","Arachis hypogaea"], ja:["ピーナッツ","落花生","アラキス"], zh:["花生","落花生"], ar:["الفول السوداني","فول سوداني"], tr:["Yerfıstığı","Fıstık"], th:["ถั่วลิสง"], el:["Φιστίκια Αμερικής","Αραχίδες"] },
  },
  soja: {
    products: { da:["Tofu","Soja sauce","Miso","Edamame","Tempeh"], en:["Tofu","Soy sauce","Miso","Edamame","Tempeh"], de:["Tofu","Sojasoße","Miso","Edamame","Tempeh"], fr:["Tofu","Sauce soja","Miso","Edamame","Tempeh"], es:["Tofu","Salsa de soja","Miso","Edamame","Tempeh"], it:["Tofu","Salsa di soia","Miso","Edamame","Tempeh"], nl:["Tofu","Sojasaus","Miso","Edamame","Tempeh"], pt:["Tofu","Molho de soja","Miso","Edamame","Tempeh"], pl:["Tofu","Sos sojowy","Miso","Edamame","Tempeh"], sv:["Tofu","Sojasås","Miso","Edamame","Tempeh"], no:["Tofu","Soyasaus","Miso","Edamame","Tempeh"], ja:["豆腐","醤油","味噌","枝豆","テンペ"], zh:["豆腐","酱油","味噌","毛豆","天贝"], ar:["توفو","صلصة الصويا","ميسو","إيدامامي","تيمبيه"], tr:["Tofu","Soya sosu","Miso","Edamame","Tempeh"], th:["เต้าหู้","ซีอิ้ว","มิโซะ","เอดาแมม","เทมเป้"], el:["Τόφου","Σάλτσα σόγιας","Μίσο","Εντάμαμε","Τέμπε"] },
    ingredients: { da:["Soja","Sojabønner","Sojalecitin","Sojaprotein","E322"], en:["Soy","Soybeans","Soy lecithin","Soy protein","E322"], de:["Soja","Sojabohnen","Sojalecithin","Sojaprotein","E322"], fr:["Soja","Haricots de soja","Lécithine de soja","Protéine de soja","E322"], es:["Soja","Habas de soja","Lecitina de soja","Proteína de soja","E322"], it:["Soia","Semi di soia","Lecitina di soia","Proteina di soia","E322"], nl:["Soja","Sojabone","Sojalecithine","Sojaprotein","E322"], pt:["Soja","Feijão de soja","Lecitina de soja","Proteína de soja","E322"], pl:["Soja","Sojowe","Lecytyna sojowa","Białko sojowe","E322"], sv:["Soja","Sojabönor","Sojalecithin","Sojaprotein","E322"], no:["Soya","Soyabønner","Sojalesitin","Sojaprotein","E322"], ja:["大豆","大豆レシチン","大豆タンパク","E322"], zh:["大豆","大豆卵磷脂","大豆蛋白","E322"], ar:["الصويا","فول الصويا","ليسيثين الصويا","E322"], tr:["Soya","Soya fasulyesi","Soya lesitini","E322"], th:["ถั่วเหลือง","เลซิตินถั่วเหลือง","E322"], el:["Σόγια","Σογιόλεκιθίνη","E322"] },
  },
  fisk: {
    products: { da:["Fiskesauce","Worcestershire","Caesar dressing","Ansjosdip"], en:["Fish sauce","Worcestershire sauce","Caesar dressing","Anchovy paste"], de:["Fischsauce","Worcestershiresauce","Caesar-Dressing","Sardellenpaste"], fr:["Sauce de poisson","Sauce Worcestershire","Vinaigrette César","Pâte d'anchois"], es:["Salsa de pescado","Salsa Worcestershire","Aderezo César","Pasta de anchoa"], it:["Salsa di pesce","Salsa Worcestershire","Condimento Caesar","Pasta di acciughe"], nl:["Vissaus","Worcestershiresaus","Caesar dressing","Ansjovispasta"], pt:["Molho de peixe","Molho Worcestershire","Molho César","Pasta de anchova"], pl:["Sos rybny","Sos worcestershire","Sos cezar","Pasta z anchois"], sv:["Fisksås","Worcestershiresås","Caesardressing","Ansjovisröra"], no:["Fiskesaus","Worcestershiresaus","Caesardressing","Ansjosvispasta"], ja:["ナンプラー","ウスターソース","シーザードレッシング","アンチョビ"], zh:["鱼露","伍斯特酱","凯撒沙拉酱","凤尾鱼酱"], ar:["صلصة السمك","صلصة وورشيسترشير","تتبيلة سيزر","معجون الأنشوجة"], tr:["Balık sosu","Worcestershire sosu","Sezar sosu","Hamsi ezmesi"], th:["น้ำปลา","ซอสวูสเตอร์","ซีซาร์เดรสซิ่ง","แอนโชวี่เพสต์"], el:["Σάλτσα ψαριού","Σάλτσα Worcestershire","Σάλτσα Καίσαρα","Πάστα αντζούγιας"] },
    ingredients: { da:["Ansjos","Laks","Tun","Makrel","Sardiner"], en:["Anchovy","Salmon","Tuna","Mackerel","Sardines"], de:["Sardellen","Lachs","Thunfisch","Makrele","Sardinen"], fr:["Anchois","Saumon","Thon","Maquereau","Sardines"], es:["Anchoas","Salmón","Atún","Caballa","Sardinas"], it:["Acciughe","Salmone","Tonno","Sgombro","Sardine"], nl:["Ansjovis","Zalm","Tonijn","Makreel","Sardines"], pt:["Anchova","Salmão","Atum","Cavala","Sardinha"], pl:["Anchois","Łosoś","Tuńczyk","Makrela","Sardynki"], sv:["Ansjovis","Lax","Tonfisk","Makrill","Sardiner"], no:["Ansjos","Laks","Tunfisk","Makrell","Sardiner"], ja:["アンチョビ","鮭","マグロ","サバ","イワシ"], zh:["凤尾鱼","三文鱼","金枪鱼","鲭鱼","沙丁鱼"], ar:["أنشوجة","سلمون","تونة","ماكريل","سردين"], tr:["Hamsi","Somon","Ton balığı","Uskumru","Sardalya"], th:["แอนโชวี่","แซลมอน","ทูน่า","ปลาแมคเคอเรล","ปลาซาร์ดีน"], el:["Αντζούγιες","Σολομός","Τόνος","Σκουμπρί","Σαρδέλες"] },
  },
  skaldyr: {
    products: { da:["Paella","Bisque","Sushi","Fiskesuppe","Bouillabaisse"], en:["Paella","Bisque","Sushi","Fish soup","Bouillabaisse"], de:["Paella","Bisque","Sushi","Fischsuppe","Bouillabaisse"], fr:["Paella","Bisque","Sushi","Soupe de poisson","Bouillabaisse"], es:["Paella","Bisque","Sushi","Sopa de pescado","Bouillabaisse"], it:["Paella","Bisque","Sushi","Zuppa di pesce","Bouillabaisse"], nl:["Paella","Bisque","Sushi","Vissoep","Bouillabaisse"], pt:["Paella","Bisque","Sushi","Sopa de peixe","Bouillabaisse"], pl:["Paella","Bisque","Sushi","Zupa rybna","Bouillabaisse"], sv:["Paella","Bisque","Sushi","Fisksoppa","Bouillabaisse"], no:["Paella","Bisque","Sushi","Fiskesuppe","Bouillabaisse"], ja:["パエリア","ビスク","寿司","魚スープ","ブイヤベース"], zh:["海鲜饭","浓汤","寿司","鱼汤","马赛鱼汤"], ar:["باييلا","شوربة كريمة","سوشي","شوربة سمك","بويابيس"], tr:["Paella","Bisque","Sushi","Balık çorbası","Bouillabaisse"], th:["ปาเอย่า","บิสก์","ซูชิ","ซุปปลา","บูยาแบส"], el:["Παέλα","Μπισκ","Σούσι","Ψαρόσουπα","Μπουγιαμπέσα"] },
    ingredients: { da:["Rejer","Krabbe","Hummer","Muslinger","Østers"], en:["Shrimp","Crab","Lobster","Mussels","Oysters"], de:["Garnelen","Krabbe","Hummer","Muscheln","Austern"], fr:["Crevettes","Crabe","Homard","Moules","Huîtres"], es:["Gambas","Cangrejo","Langosta","Mejillones","Ostras"], it:["Gamberi","Granchio","Aragosta","Cozze","Ostriche"], nl:["Garnalen","Krab","Kreeft","Mosselen","Oesters"], pt:["Camarão","Caranguejo","Lagosta","Mexilhões","Ostras"], pl:["Krewetki","Krab","Homar","Małże","Ostrygi"], sv:["Räkor","Krabba","Hummer","Musslor","Ostron"], no:["Reker","Krabbe","Hummer","Muslinger","Østers"], ja:["エビ","カニ","ロブスター","ムール貝","カキ"], zh:["虾","蟹","龙虾","贻贝","牡蛎"], ar:["روبيان","سرطان البحر","جراد البحر","بلح البحر","محار"], tr:["Karides","Yengeç","Istakoz","Midye","İstiridye"], th:["กุ้ง","ปู","กุ้งมังกร","หอยแมลงภู่","หอยนางรม"], el:["Γαρίδες","Καβούρι","Αστακός","Μύδια","Στρείδια"] },
  },
  selleri: {
    products: { da:["Bouillon","Suppe","Krydderisalt","Salat","Remoulade"], en:["Stock","Soup","Seasoning salt","Salad","Remoulade"], de:["Brühe","Suppe","Würzsalz","Salat","Remoulade"], fr:["Bouillon","Soupe","Sel aromatisé","Salade","Rémoulade"], es:["Caldo","Sopa","Sal condimentada","Ensalada","Rémoulade"], it:["Brodo","Zuppa","Sale aromatizzato","Insalata","Remoulade"], nl:["Bouillon","Soep","Kruidenzout","Salade","Remoulade"], pt:["Caldo","Sopa","Sal temperado","Salada","Remoulade"], pl:["Bulion","Zupa","Sól przyprawowa","Sałatka","Remoulada"], sv:["Buljong","Soppa","Kryddsalt","Sallad","Remoulade"], no:["Buljong","Suppe","Kryddersalt","Salat","Remoulade"], ja:["ブイヨン","スープ","シーズニングソルト","サラダ","レムラード"], zh:["高汤","汤","调味盐","沙拉","雷穆拉达酱"], ar:["مرق","شوربة","ملح متبل","سلطة","ريمولاد"], tr:["Et suyu","Çorba","Baharlı tuz","Salata","Remulad"], th:["น้ำซุป","ซุป","เกลือปรุงรส","สลัด","เรมูลาด"], el:["Ζωμός","Σούπα","Αλάτι με μπαχαρικά","Σαλάτα","Ρεμουλάντ"] },
    ingredients: { da:["Selleri","Sellerisalt","Sellerifnug","Sellerifrø"], en:["Celery","Celery salt","Celery flakes","Celery seeds"], de:["Sellerie","Selleriesalz","Selerieflocken","Selleriesamen"], fr:["Céleri","Sel de céleri","Flocons de céleri","Graines de céleri"], es:["Apio","Sal de apio","Copos de apio","Semillas de apio"], it:["Sedano","Sale di sedano","Fiocchi di sedano","Semi di sedano"], nl:["Selderij","Selderijzout","Selderijvlokken","Selderijzaad"], pt:["Aipo","Sal de aipo","Flocos de aipo","Sementes de aipo"], pl:["Seler","Sól selerowa","Płatki selera","Nasiona selera"], sv:["Selleri","Sellerisalt","Selleriflingor","Selleriefrön"], no:["Selleri","Sellerisalt","Sellerifnugg","Sellerifrø"], ja:["セロリ","セロリソルト","セロリフレーク","セロリシード"], zh:["芹菜","芹菜盐","芹菜片","芹菜籽"], ar:["كرفس","ملح الكرفس","رقائق الكرفس","بذور الكرفس"], tr:["Kereviz","Kereviz tuzu","Kereviz pul","Kereviz tohumu"], th:["คื่นฉ่าย","เกลือคื่นฉ่าย","คื่นฉ่ายแห้ง","เมล็ดคื่นฉ่าย"], el:["Σέλινο","Αλάτι σέλινου","Νιφάδες σέλινου","Σπόροι σέλινου"] },
  },
  sennep: {
    products: { da:["Sennep","Dressing","Marinade","Curry","Pickles"], en:["Mustard","Dressing","Marinade","Curry","Pickles"], de:["Senf","Dressing","Marinade","Curry","Gewürzgurken"], fr:["Moutarde","Vinaigrette","Marinade","Curry","Cornichons"], es:["Mostaza","Aderezo","Marinada","Curry","Pepinillos"], it:["Senape","Condimento","Marinata","Curry","Sottaceti"], nl:["Mosterd","Dressing","Marinade","Curry","Augurken"], pt:["Mostarda","Molho","Marinada","Caril","Pickles"], pl:["Musztarda","Dressing","Marynata","Curry","Ogórki konserwowe"], sv:["Senap","Dressing","Marinad","Curry","Pickles"], no:["Sennep","Dressing","Marinade","Karri","Pickles"], ja:["マスタード","ドレッシング","マリネ","カレー","ピクルス"], zh:["芥末","沙拉酱","腌料","咖喱","泡菜"], ar:["خردل","صلصة السلطة","تتبيلة","كاري","مخللات"], tr:["Hardal","Sos","Turşu sosu","Köri","Turşu"], th:["มัสตาร์ด","น้ำสลัด","น้ำหมัก","แกงกะหรี่","ดองผัก"], el:["Μουστάρδα","Σαλτσάκι","Μαρινάδα","Κάρυ","Πίκλες"] },
    ingredients: { da:["Sennepsfrø","Sennepsmel","Sennepsolie","Sennepspulver"], en:["Mustard seeds","Mustard flour","Mustard oil","Mustard powder"], de:["Senfkörner","Senfmehl","Senföl","Senfpulver"], fr:["Graines de moutarde","Farine de moutarde","Huile de moutarde","Poudre de moutarde"], es:["Semillas de mostaza","Harina de mostaza","Aceite de mostaza","Polvo de mostaza"], it:["Semi di senape","Farina di senape","Olio di senape","Polvere di senape"], nl:["Mosterdzaad","Mosterdmeel","Mosterdie","Mosterdpoeder"], pt:["Sementes de mostarda","Farinha de mostarda","Óleo de mostarda","Pó de mostarda"], pl:["Nasiona gorczycy","Mąka gorczycowa","Olej gorczycowy","Proszek gorczycowy"], sv:["Senapsfrön","Senapsmjöl","Senapsolja","Senapspulver"], no:["Sennepsfrø","Sennepsmel","Sennepsolje","Sennepspulver"], ja:["マスタードシード","マスタードフラワー","マスタードオイル","マスタードパウダー"], zh:["芥末籽","芥末粉","芥末油","芥末粉末"], ar:["بذور الخردل","دقيق الخردل","زيت الخردل","مسحوق الخردل"], tr:["Hardal tohumu","Hardal unu","Hardal yağı","Hardal tozu"], th:["เมล็ดมัสตาร์ด","แป้งมัสตาร์ด","น้ำมันมัสตาร์ด","ผงมัสตาร์ด"], el:["Σπόροι μουστάρδας","Αλεύρι μουστάρδας","Λάδι μουστάρδας","Σκόνη μουστάρδας"] },
  },
  sesam: {
    products: { da:["Hummus","Tahini","Bagels","Sushi","Halvah"], en:["Hummus","Tahini","Bagels","Sushi","Halvah"], de:["Hummus","Tahini","Bagels","Sushi","Halva"], fr:["Houmous","Tahiné","Bagels","Sushi","Halva"], es:["Hummus","Tahini","Bagels","Sushi","Halva"], it:["Hummus","Tahini","Bagel","Sushi","Halva"], nl:["Hummus","Tahini","Bagels","Sushi","Halva"], pt:["Hummus","Tahini","Bagels","Sushi","Halva"], pl:["Hummus","Tahini","Bagele","Sushi","Chałwa"], sv:["Hummus","Tahini","Bagels","Sushi","Halva"], no:["Hummus","Tahini","Bagels","Sushi","Halva"], ja:["フムス","タヒニ","ベーグル","寿司","ハルヴァ"], zh:["鹰嘴豆泥","芝麻酱","百吉饼","寿司","哈尔瓦"], ar:["حمص","طحينة","بيغل","سوشي","حلاوة طحينية"], tr:["Humus","Tahin","Bagel","Sushi","Helva"], th:["ฮัมมัส","ทาฮีนี","เบเกิล","ซูชิ","ฮาลวา"], el:["Χούμους","Ταχίνι","Μπέιγκελ","Σούσι","Χαλβάς"] },
    ingredients: { da:["Sesam","Sesamfrø","Tahini","Sesamolie","Sesammel"], en:["Sesame","Sesame seeds","Tahini","Sesame oil","Sesame flour"], de:["Sesam","Sesamsamen","Tahini","Sesamöl","Sesammehl"], fr:["Sésame","Graines de sésame","Tahiné","Huile de sésame","Farine de sésame"], es:["Sésamo","Semillas de sésamo","Tahini","Aceite de sésamo","Harina de sésamo"], it:["Sesamo","Semi di sesamo","Tahini","Olio di sesamo","Farina di sesamo"], nl:["Sesam","Sesamzaad","Tahini","Sesamolie","Sesambloem"], pt:["Sésamo","Sementes de sésamo","Tahini","Óleo de sésamo","Farinha de sésamo"], pl:["Sezam","Ziarna sezamu","Tahini","Olej sezamowy","Mąka sezamowa"], sv:["Sesam","Sesamfrön","Tahini","Sesamolja","Sesammjöl"], no:["Sesam","Sesamfrø","Tahini","Sesamolje","Sesammel"], ja:["ゴマ","ゴマの種","タヒニ","ゴマ油","ゴマ粉"], zh:["芝麻","芝麻籽","芝麻酱","芝麻油","芝麻粉"], ar:["سمسم","بذور السمسم","طحينة","زيت السمسم","دقيق السمسم"], tr:["Susam","Susam tohumu","Tahin","Susam yağı","Susam unu"], th:["งา","เมล็ดงา","ทาฮีนี","น้ำมันงา","แป้งงา"], el:["Σουσάμι","Σπόροι σουσαμιού","Ταχίνι","Λάδι σουσαμιού","Αλεύρι σουσαμιού"] },
  },
  svovl: {
    products: { da:["Vin","Tørrede frugter","Konserves","Eddike","Syltetøj"], en:["Wine","Dried fruits","Preserves","Vinegar","Jam"], de:["Wein","Trockenfrüchte","Konserven","Essig","Marmelade"], fr:["Vin","Fruits secs","Conserves","Vinaigre","Confiture"], es:["Vino","Frutas secas","Conservas","Vinagre","Mermelada"], it:["Vino","Frutta secca","Conserve","Aceto","Marmellata"], nl:["Wijn","Gedroogd fruit","Conserven","Azijn","Jam"], pt:["Vinho","Frutas secas","Conservas","Vinagre","Compota"], pl:["Wino","Suszone owoce","Przetwory","Ocet","Dżem"], sv:["Vin","Torkad frukt","Konserver","Vinäger","Sylt"], no:["Vin","Tørket frukt","Hermetikk","Eddik","Syltetøy"], ja:["ワイン","ドライフルーツ","保存食","酢","ジャム"], zh:["葡萄酒","干果","罐头","醋","果酱"], ar:["نبيذ","فاكهة مجففة","معلبات","خل","مربى"], tr:["Şarap","Kurutulmuş meyve","Konserveler","Sirke","Reçel"], th:["ไวน์","ผลไม้แห้ง","อาหารกระป๋อง","น้ำส้มสายชู","แยม"], el:["Κρασί","Αποξηραμένα φρούτα","Κονσέρβες","Ξύδι","Μαρμελάδα"] },
    ingredients: { da:["E220","E221","E222","Sulfitter","SO₂","Svovldioxid"], en:["E220","E221","E222","Sulphites","SO₂","Sulphur dioxide"], de:["E220","E221","E222","Sulfite","SO₂","Schwefeldioxid"], fr:["E220","E221","E222","Sulfites","SO₂","Dioxyde de soufre"], es:["E220","E221","E222","Sulfitos","SO₂","Dióxido de azufre"], it:["E220","E221","E222","Solfiti","SO₂","Anidride solforosa"], nl:["E220","E221","E222","Sulfieten","SO₂","Zwaveldioxide"], pt:["E220","E221","E222","Sulfitos","SO₂","Dióxido de enxofre"], pl:["E220","E221","E222","Siarczyny","SO₂","Dwutlenek siarki"], sv:["E220","E221","E222","Sulfiter","SO₂","Svaveldioxid"], no:["E220","E221","E222","Sulfitter","SO₂","Svoveldioksid"], ja:["E220","E221","E222","亜硫酸塩","SO₂","二酸化硫黄"], zh:["E220","E221","E222","亚硫酸盐","SO₂","二氧化硫"], ar:["E220","E221","E222","كبريتيت","SO₂","ثاني أكسيد الكبريت"], tr:["E220","E221","E222","Sülfit","SO₂","Kükürt dioksit"], th:["E220","E221","E222","ซัลไฟต์","SO₂","ซัลเฟอร์ไดออกไซด์"], el:["E220","E221","E222","Θειώδη","SO₂","Διοξείδιο του θείου"] },
  },
  lupin: {
    products: { da:["Glutenfri mel","Pasta","Brød","Snacks","Panering"], en:["Gluten-free flour","Pasta","Bread","Snacks","Breading"], de:["Glutenfreies Mehl","Pasta","Brot","Snacks","Panade"], fr:["Farine sans gluten","Pâtes","Pain","Snacks","Chapelure"], es:["Harina sin gluten","Pasta","Pan","Snacks","Rebozado"], it:["Farina senza glutine","Pasta","Pane","Snack","Panatura"], nl:["Glutenvrij meel","Pasta","Brood","Snacks","Paneermeel"], pt:["Farinha sem glúten","Massa","Pão","Snacks","Panado"], pl:["Mąka bezglutenowa","Makaron","Chleb","Przekąski","Panierka"], sv:["Glutenfritt mjöl","Pasta","Bröd","Snacks","Panering"], no:["Glutenfritt mel","Pasta","Brød","Snacks","Panering"], ja:["グルテンフリー小麦粉","パスタ","パン","スナック","パン粉"], zh:["无麸质面粉","面食","面包","零食","面包屑"], ar:["دقيق خالي من الغلوتين","معكرونة","خبز","وجبات خفيفة","فتات الخبز"], tr:["Glutensiz un","Makarna","Ekmek","Atıştırmalık","Ekmek kırıntısı"], th:["แป้งไม่มีกลูเตน","พาสต้า","ขนมปัง","ขนมขบเคี้ยว","เกล็ดขนมปัง"], el:["Αλεύρι χωρίς γλουτένη","Ζυμαρικά","Ψωμί","Σνακ","Πανάδα"] },
    ingredients: { da:["Lupinmel","Lupinfrø","Lupinprotein","Lupinfiber"], en:["Lupin flour","Lupin seeds","Lupin protein","Lupin fibre"], de:["Lupinenmehl","Lupinensamen","Lupinenprotein","Lupinenfaser"], fr:["Farine de lupin","Graines de lupin","Protéine de lupin","Fibre de lupin"], es:["Harina de altramuz","Semillas de altramuz","Proteína de altramuz","Fibra de altramuz"], it:["Farina di lupino","Semi di lupino","Proteina di lupino","Fibra di lupino"], nl:["Lupinebloem","Lupinezaad","Lupineprotein","Lupinevezel"], pt:["Farinha de tremoço","Sementes de tremoço","Proteína de tremoço","Fibra de tremoço"], pl:["Mąka łubinowa","Nasiona łubinu","Białko łubinu","Błonnik łubinu"], sv:["Lupinmjöl","Lupinfrön","Lupinprotein","Lupinfibrer"], no:["Lupinmel","Lupinfrø","Lupinprotein","Lupinfiber"], ja:["ルピナス粉","ルピナス種子","ルピナスタンパク","ルピナス繊維"], zh:["羽扇豆粉","羽扇豆种子","羽扇豆蛋白","羽扇豆纤维"], ar:["دقيق الترمس","بذور الترمس","بروتين الترمس","ألياف الترمس"], tr:["Lupin unu","Lupin tohumu","Lupin proteini","Lupin lifi"], th:["แป้งลูพิน","เมล็ดลูพิน","โปรตีนลูพิน","ไฟเบอร์ลูพิน"], el:["Αλεύρι λούπινων","Σπόροι λούπινων","Πρωτεΐνη λούπινων","Ίνες λούπινων"] },
  },
  bloeddyr: {
    products: { da:["Paella","Pasta frutti di mare","Sushi","Risotto"], en:["Paella","Seafood pasta","Sushi","Risotto"], de:["Paella","Meeresfrüchtepasta","Sushi","Risotto"], fr:["Paella","Pâtes aux fruits de mer","Sushi","Risotto"], es:["Paella","Pasta con mariscos","Sushi","Risotto"], it:["Paella","Pasta ai frutti di mare","Sushi","Risotto"], nl:["Paella","Zeevruchtenpasta","Sushi","Risotto"], pt:["Paella","Massa com mariscos","Sushi","Risoto"], pl:["Paella","Makaron z owocami morza","Sushi","Risotto"], sv:["Paella","Skaldjurspasta","Sushi","Risotto"], no:["Paella","Sjømatpasta","Sushi","Risotto"], ja:["パエリア","シーフードパスタ","寿司","リゾット"], zh:["海鲜饭","海鲜面食","寿司","意大利烩饭"], ar:["باييلا","معكرونة بحرية","سوشي","ريزوتو"], tr:["Paella","Deniz ürünleri makarnası","Sushi","Risotto"], th:["ปาเอย่า","พาสต้าซีฟู้ด","ซูชิ","ริซอตโต้"], el:["Παέλα","Ζυμαρικά θαλασσινών","Σούσι","Ριζότο"] },
    ingredients: { da:["Blæksprutte","Østers","Muslinger","Snegle","Kammusling"], en:["Squid","Oysters","Mussels","Snails","Scallops"], de:["Tintenfisch","Austern","Muscheln","Schnecken","Jakobsmuscheln"], fr:["Calamar","Huîtres","Moules","Escargots","Coquilles Saint-Jacques"], es:["Calamar","Ostras","Mejillones","Caracoles","Vieiras"], it:["Calamaro","Ostriche","Cozze","Lumache","Capesante"], nl:["Inktvis","Oesters","Mosselen","Slakken","Sint-jakobsschelpen"], pt:["Lula","Ostras","Mexilhões","Caracóis","Vieiras"], pl:["Kałamarnica","Ostrygi","Małże","Ślimaki","Przegrzebki"], sv:["Bläckfisk","Ostron","Musslor","Sniglar","Pilgrimsmusslor"], no:["Blekksprut","Østers","Muslinger","Snegler","Kamskjell"], ja:["イカ","カキ","ムール貝","カタツムリ","ホタテ"], zh:["鱿鱼","牡蛎","贻贝","蜗牛","扇贝"], ar:["حبار","محار","بلح البحر","حلزون","إسقلوب"], tr:["Kalamar","İstiridye","Midye","Salyangoz","Deniz tarağı"], th:["ปลาหมึก","หอยนางรม","หอยแมลงภู่","หอยทาก","หอยเชลล์"], el:["Καλαμάρι","Στρείδια","Μύδια","Σαλιγκάρια","Χτένια"] },
  },
};

export const DIETS = [
  { id:"vegan",       label:"Vegansk",       desc:"Ingen animalske produkter" },
  { id:"vegetarian",  label:"Vegetarisk",    desc:"Ingen kød eller fisk" },
  { id:"pescetarian", label:"Pescetarisk",   desc:"Ingen kød, men fisk ok" },
  { id:"gluten-free", label:"Glutenfri",     desc:"Ingen gluten" },
  { id:"keto",        label:"Keto",          desc:"Lavt kulhydratindhold" },
];

export const AVATAR_COLORS = ["#52b788","#74c69d","#40916c","#b7e4c7","#2d6a4f","#95d5b2","#f4a261","#e76f51"];

export const HOME_TIPS = [
  { icon:"warning", title:"Gluten er overalt", text:"Gluten findes ikke kun i brød — det gemmer sig i saucer, supper og krydderier. Scan altid." },
  { icon:"info", title:"Læs altid etiketten", text:"Opskrifter ændres uden varsel. Et produkt du har spist trygt før, kan have nye ingredienser." },
  { icon:"family", title:"Tilføj din familie", text:"Opret profiler for hele familien — så ser du på én gang hvem der kan spise hvad." },
  { icon:"heart", title:"Hjælp fællesskabet", text:"Scan du et ukendt produkt? Indsend det! Databasen vokser med hjælp fra brugere som dig." },
  { icon:"warning", title:"Spor af allergener", text:"'Kan indeholde spor af' er ikke uskadeligt. For stærkt allergiske kan selv spormængder være farlige." },
  { icon:"cart", title:"Planlæg din indkøbsliste", text:"Brug indkøbslisten til at tjekke produkter inden du handler — spar tid i butikken." },
  { icon:"search", title:"Søg inden du handler", text:"Søg på produkter inden du tager i butikken — så ved du hvad du kan købe trygt." },
  { icon:"bulb", title:"Tilføj til hjemskærm", text:"Tilføj EatSafe til din telefons hjemskærm for hurtig adgang — det føles som en rigtig app." },
];

// ─── HJÆLPEFUNKTIONER ────────────────────────────────────────────────────────

export const uid = () => Math.random().toString(36).slice(2,9);

// Pæn ingrediensliste — fremhæver allergener med STORE BOGSTAVER

export const MADPAS_LANGUAGES = [
  { code:"da", flag:"🇩🇰", name:"Dansk",      bcp:"da-DK" },
  { code:"en", flag:"🇬🇧", name:"English",    bcp:"en-GB" },
  { code:"de", flag:"🇩🇪", name:"Deutsch",    bcp:"de-DE" },
  { code:"fr", flag:"🇫🇷", name:"Français",   bcp:"fr-FR" },
  { code:"es", flag:"🇪🇸", name:"Español",    bcp:"es-ES" },
  { code:"it", flag:"🇮🇹", name:"Italiano",   bcp:"it-IT" },
  { code:"nl", flag:"🇳🇱", name:"Nederlands", bcp:"nl-NL" },
  { code:"pt", flag:"🇵🇹", name:"Português",  bcp:"pt-PT" },
  { code:"pl", flag:"🇵🇱", name:"Polski",     bcp:"pl-PL" },
  { code:"sv", flag:"🇸🇪", name:"Svenska",    bcp:"sv-SE" },
  { code:"no", flag:"🇳🇴", name:"Norsk",      bcp:"nb-NO" },
  { code:"ja", flag:"🇯🇵", name:"日本語",      bcp:"ja-JP" },
  { code:"zh", flag:"🇨🇳", name:"中文",        bcp:"zh-CN" },
  { code:"ar", flag:"🇸🇦", name:"العربية",    bcp:"ar-SA", rtl:true },
  { code:"tr", flag:"🇹🇷", name:"Türkçe",     bcp:"tr-TR" },
  { code:"th", flag:"🇹🇭", name:"ภาษาไทย",    bcp:"th-TH" },
  { code:"el", flag:"🇬🇷", name:"Ελληνικά",   bcp:"el-GR" },
];

export const ALLERGEN_T = {
  gluten:      { en:{n:"Gluten",d:"Contains gluten (wheat, rye, barley, oats, spelt)"},de:{n:"Gluten",d:"Enthält Gluten (Weizen, Roggen, Gerste, Hafer, Dinkel)"},fr:{n:"Gluten",d:"Contient du gluten (blé, seigle, orge, avoine, épeautre)"},es:{n:"Gluten",d:"Contiene gluten (trigo, centeno, cebada, avena, espelta)"},it:{n:"Glutine",d:"Contiene glutine (frumento, segale, orzo, avena, farro)"},nl:{n:"Gluten",d:"Bevat gluten (tarwe, rogge, gerst, haver, spelt)"},pt:{n:"Glúten",d:"Contém glúten (trigo, centeio, cevada, aveia, espelta)"},pl:{n:"Gluten",d:"Zawiera gluten (pszenica, żyto, jęczmień, owies, orkisz)"},sv:{n:"Gluten",d:"Innehåller gluten (vete, råg, korn, havre, dinkel)"},no:{n:"Gluten",d:"Inneholder gluten (hvete, rug, bygg, havre, spelt)"},ja:{n:"グルテン",d:"グルテン含有（小麦・ライ麦・大麦・燕麦・スペルト小麦）"},zh:{n:"麸质",d:"含麸质（小麦、黑麦、大麦、燕麦、斯佩尔特小麦）"},ar:{n:"الغلوتين",d:"يحتوي على الغلوتين (قمح، جاودار، شعير، شوفان)"},tr:{n:"Gluten",d:"Gluten içerir (buğday, çavdar, arpa, yulaf, kavılca)"},th:{n:"กลูเตน",d:"มีกลูเตน (ข้าวสาลี, ข้าวไรย์, ข้าวบาร์เลย์, ข้าวโอ๊ต)"},el:{n:"Γλουτένη",d:"Περιέχει γλουτένη (σιτάρι, σίκαλη, κριθάρι, βρώμη, ζέα)"} },
  laktose:     { en:{n:"Lactose / Dairy",d:"Contains milk and dairy products (lactose)"},de:{n:"Laktose / Milch",d:"Enthält Milch und Milchprodukte (Laktose)"},fr:{n:"Lactose / Lait",d:"Contient du lait et des produits laitiers (lactose)"},es:{n:"Lactosa / Lácteos",d:"Contiene leche y productos lácteos (lactosa)"},it:{n:"Lattosio / Latte",d:"Contiene latte e latticini (lattosio)"},nl:{n:"Lactose / Melk",d:"Bevat melk en zuivelproducten (lactose)"},pt:{n:"Lactose / Leite",d:"Contém leite e produtos lácteos (lactose)"},pl:{n:"Laktoza / Mleko",d:"Zawiera mleko i produkty mleczne (laktoza)"},sv:{n:"Laktos / Mjölk",d:"Innehåller mjölk och mjölkprodukter (laktos)"},no:{n:"Laktose / Melk",d:"Inneholder melk og meieriprodukter (laktose)"},ja:{n:"乳糖 / 乳製品",d:"牛乳および乳製品を含む（ラクトース）"},zh:{n:"乳糖 / 乳制品",d:"含有牛奶和乳制品（乳糖）"},ar:{n:"اللاكتوز / الألبان",d:"يحتوي على الحليب ومنتجات الألبان"},tr:{n:"Laktoz / Süt",d:"Süt ve süt ürünleri içerir (laktoz)"},th:{n:"แลคโตส / นม",d:"มีนมและผลิตภัณฑ์จากนม (แลคโตส)"},el:{n:"Λακτόζη / Γάλα",d:"Περιέχει γάλα και γαλακτοκομικά (λακτόζη)"} },
  aeg:         { en:{n:"Eggs",d:"Contains eggs and egg products"},de:{n:"Ei",d:"Enthält Eier und Eiprodukte"},fr:{n:"Œufs",d:"Contient des œufs et ovoproduits"},es:{n:"Huevos",d:"Contiene huevos y ovoproductos"},it:{n:"Uova",d:"Contiene uova e ovoprodotti"},nl:{n:"Eieren",d:"Bevat eieren en eiproducten"},pt:{n:"Ovos",d:"Contém ovos e produtos à base de ovos"},pl:{n:"Jaja",d:"Zawiera jaja i produkty na bazie jaj"},sv:{n:"Ägg",d:"Innehåller ägg och äggprodukter"},no:{n:"Egg",d:"Inneholder egg og eggprodukter"},ja:{n:"卵",d:"卵および卵製品を含む"},zh:{n:"鸡蛋",d:"含有鸡蛋和蛋制品"},ar:{n:"البيض",d:"يحتوي على البيض ومنتجاته"},tr:{n:"Yumurta",d:"Yumurta ve yumurta ürünleri içerir"},th:{n:"ไข่",d:"มีไข่และผลิตภัณฑ์จากไข่"},el:{n:"Αυγά",d:"Περιέχει αυγά και προϊόντα αυγών"} },
  noedder:     { en:{n:"Tree Nuts",d:"Contains nuts (almonds, hazelnuts, walnuts, cashews, pistachios etc.)"},de:{n:"Schalenfrüchte",d:"Enthält Nüsse (Mandeln, Haselnüsse, Walnüsse, Cashews, Pistazien usw.)"},fr:{n:"Fruits à coque",d:"Contient des fruits à coque (amandes, noisettes, noix, cajou, pistaches, etc.)"},es:{n:"Frutos secos",d:"Contiene frutos secos (almendras, avellanas, nueces, anacardos, pistachos, etc.)"},it:{n:"Frutta a guscio",d:"Contiene frutta a guscio (mandorle, nocciole, noci, anacardi, pistacchi ecc.)"},nl:{n:"Noten",d:"Bevat noten (amandelen, hazelnoten, walnoten, cashewnoten, pistachenoten, etc.)"},pt:{n:"Frutos de casca rija",d:"Contém frutos de casca rija (amêndoas, avelãs, nozes, cajus, pistáchios, etc.)"},pl:{n:"Orzechy",d:"Zawiera orzechy (migdały, orzechy laskowe, włoskie, nerkowce, pistacje itp.)"},sv:{n:"Nötter",d:"Innehåller nötter (mandlar, hasselnötter, valnötter, cashewnötter, pistaschnötter m.fl.)"},no:{n:"Nøtter",d:"Inneholder nøtter (mandler, hasselnøtter, valnøtter, cashewnøtter, pistasjnøtter m.fl.)"},ja:{n:"ナッツ類",d:"ナッツ類含有（アーモンド・ヘーゼルナッツ・クルミ・カシューナッツ・ピスタチオ等）"},zh:{n:"坚果",d:"含有坚果（杏仁、榛子、核桃、腰果、开心果等）"},ar:{n:"المكسرات",d:"يحتوي على المكسرات (اللوز، البندق، الجوز، الكاجو، الفستق)"},tr:{n:"Kabuklu Yemişler",d:"Kabuklu yemiş içerir (badem, fındık, ceviz, kaju, antep fıstığı vb.)"},th:{n:"ถั่วต้นไม้",d:"มีถั่ว (อัลมอนด์, เฮเซลนัท, วอลนัท, มะม่วงหิมพานต์, พิสตาชิโอ)"},el:{n:"Ξηροί καρποί",d:"Περιέχει ξηρούς καρπούς (αμύγδαλα, φουντούκια, καρύδια, κάσιους, φιστίκια)"} },
  jordnoedder: { en:{n:"Peanuts",d:"Contains peanuts and peanut products"},de:{n:"Erdnüsse",d:"Enthält Erdnüsse und Erdnussprodukte"},fr:{n:"Arachides",d:"Contient des arachides (cacahuètes) et produits"},es:{n:"Cacahuetes",d:"Contiene cacahuetes y productos a base de cacahuetes"},it:{n:"Arachidi",d:"Contiene arachidi e prodotti a base di arachidi"},nl:{n:"Pinda's",d:"Bevat pinda's en pindaproducten"},pt:{n:"Amendoins",d:"Contém amendoins e produtos à base de amendoins"},pl:{n:"Orzeszki ziemne",d:"Zawiera orzeszki ziemne i produkty z orzeszków ziemnych"},sv:{n:"Jordnötter",d:"Innehåller jordnötter och jordnötsprodukter"},no:{n:"Peanøtter",d:"Inneholder peanøtter og peanøttprodukter"},ja:{n:"ピーナッツ",d:"ピーナッツおよびピーナッツ製品を含む"},zh:{n:"花生",d:"含有花生和花生制品"},ar:{n:"الفول السوداني",d:"يحتوي على الفول السوداني ومنتجاته"},tr:{n:"Yerfıstığı",d:"Yerfıstığı ve yerfıstığı ürünleri içerir"},th:{n:"ถั่วลิสง",d:"มีถั่วลิสงและผลิตภัณฑ์จากถั่วลิสง"},el:{n:"Φιστίκια",d:"Περιέχει φιστίκια και προϊόντα φιστικιών"} },
  soja:        { en:{n:"Soy / Soya",d:"Contains soy and soy-based products"},de:{n:"Soja",d:"Enthält Soja und sojahaltige Produkte"},fr:{n:"Soja",d:"Contient du soja et des produits à base de soja"},es:{n:"Soja",d:"Contiene soja y productos a base de soja"},it:{n:"Soia",d:"Contiene soia e prodotti a base di soia"},nl:{n:"Soja",d:"Bevat soja en sojaproducten"},pt:{n:"Soja",d:"Contém soja e produtos à base de soja"},pl:{n:"Soja",d:"Zawiera soję i produkty sojowe"},sv:{n:"Soja",d:"Innehåller soja och sojabaserade produkter"},no:{n:"Soya",d:"Inneholder soya og soyabaserte produkter"},ja:{n:"大豆",d:"大豆および大豆製品を含む"},zh:{n:"大豆",d:"含有大豆和大豆制品"},ar:{n:"الصويا",d:"يحتوي على الصويا ومنتجاتها"},tr:{n:"Soya",d:"Soya ve soya ürünleri içerir"},th:{n:"ถั่วเหลือง",d:"มีถั่วเหลืองและผลิตภัณฑ์จากถั่วเหลือง"},el:{n:"Σόγια",d:"Περιέχει σόγια και προϊόντα σόγιας"} },
  fisk:        { en:{n:"Fish",d:"Contains fish and fish products"},de:{n:"Fisch",d:"Enthält Fisch und Fischprodukte"},fr:{n:"Poisson",d:"Contient du poisson et des produits à base de poisson"},es:{n:"Pescado",d:"Contiene pescado y productos a base de pescado"},it:{n:"Pesce",d:"Contiene pesce e prodotti ittici"},nl:{n:"Vis",d:"Bevat vis en visproducten"},pt:{n:"Peixe",d:"Contém peixe e produtos à base de peixe"},pl:{n:"Ryby",d:"Zawiera ryby i produkty rybne"},sv:{n:"Fisk",d:"Innehåller fisk och fiskprodukter"},no:{n:"Fisk",d:"Inneholder fisk og fiskeprodukter"},ja:{n:"魚",d:"魚および魚製品を含む"},zh:{n:"鱼类",d:"含有鱼和鱼制品"},ar:{n:"السمك",d:"يحتوي على السمك ومنتجاته"},tr:{n:"Balık",d:"Balık ve balık ürünleri içerir"},th:{n:"ปลา",d:"มีปลาและผลิตภัณฑ์จากปลา"},el:{n:"Ψάρι",d:"Περιέχει ψάρι και προϊόντα ψαριού"} },
  skaldyr:     { en:{n:"Shellfish / Crustaceans",d:"Contains crustaceans and shellfish (shrimp, crab, lobster, mussels etc.)"},de:{n:"Krebstiere / Schalentiere",d:"Enthält Krebstiere und Schalentiere (Garnelen, Krabben, Hummer, Muscheln)"},fr:{n:"Crustacés / Mollusques",d:"Contient des crustacés et mollusques (crevettes, crabe, homard, moules)"},es:{n:"Crustáceos / Mariscos",d:"Contiene crustáceos y mariscos (gambas, cangrejo, langosta, mejillones)"},it:{n:"Crostacei / Molluschi",d:"Contiene crostacei e molluschi (gamberi, granchio, aragosta, cozze)"},nl:{n:"Schaaldieren",d:"Bevat schaaldieren (garnalen, krab, kreeft, mosselen)"},pt:{n:"Crustáceos / Moluscos",d:"Contém crustáceos e moluscos (camarão, caranguejo, lagosta, mexilhões)"},pl:{n:"Skorupiaki",d:"Zawiera skorupiaki (krewetki, kraby, homary, małże)"},sv:{n:"Skaldjur",d:"Innehåller skaldjur (räkor, krabba, hummer, musslor)"},no:{n:"Skalldyr",d:"Inneholder skalldyr (reker, krabbe, hummer, muslinger)"},ja:{n:"甲殻類・貝類",d:"甲殻類・貝類含有（エビ・カニ・ロブスター・ムール貝等）"},zh:{n:"甲壳类 / 贝类",d:"含有甲壳类和贝类（虾、蟹、龙虾、贻贝等）"},ar:{n:"القشريات والمحار",d:"يحتوي على القشريات والمحار"},tr:{n:"Kabuklu Deniz Ürünleri",d:"Kabuklu deniz ürünleri içerir (karides, yengeç, ıstakoz, midye)"},th:{n:"สัตว์มีเปลือก",d:"มีสัตว์มีเปลือก (กุ้ง, ปู, กุ้งมังกร, หอย)"},el:{n:"Οστρακοειδή",d:"Περιέχει οστρακοειδή (γαρίδες, καβούρι, αστακός, μύδια)"} },
  selleri:     { en:{n:"Celery",d:"Contains celery and celery products"},de:{n:"Sellerie",d:"Enthält Sellerie und Sellerieprodukte"},fr:{n:"Céleri",d:"Contient du céleri et produits à base de céleri"},es:{n:"Apio",d:"Contiene apio y productos a base de apio"},it:{n:"Sedano",d:"Contiene sedano e prodotti a base di sedano"},nl:{n:"Selderij",d:"Bevat selderij en selderijproducten"},pt:{n:"Aipo",d:"Contém aipo e produtos à base de aipo"},pl:{n:"Seler",d:"Zawiera seler i produkty na bazie selera"},sv:{n:"Selleri",d:"Innehåller selleri och selleriprodukter"},no:{n:"Selleri",d:"Inneholder selleri og selleriprodukter"},ja:{n:"セロリ",d:"セロリおよびセロリ製品を含む"},zh:{n:"芹菜",d:"含有芹菜和芹菜制品"},ar:{n:"الكرفس",d:"يحتوي على الكرفس ومنتجاته"},tr:{n:"Kereviz",d:"Kereviz ve kereviz ürünleri içerir"},th:{n:"คื่นฉ่าย",d:"มีคื่นฉ่ายและผลิตภัณฑ์จากคื่นฉ่าย"},el:{n:"Σέλινο",d:"Περιέχει σέλινο και προϊόντα σέλινου"} },
  sennep:      { en:{n:"Mustard",d:"Contains mustard and mustard products"},de:{n:"Senf",d:"Enthält Senf und Senfprodukte"},fr:{n:"Moutarde",d:"Contient de la moutarde et produits à base de moutarde"},es:{n:"Mostaza",d:"Contiene mostaza y productos a base de mostaza"},it:{n:"Senape",d:"Contiene senape e prodotti a base di senape"},nl:{n:"Mosterd",d:"Bevat mosterd en mosterdbevattende producten"},pt:{n:"Mostarda",d:"Contém mostarda e produtos à base de mostarda"},pl:{n:"Gorczyca",d:"Zawiera gorczycę i produkty na bazie gorczycy"},sv:{n:"Senap",d:"Innehåller senap och senapsprodukter"},no:{n:"Sennep",d:"Inneholder sennep og sennepsprodukter"},ja:{n:"マスタード",d:"マスタードおよびマスタード製品を含む"},zh:{n:"芥末",d:"含有芥末和芥末制品"},ar:{n:"الخردل",d:"يحتوي على الخردل ومنتجاته"},tr:{n:"Hardal",d:"Hardal ve hardal ürünleri içerir"},th:{n:"มัสตาร์ด",d:"มีมัสตาร์ดและผลิตภัณฑ์จากมัสตาร์ด"},el:{n:"Μουστάρδα",d:"Περιέχει μουστάρδα και προϊόντα μουστάρδας"} },
  sesam:       { en:{n:"Sesame",d:"Contains sesame seeds and sesame products"},de:{n:"Sesam",d:"Enthält Sesamsamen und Sesamprodukte"},fr:{n:"Sésame",d:"Contient des graines de sésame et produits à base de sésame"},es:{n:"Sésamo",d:"Contiene semillas de sésamo y productos a base de sésamo"},it:{n:"Sesamo",d:"Contiene semi di sesamo e prodotti a base di sesamo"},nl:{n:"Sesam",d:"Bevat sesamzaad en sesamproducten"},pt:{n:"Sésamo",d:"Contém sementes de sésamo e produtos à base de sésamo"},pl:{n:"Sezam",d:"Zawiera ziarna sezamu i produkty sezamowe"},sv:{n:"Sesam",d:"Innehåller sesamfrön och sesamprodukter"},no:{n:"Sesam",d:"Inneholder sesamfrø og sesamprodukter"},ja:{n:"ゴマ",d:"ゴマおよびゴマ製品を含む"},zh:{n:"芝麻",d:"含有芝麻和芝麻制品"},ar:{n:"السمسم",d:"يحتوي على بذور السمسم ومنتجاته"},tr:{n:"Susam",d:"Susam tohumu ve susam ürünleri içerir"},th:{n:"งา",d:"มีเมล็ดงาและผลิตภัณฑ์จากงา"},el:{n:"Σουσάμι",d:"Περιέχει σουσάμι και προϊόντα σουσαμιού"} },
  svovl:       { en:{n:"Sulphites / Sulfites",d:"Contains sulphites/sulphur dioxide (preservative)"},de:{n:"Sulfite / SO₂",d:"Enthält Sulfite/Schwefeldioxid (Konservierungsmittel)"},fr:{n:"Sulfites / SO₂",d:"Contient des sulfites/dioxyde de soufre (conservateur)"},es:{n:"Sulfitos / SO₂",d:"Contiene sulfitos/dióxido de azufre (conservante)"},it:{n:"Solfiti / SO₂",d:"Contiene solfiti/anidride solforosa (conservante)"},nl:{n:"Sulfieten / SO₂",d:"Bevat sulfieten/zwaveldioxide (conserveermiddel)"},pt:{n:"Sulfitos / SO₂",d:"Contém sulfitos/dióxido de enxofre (conservante)"},pl:{n:"Siarczyny / SO₂",d:"Zawiera siarczyny/dwutlenek siarki (konserwant)"},sv:{n:"Sulfiter / SO₂",d:"Innehåller sulfiter/svaveldioxid (konserveringsmedel)"},no:{n:"Sulfitter / SO₂",d:"Inneholder sulfitter/svoveldioksid (konserveringsmiddel)"},ja:{n:"亜硫酸塩 / SO₂",d:"亜硫酸塩/二酸化硫黄を含む（保存料）"},zh:{n:"亚硫酸盐 / SO₂",d:"含有亚硫酸盐/二氧化硫（防腐剂）"},ar:{n:"الكبريتيت / SO₂",d:"يحتوي على الكبريتيت (مادة حافظة)"},tr:{n:"Sülfit / SO₂",d:"Sülfit/kükürt dioksit içerir (koruyucu)"},th:{n:"ซัลไฟต์ / SO₂",d:"มีซัลไฟต์/ซัลเฟอร์ไดออกไซด์ (สารกันบูด)"},el:{n:"Θειώδη / SO₂",d:"Περιέχει θειώδη/διοξείδιο του θείου (συντηρητικό)"} },
  lupin:       { en:{n:"Lupin",d:"Contains lupin and lupin-based products"},de:{n:"Lupinen",d:"Enthält Lupinen und Lupinenprodukte"},fr:{n:"Lupin",d:"Contient du lupin et des produits à base de lupin"},es:{n:"Altramuz",d:"Contiene altramuz y productos a base de altramuz"},it:{n:"Lupini",d:"Contiene lupini e prodotti a base di lupini"},nl:{n:"Lupine",d:"Bevat lupine en lupineproducten"},pt:{n:"Tremoço",d:"Contém tremoço e produtos à base de tremoço"},pl:{n:"Łubin",d:"Zawiera łubin i produkty z łubinu"},sv:{n:"Lupin",d:"Innehåller lupin och lupinbaserade produkter"},no:{n:"Lupin",d:"Inneholder lupin og lupinbaserte produkter"},ja:{n:"ルピナス",d:"ルピナスおよびルピナス製品を含む"},zh:{n:"羽扇豆",d:"含有羽扇豆和羽扇豆制品"},ar:{n:"الترمس",d:"يحتوي على الترمس ومنتجاته"},tr:{n:"Lupin",d:"Lupin ve lupin ürünleri içerir"},th:{n:"ลูพิน",d:"มีลูพินและผลิตภัณฑ์จากลูพิน"},el:{n:"Λούπινα",d:"Περιέχει λούπινα και προϊόντα λούπινων"} },
  bloeddyr:    { en:{n:"Molluscs",d:"Contains molluscs (squid, oysters, mussels, snails etc.)"},de:{n:"Weichtiere",d:"Enthält Weichtiere (Tintenfisch, Austern, Muscheln, Schnecken)"},fr:{n:"Mollusques",d:"Contient des mollusques (calamar, huîtres, moules, escargots)"},es:{n:"Moluscos",d:"Contiene moluscos (calamar, ostras, mejillones, caracoles)"},it:{n:"Molluschi",d:"Contiene molluschi (calamari, ostriche, cozze, lumache)"},nl:{n:"Weekdieren",d:"Bevat weekdieren (inktvis, oesters, mosselen, slakken)"},pt:{n:"Moluscos",d:"Contém moluscos (lulas, ostras, mexilhões, caracóis)"},pl:{n:"Mięczaki",d:"Zawiera mięczaki (kałamarnica, ostrygi, małże, ślimaki)"},sv:{n:"Blötdjur",d:"Innehåller blötdjur (bläckfisk, ostron, musslor, sniglar)"},no:{n:"Bløtdyr",d:"Inneholder bløtdyr (blekksprut, østers, muslinger, snegler)"},ja:{n:"軟体動物",d:"軟体動物含有（イカ・カキ・ムール貝・カタツムリ等）"},zh:{n:"软体动物",d:"含有软体动物（鱿鱼、牡蛎、贻贝、蜗牛等）"},ar:{n:"الرخويات",d:"يحتوي على الرخويات (الحبار، المحار، بلح البحر)"},tr:{n:"Yumuşakçalar",d:"Yumuşakça içerir (kalamar, istiridye, midye, salyangoz)"},th:{n:"หอย / ปลาหมึก",d:"มีสัตว์จำพวกหอย (ปลาหมึก, หอยนางรม, หอยแมลงภู่)"},el:{n:"Μαλάκια",d:"Περιέχει μαλάκια (καλαμάρι, στρείδια, μύδια, σαλιγκάρια)"} },
};

export const MADPAS_INTRO = {
  da:"Jeg har følgende fødevareallergier og intoleranser. Vær venlig at sikre, at min mad ikke indeholder nogen af disse.",
  en:"I have the following food allergies and intolerances. Please ensure my meal does not contain any of these.",
  de:"Ich habe folgende Lebensmittelallergien und Unverträglichkeiten. Bitte stellen Sie sicher, dass mein Essen keines davon enthält.",
  fr:"J'ai les allergies alimentaires et intolérances suivantes. Veuillez vous assurer que mon repas n'en contient aucune.",
  es:"Tengo las siguientes alergias alimentarias e intolerancias. Por favor, asegúrese de que mi comida no contenga ninguno de estos.",
  it:"Ho le seguenti allergie alimentari e intolleranze. Si prega di assicurarsi che il mio pasto non contenga nessuno di questi.",
  nl:"Ik heb de volgende voedselallergieën en intoleranties. Zorg er alstublieft voor dat mijn maaltijd geen van deze bevat.",
  pt:"Tenho as seguintes alergias alimentares e intolerâncias. Por favor, certifique-se de que a minha refeição não contém nenhum destes.",
  pl:"Mam następujące alergie pokarmowe i nietolerancje. Proszę upewnić się, że moje jedzenie nie zawiera żadnego z tych składników.",
  sv:"Jag har följande matallergier och intoleranser. Vänligen se till att min måltid inte innehåller något av dessa.",
  no:"Jeg har følgende matallergier og intoleranser. Vennligst sørg for at mitt måltid ikke inneholder noen av disse.",
  ja:"私は以下の食物アレルギーと不耐症があります。私の食事にこれらが含まれないようにしてください。",
  zh:"我有以下食物过敏和不耐受。请确保我的餐食不含以下任何成分。",
  ar:"لدي الحساسية الغذائية والتعصبات التالية. يرجى التأكد من أن وجبتي لا تحتوي على أي من هذه العناصر.",
  tr:"Aşağıdaki gıda alerjilerim ve intoleranslarım var. Lütfen yemeğimin bunlardan hiçbirini içermediğinden emin olun.",
  th:"ฉันมีการแพ้อาหารและการแพ้ต่อไปนี้ กรุณาตรวจสอบให้แน่ใจว่าอาหารของฉันไม่มีสิ่งเหล่านี้",
  el:"Έχω τις ακόλουθες αλλεργίες και δυσανεξίες. Παρακαλώ βεβαιωθείτε ότι το γεύμα μου δεν περιέχει κανένα από αυτά.",
};
