// @ts-check
// ─── EATSAFE KONSTANTER ─────────────────────────────────────────────────────

export const SUPABASE_URL = "https://jegrpcflyguadyxialkm.supabase.co";
// Version af privatlivspolitikkens samtykketekst (gemmes sammen med samtykket, 2. okt. 2026). Ændres teksten væsentligt, hæves versionen.
export const HEALTH_CONSENT_VERSION = "2026-10-02";

export const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplZ3JwY2ZseWd1YWR5eGlhbGttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkxNjY5NjQsImV4cCI6MjA5NDc0Mjk2NH0.QErfbw2xmsdYjTZCS1WUOUwQHv6G2PKQRldyj8rdGq8";

// ─── KONSTANTER ──────────────────────────────────────────────────────────────

// ─── EATSAFE LOGO KOMPONENT ──────────────────────────────────────────────────

export const E_CATEGORIES = [
  { id:"farve",    label:"Farvestoffer",          range:"E100–E199", min:100,  max:199,  popular:["E102","E110","E122","E129","E150d","E171","E120","E127"] },
  { id:"konserv",  label:"Konserveringsmidler",   range:"E200–E299", min:200,  max:299,  popular:["E202","E211","E220","E250","E251","E252","E282","E290"] },
  { id:"antioxid", label:"Antioxidanter",         range:"E300–E399", min:300,  max:399,  popular:["E300","E306","E320","E321","E322","E330"] },
  { id:"emulg",    label:"Emulgatorer",           range:"E400–E499", min:400,  max:499,  popular:["E407","E412","E415","E440","E471","E476","E433"] },
  { id:"smags",    label:"Smagsforstærkere",      range:"E600–E699", min:600,  max:699,  popular:["E621","E627","E631","E635","E620"] },
  { id:"diverse",  label:"Diverse (E700–E949)",   range:"E700–E949", min:700,  max:949,  popular:["E901","E904","E920","E942"] },
  { id:"sode",     label:"Sødestoffer",            range:"E950–E999", min:950,  max:999,  popular:["E950","E951","E954","E955","E960","E965","E967","E968"] },
  { id:"stivelse", label:"Stivelse & overflader",  range:"E1000+",    min:1000, max:9999, popular:["E1200","E1400","E1404","E1412","E1422","E1440"] },
];

export const E_NUMBERS = {
  "E100": "Curcumin — naturligt gult farvestof fra gurkemeje.",
  "E101": "Riboflavin (B2) — gul-orange farve. Riboflavin er også vitamin B2.",
  "E102": "Tartrazin — syntetisk gul azo-farve. Kan have negativ indvirkning på børns aktivitet og koncentrationsevne (EU-krav om advarselsmærkning).",
  "E103": "Alkannin — rød-brun farve. Ikke opført som godkendt farvestof i EU.",
  "E104": "Quinolingul — syntetisk gul-grøn farve. Kan have negativ indvirkning på børns aktivitet og koncentrationsevne (EU-krav om advarselsmærkning).",
  "E105": "Fast Yellow AB — syntetisk gul farve (ikke godkendt i EU)",
  "E107": "Yellow 2G — syntetisk gul farve",
  "E110": "Solsikkegul FCF — syntetisk orange-gul azo-farve. Kan have negativ indvirkning på børns aktivitet og koncentrationsevne (EU-krav om advarselsmærkning).",
  "E111": "Orange GGN — syntetisk orange farve (ikke godkendt i EU)",
  "E120": "Cochenille/Karminsyre — rød farve fra skjoldlus",
  "E121": "Orcein — rød-lilla farve (ikke godkendt i EU)",
  "E122": "Azorubine/Karmoisin — syntetisk rød azo-farve. Kan have negativ indvirkning på børns aktivitet og koncentrationsevne (EU-krav om advarselsmærkning).",
  "E123": "Amaranth — syntetisk rød azo-farve (ikke godkendt i EU)",
  "E124": "Ponceau 4R — syntetisk rød azo-farve. Kan have negativ indvirkning på børns aktivitet og koncentrationsevne (EU-krav om advarselsmærkning).",
  "E125": "Scarlet GN — syntetisk rød farve (ikke godkendt i EU)",
  "E126": "Ponceau 6R — syntetisk rød azo-farve (ikke godkendt i EU)",
  "E127": "Erythrosin — syntetisk lyserød/rød farve",
  "E128": "Red 2G — syntetisk rød azo-farve",
  "E129": "Allura Rød AC — syntetisk rød azo-farve. Kan have negativ indvirkning på børns aktivitet og koncentrationsevne (EU-krav om advarselsmærkning).",
  "E131": "Patent Blå V — syntetisk blå farve",
  "E132": "Indigokarmin — syntetisk blå farve",
  "E133": "Brilliant Blå FCF — syntetisk blå farve",
  "E140": "Klorofyller — naturlig grøn farve fra planter",
  "E141": "Klorofylkomplekser med kobber — grøn farve",
  "E142": "Grøn S — syntetisk grøn farve",
  "E150a": "Karamelfarve, alm. — brun farve lavet ved opvarmning af sukker",
  "E150b": "Karamelfarve, sulfit — brun farve fremstillet med sulfit",
  "E150c": "Karamelfarve, ammoniak — brun farve fremstillet med ammoniak",
  "E150d": "Karamelfarve, ammoniumsulfit — brun farve i cola og øl",
  "E151": "Brilliant Sort BN — syntetisk sort azo-farve",
  "E152": "Carbon Black — sort farve (ikke godkendt i EU)",
  "E153": "Vegetabilsk kul — sort farve fra forkullet plantemateriale",
  "E154": "Brown FK — syntetisk brun azo-farve",
  "E155": "Brown HT — syntetisk brun azo-farve",
  "E160a": "Alfa-, beta-, gamma-karoten — orange farve, forstadium til A-vitamin",
  "E160b": "Annatto/Bixin/Norbixin — orange-rød farve fra annattobusk",
  "E160c": "Paprikaekstrakt/Capsanthin — rød-orange farve fra paprika",
  "E160d": "Lykopen — rød farve fra tomat",
  "E160e": "Beta-apo-8-carotenal — orange farve",
  "E160f": "Beta-apo-8-carotensyreethylester — orange farve",
  "E161a": "Flavoxanthin — gul farve (ikke godkendt i EU)",
  "E161b": "Lutein — gul farve fra blomster og æg",
  "E161c": "Kryptoxanthin — gul-orange farve (ikke godkendt i EU)",
  "E161d": "Rubixanthin — gul-orange farve (ikke godkendt i EU)",
  "E161e": "Violaxanthin — gul farve (ikke godkendt i EU)",
  "E161f": "Rhodoxanthin — rød farve (ikke godkendt i EU)",
  "E162": "Rødbetarød/Betanin — rød farve fra rødbede",
  "E163": "Anthocyaniner — rød-lilla farve fra bær og druer",
  "E170": "Calciumkarbonat — hvid farve/fyldsoftf, også kalk",
  "E171": "Titandioxid — hvid farve, bruges i slik og tandpasta",
  "E172": "Jernoxider og jernhydroxider — gul, rød og sort farve",
  "E173": "Aluminium — sølvfarve til konfekture",
  "E174": "Sølv — sølvfarve til konfekture",
  "E175": "Guld — guldfarve til konfekture",
  "E180": "Litholrubine BK — rød farve til osteskorper",
  "E200": "Sorbinsyre — konserverer mod skimmelsvamp i ost og bagværk",
  "E201": "Natriumsorbat — konservering mod skimmel",
  "E202": "Kaliumsorbat — meget udbredt konservering mod skimmel og gær",
  "E203": "Calciumsorbat — konservering mod skimmel",
  "E210": "Benzoesyre — konservering i saft, marmelade og drikkevarer",
  "E211": "Natriumbenzoat — udbredt konservering i sodavand og saucer",
  "E212": "Kaliumbenzoat — konservering mod gær og bakterier",
  "E213": "Calciumbenzoat — konservering mod mikrober",
  "E214": "Ethylparahydroxybenzoat — konservering (parabener)",
  "E215": "Natriumethylparahydroxybenzoat — konservering (parabener)",
  "E218": "Methylparahydroxybenzoat — konservering (parabener)",
  "E219": "Natriummethylparahydroxybenzoat — konservering (parabener)",
  "E220": "Svovldioxid — konservering i vin, frugt og tørrede frugter",
  "E221": "Natriumsulfit — konservering, forhindrer brunfarvning",
  "E222": "Natriumhydrogensulfit — konservering i vin og frugtprodukter",
  "E223": "Natriumdisulfit — konservering og blegemiddel",
  "E224": "Kaliumdisulfit — konservering i vin",
  "E225": "Kaliumsulfit — konservering",
  "E226": "Calciumsulfit — konservering og fasthedsmiddel",
  "E227": "Calciumhydrogensulfit — konservering i øl",
  "E228": "Kaliumhydrogensulfit — konservering i vin",
  "E230": "Biphenyl/Diphenyl — konservering på citrusskaller",
  "E231": "Orthophenylphenol — konservering på citrusskaller",
  "E232": "Natriumorthophenylphenol — konservering på citrusskaller",
  "E234": "Nisin — naturlig antibiotisk konservering i ost",
  "E235": "Natamycin — naturlig antibiotisk konservering mod skimmel",
  "E239": "Hexamethylentetramin — konservering i syltet fisk",
  "E242": "Dimethyldicarbonat — konservering i drikkevarer",
  "E249": "Kaliumnitrit — konservering og rødfarvning af kødprodukter",
  "E250": "Natriumnitrit — konservering i pålæg og bacon, kan danne nitrosaminer",
  "E251": "Natriumnitrat — konservering i kødprodukter og ost",
  "E252": "Kaliumnitrat — konservering i kødprodukter og ost",
  "E260": "Eddikesyre — konservering og smagsgiver, naturlig i eddike",
  "E261": "Kaliumacetat — konservering og surheds regulering",
  "E262": "Natriumacetat — konservering og smagsgiver",
  "E263": "Calciumacetat — konservering og fasthedsmiddel",
  "E270": "Mælkesyre — konservering, naturlig i fermenterede produkter",
  "E280": "Propionsyre — konservering mod skimmel i brød",
  "E281": "Natriumpropionat — konservering i brød og bagværk",
  "E282": "Calciumpropionat — konservering i brød og bagværk",
  "E283": "Kaliumpropionat — konservering i brød",
  "E284": "Borsyre — konservering i kaviar",
  "E285": "Natriumtetraborat — konservering i kaviar",
  "E290": "Kuldioxid — kulsyre i drikkevarer og emballage",
  "E296": "Æblesyre — konservering og smagsgiver",
  "E297": "Fumarsyre — konservering og syrningsagent",
  "E300": "Ascorbinsyre (C-vitamin) — antioxidant, forhindrer brunfarvning",
  "E301": "Natriumascorbat — antioxidant, C-vitaminsalt",
  "E302": "Calciumascorbat — antioxidant, C-vitaminsalt",
  "E304": "Fedtsyreestere af ascorbinsyre — fedtopløselig antioxidant",
  "E306": "Tokoferoler (E-vitamin) — naturlig antioxidant fra vegetabilske olier",
  "E307": "Alfa-tokoferol — syntetisk E-vitamin, antioxidant",
  "E308": "Gamma-tokoferol — syntetisk E-vitamin",
  "E309": "Delta-tokoferol — syntetisk E-vitamin",
  "E310": "Propylgallat — antioxidant i fedtstoffer og olier",
  "E311": "Octylgallat — antioxidant i fedtstoffer",
  "E312": "Dodecylgallat — antioxidant i fedtstoffer",
  "E315": "Erythorbinsyre — antioxidant i kødprodukter",
  "E316": "Natriumerythorbat — antioxidant i kødprodukter",
  "E319": "TBHQ — antioxidant i vegetabilske olier og chips",
  "E320": "BHA (Butylhydroxyanisol) — antioxidant i fedtstoffer og fedtholdige fødevarer",
  "E321": "BHT (Butylhydroxytoluen) — antioxidant i fedtstoffer og fedtholdige fødevarer",
  "E322": "Lecitiner — emulgator og antioxidant, ofte fra soja eller solsikke",
  "E325": "Natriumlactat — antioxidantsynergist og fugtighedsbeholder",
  "E326": "Kaliumlactat — antioxidantsynergist",
  "E327": "Calciumlactat — antioxidantsynergist og fasthedsmiddel",
  "E328": "Ammoniumlactat — antioxidantsynergist",
  "E329": "Magnesiumlactat — antioxidantsynergist",
  "E330": "Citronsyre — antioxidant og syrningsagent, naturlig i citrusfrugter",
  "E331": "Natriumcitrat — antioxidantsynergist og emulgator",
  "E332": "Kaliumcitrat — antioxidantsynergist og regulering af surhedsgrad",
  "E333": "Calciumcitrat — antioxidantsynergist og fasthedsmiddel",
  "E334": "Vinsyre (L-tartrat) — antioxidant og syrningsagent i vin",
  "E335": "Natriumtartrat — antioxidantsynergist",
  "E336": "Kaliumtartrat — antioxidantsynergist og bagepulver",
  "E337": "Natriumkaliumtartrat — antioxidantsynergist",
  "E338": "Fosforsyre — antioxidantsynergist og surhedsregulering i cola",
  "E339": "Natriumfosfater — antioxidantsynergist og emulgator",
  "E340": "Kaliumfosfater — antioxidantsynergist og hævemiddel",
  "E341": "Calciumfosfater — antioxidantsynergist og hævemiddel",
  "E343": "Magnesiumfosfater — antioxidantsynergist",
  "E350": "Natriummalat — antioxidantsynergist",
  "E351": "Kaliummalat — antioxidantsynergist",
  "E352": "Calciummalat — antioxidantsynergist",
  "E353": "Metavinsyre — antioxidantsynergist i vin",
  "E354": "Calciumtartrat — antioxidantsynergist",
  "E355": "Adipinsyre — antioxidantsynergist og syrningsagent",
  "E356": "Natriumadipinat — antioxidantsynergist",
  "E357": "Kaliumadipinat — antioxidantsynergist",
  "E363": "Ravsyre — antioxidantsynergist",
  "E380": "Triammoniumcitrat — antioxidantsynergist",
  "E385": "Calciumdinatrium-EDTA — antioxidantsynergist og sekvestringsmiddel",
  "E392": "Ekstrakter af rosmarin — naturlig antioxidant",
  "E393": "Ekstrakter af rig-ekstrakt (Quillaja) — naturlig antioxidant",
  "E400": "Alginsyre — fortykningsmiddel fra brunalger",
  "E401": "Natriumalginat — fortykningsmiddel fra brunalger",
  "E402": "Kaliumalginat — fortykningsmiddel fra brunalger",
  "E403": "Ammoniumalginat — fortykningsmiddel fra brunalger",
  "E404": "Calciumalginat — fortykningsmiddel, gelerende middel",
  "E405": "Propylenglycolalginat — emulgator og stabilisator",
  "E406": "Agar — gelerende middel fra rødalger, vegansk gelatine",
  "E407": "Carrageenan — fortykningsmiddel fra rødalger, bruges i mælkeprodukter",
  "E407a": "Bearbejdet Eucheuma-alger — fortykningsmiddel",
  "E408": "Karayagummi — fortykningsmiddel",
  "E410": "Johannesbrødkernmel — fortykningsmiddel fra johannesbrødtræ",
  "E411": "Havrekernmel — fortykningsmiddel",
  "E412": "Guargummi — fortykningsmiddel fra guarbønne",
  "E413": "Tragant — fortykningsmiddel fra tornebusk",
  "E414": "Arabiagummi — fortykningsmiddel, naturlig harpiks",
  "E415": "Xanthangummi — fortykningsmiddel fra fermentering",
  "E416": "Karayagummi — fortykningsmiddel fra karayabusk",
  "E417": "Tarakernmel — fortykningsmiddel fra tarafrø",
  "E418": "Gellangummi — fortykningsmiddel fra fermentering",
  "E419": "Ghatti gummi — fortykningsmiddel",
  "E420": "Sorbitol/Sorbitolsirup — sødemiddel og fugtighedsbeholder",
  "E421": "Mannitol — sødemiddel og anti-klumpningsmiddel",
  "E422": "Glycerol — fugtighedsbeholder og opløsningsmiddel",
  "E423": "Octylgallat — antioxidant",
  "E425": "Konjac — fortykningsmiddel og gelerende middel",
  "E426": "Sojabønne-hemicellulose — emulgator",
  "E427": "Cassie gummi — fortykningsmiddel",
  "E430": "Polyoxyethylen(8)stearat — emulgator",
  "E431": "Polyoxyethylen(40)stearat — emulgator",
  "E432": "Polyoxyethylensobitanmonolaurat (Polysorbat 20) — emulgator",
  "E433": "Polyoxyethylensorbitanmonooleat (Polysorbat 80) — emulgator",
  "E434": "Polyoxyethylensorbitanmonopalmitat (Polysorbat 40) — emulgator",
  "E435": "Polyoxyethylensorbitanmonostearat (Polysorbat 60) — emulgator",
  "E436": "Polyoxyethylensorbitantristearat (Polysorbat 65) — emulgator",
  "E440": "Pektiner — gelerende middel fra citrusskaller og æbler",
  "E442": "Ammoniumfosfatider — emulgator i chokolade",
  "E444": "Saccharoseacetoisobutyrat — emulgator i drikkevarer",
  "E445": "Glycerolestere af træharpiks — emulgator i drikkevarer",
  "E450": "Diphosphater — hæve- og bindemiddel i bagværk",
  "E451": "Triphosphater — bindemiddel i kødprodukter",
  "E452": "Polyphosphater — bindemiddel, vandholdenhed i kød",
  "E459": "Beta-cyclodextrin — indkapslingsmiddel",
  "E460": "Cellulose — fyldsotf og anti-klumpningsmiddel",
  "E461": "Methylcellulose — fortykningsmiddel og emulgator",
  "E462": "Ethylcellulose — bindemiddel",
  "E463": "Hydroxypropylcellulose — fortykningsmiddel",
  "E464": "Hydroxypropylmethylcellulose — fortykningsmiddel og emulgator",
  "E465": "Ethylmethylcellulose — fortykningsmiddel",
  "E466": "Carboxymethylcellulose — fortykningsmiddel og stabilisator",
  "E468": "Crosslinket natriumcarboxymethylcellulose — stabilisator",
  "E469": "Enzymatisk hydrolyseret carboxymethylcellulose — stabilisator",
  "E470a": "Natriumsalte af fedtsyrer — emulgator",
  "E470b": "Magnesiumsalte af fedtsyrer — emulgator og anti-klumpningsmiddel",
  "E471": "Mono- og diglycerider af fedtsyrer — emulgator i brød og margarine",
  "E472a": "Eddikesyreestere af mono- og diglycerider — emulgator",
  "E472b": "Mælkesyreestere af mono- og diglycerider — emulgator",
  "E472c": "Citronsyreestere af mono- og diglycerider — emulgator",
  "E472d": "Vinsyreestere af mono- og diglycerider — emulgator",
  "E472e": "Diacetyltartrat- og eddikesyreestere af mono- og diglycerider — emulgator",
  "E472f": "Blandede eddike- og vinsyreestere af mono- og diglycerider — emulgator",
  "E473": "Saccharosefedtsyreestere — emulgator",
  "E474": "Saccharoglycerider — emulgator",
  "E475": "Polyglycerolestere af fedtsyrer — emulgator",
  "E476": "Polyglycerolpolyricinoleat — emulgator i chokolade",
  "E477": "Propylenglycolestere af fedtsyrer — emulgator",
  "E479b": "Varmebehandlet sojaolieinteraktion med mono- og diglycerider — emulgator",
  "E481": "Natriumstearoyl-2-lactylat — emulgator i brød",
  "E482": "Calciumstearoyl-2-lactylat — emulgator i brød",
  "E483": "Stearoyltartrat — emulgator",
  "E484": "Stearylcitrat — emulgator",
  "E491": "Sorbitanmonostearat — emulgator",
  "E492": "Sorbitantristearat — emulgator",
  "E493": "Sorbitanmonolauarat — emulgator",
  "E494": "Sorbitanmonooleat — emulgator",
  "E495": "Sorbitanmonopalmitat — emulgator",
  "E620": "L-Glutaminsyre — naturlig smagsforstærker, findes i tomat og ost",
  "E621": "Mononatriumglutamat (MSG) — syntetisk smagsforstærker, omdiskuteret",
  "E622": "Monokaliumglutamat — smagsforstærker",
  "E623": "Calciumdiglutamat — smagsforstærker",
  "E624": "Monoammoniumglutamat — smagsforstærker",
  "E625": "Magnesiumdiglutamat — smagsforstærker",
  "E626": "Guanylsyre — smagsforstærker",
  "E627": "Dinatriumguanylat — smagsforstærker, forstærker MSG-effekt",
  "E628": "Dikaliumguanylat — smagsforstærker",
  "E629": "Calciumguanylat — smagsforstærker",
  "E630": "Inosinsyre — smagsforstærker",
  "E631": "Dinatriuminosinat — smagsforstærker, forstærker MSG-effekt",
  "E632": "Dikaliuminosinat — smagsforstærker",
  "E633": "Calciuminosinat — smagsforstærker",
  "E634": "Calcium-5-ribonukleotider — smagsforstærker",
  "E635": "Dinatrium-5-ribonukleotider — smagsforstærker, kombination af E627+E631",
  "E636": "Maltol — smagsforstærker og aromasoftf",
  "E637": "Ethylmaltol — smagsforstærker, forstærker sød smag",
  "E640": "Glycin og natriumsalt — smagsforstærker",
  "E650": "Zinkacetat — smagsforstærker i tyggegummi",
  "E900": "Dimethylpolysiloxan — anti-skummiddel i fedtstoffer og juice",
  "E901": "Bivoks — glaseringsmiddel på frugt og slik",
  "E902": "Candelillavoks — glaseringsmiddel, vegansk alternativ til bivoks",
  "E903": "Carnaubavoks — glaseringsmiddel fra palmeblade",
  "E904": "Shellac — glaseringsmiddel fra skjoldlus",
  "E905": "Mikrokrystallinsk voks — glaseringsmiddel",
  "E907": "Raffineret mikrokrystallinsk voks — glaseringsmiddel",
  "E912": "Montan-syreestere — glaseringsmiddel",
  "E914": "Oxideret polyethylenvoks — glaseringsmiddel",
  "E920": "L-Cystein — mel-forbedrer i bagværk",
  "E927b": "Carbamid (urinstof) — mel-forbedrer",
  "E938": "Argon — emballeringsgas",
  "E939": "Helium — emballeringsgas",
  "E941": "Kvælstof — emballeringsgas, forlænger holdbarheden",
  "E942": "Lattergas — drivgas i flødeskum",
  "E943a": "Butan — drivgas",
  "E943b": "Isobutan — drivgas",
  "E944": "Propan — drivgas",
  "E948": "Oxygen — emballeringsgas",
  "E949": "Hydrogen — emballeringsgas",
  "E950": "Acesulfam K — sødemiddel, ca. 200x sødere end sukker",
  "E951": "Aspartam — sødemiddel, 200x sødere end sukker, indeholder phenylalanin",
  "E952": "Cyclaminsyre/Cyclamat — sødemiddel; reglerne for brug varierer mellem lande",
  "E953": "Isomalt — sødemiddel og fyldsoftf fra sukker",
  "E954": "Saccharin og salte — ældste kunstige sødemiddel, 300-500x sødere",
  "E955": "Sucralose — sødemiddel, 600x sødere end sukker",
  "E957": "Thaumatin — naturlig proteinsødemiddel fra afrikansk frugt",
  "E958": "Glycyrrhizin — naturlig sødemiddel fra lakrids",
  "E959": "Neohesperidindihydrochalcon — sødemiddel fra citrus",
  "E960": "Steviolglykosider (Stevia) — naturlig sødemiddel fra steviaplante",
  "E961": "Neotam — sødemiddel, 7000-13000x sødere end sukker",
  "E962": "Aspartam-acesulfamsalt — sødemiddel",
  "E965": "Maltitol/Maltitolsirup — sødemiddel og fugtighedsbeholder",
  "E966": "Lactitol — sødemiddel, afledt af laktose",
  "E967": "Xylitol — sødemiddel fra birkebark, godt for tænder",
  "E968": "Erythritol — sødemiddel, naturligt i frugt og fermenterede fødevarer",
  "E969": "Advantam — sødemiddel, 20000x sødere end sukker",
  "E999": "Quillajaekstrakt — skumdannende middel i drikkevarer",
  "E161g": "Canthaxanthin — orange farve, bruges i lakseopdræt",
};

// "type" bruges til at dele allergener op i to tydeligt adskilte sektioner
// i onboarding trin 2 (25. sept. 2026, brugerfeedback: "Hvedeallergi,
// mælkeallergi og laktoseintolerance er ikke det samme") — "allergi" for
// klassiske IgE-medierede fødevareallergier, "intolerance" for laktose-
// intolerance, sulfit-følsomhed og gluten (cøliaki/glutenfølsomhed, som
// ikke er det samme som hvedeallergi — deraf også "note"-feltet på gluten).
export const ALLERGENS = [
  // Note udvidet (28. sept. 2026, Profil-oprydning, krav 6) til også at
  // forklare forholdet til kostpræferencen "Glutenfri" — de to er koblet
  // (se useGlutenFreeSync i AllergenPicker.jsx: vælges Gluten her, tilføjes
  // Glutenfri automatisk under Kostpræferencer), så brugeren ikke behøver
  // vælge begge selv for at opnå samme filtrering.
  // Glutenfølsomhed (ikke-cøliakisk) er et eget valg: ikke det samme som hvedeallergi og ikke cøliaki (som er et eget valg, `coeliaki`).
  // `pickerLabel` bruges i valg-skærmene; `label` bruges i resultater ("Indeholder gluten"). Id'et er uændret.
  { id:"gluten",        label:"Gluten",           pickerLabel:"Glutenfølsomhed", emoji:"🥖", type:"intolerance", note:"Glutenfølsomhed og glutenfri kost er koblet sammen. Vælger du glutenfølsomhed, kan glutenfri kost anvendes automatisk, så du ikke skal vælge begge. Det er ikke det samme som hvedeallergi eller cøliaki." },
  { id:"hvede",         label:"Hvede",             emoji:"🌾", type:"allergi", note:"Hvedeallergi gælder hvede. Det er ikke det samme som glutenfølsomhed, og de vælges hver for sig." },
  // Cøliaki (2. okt. 2026, Bjørn): et eget, eksplicit valg, aldrig udledt af Gluten eller Hvede. `profileOnly`: det er en tilstand hos brugeren,
  // ikke en egenskab ved et produkt, så det findes ikke som produktflag (se PRODUCT_ALLERGENS). Matches mod produktets gluten-/hvedeflag
  // (`effectiveAllergenFlag` i helpers.js). Cøliaki-vejledningen om spor vises kun for dette id (`AllergenSensitivity`).
  { id:"coeliaki",      label:"Cøliaki",           emoji:"🌾", type:"intolerance", profileOnly:true, note:"Cøliaki er en autoimmun sygdom udløst af gluten. Det er ikke det samme som hvedeallergi eller glutenfølsomhed." },
  { id:"maelkeallergi", label:"Mælk",              emoji:"🥛", type:"allergi" },
  // emoji er kun et fallback-tegn for evt. rene tekst-kontekster uden JSX
  // (se AllergenGlyph i SharedComponents.jsx, som al UI reelt bruger) — det
  // oprindelige "🍬" (slik) havde ingen sammenhæng med laktose overhovedet.
  // Laktoseintolerance er ikke mælkeallergi og har ingen "kan indeholde spor af"-logik (traceOk:false): sporvalg vises ikke for den.
  { id:"laktose",       label:"Laktose",           emoji:"💧", type:"intolerance", traceOk:false },
  { id:"aeg",           label:"Æg",               emoji:"🥚", type:"allergi" },
  { id:"noedder",       label:"Nødder",            emoji:"🌰", type:"allergi" },
  { id:"jordnoedder",   label:"Jordnødder",        emoji:"🥜", type:"allergi" },
  { id:"soja",          label:"Soja",              emoji:"🫛", type:"allergi" },
  { id:"fisk",          label:"Fisk",              emoji:"🐟", type:"allergi" },
  { id:"skaldyr",       label:"Skaldyr",           emoji:"🦐", type:"allergi" },
  { id:"selleri",       label:"Selleri",           emoji:"🥬", type:"allergi" },
  { id:"sennep",        label:"Sennep",            emoji:"🟡", type:"allergi" },
  { id:"sesam",         label:"Sesam",             emoji:"🌿", type:"allergi" },
  // Sulfitter: mærkningspligtigt EU-allergen (svovldioxid/sulfitter) over 10 mg/kg eller 10 mg/l samlet SO₂. Klassificeres fortsat som
  // "intolerance" i resultatlogikken (sikker filtrering), men har sin egen mærkningsgrænse som data (labelThresholdMgPerKg).
  { id:"svovl",         label:"Sulfitter",         emoji:"🍷", type:"intolerance", labelThresholdMgPerKg:10, note:"Sulfitter er et mærkningspligtigt allergen i EU, når der er over 10 mg/kg eller 10 mg/l (målt som samlet SO₂). Under grænsen står de ikke nødvendigvis på emballagen." },
  { id:"lupin",         label:"Lupin",             emoji:"🌸", type:"allergi" },
  { id:"bloeddyr",      label:"Bløddyr",           emoji:"🦑", type:"allergi" },
];

// Allergener, der findes som produktflag (allergen_flags). Cøliaki er kun et profilvalg og hører ikke hjemme i produktredigering, indberetning mv.
export const PRODUCT_ALLERGENS = ALLERGENS.filter(a => !a.profileOnly);

export const DEMO_CODES = [
  { code:"3017620422003", label:"Nutella" },
  { code:"5449000054227", label:"Coca-Cola" },
  { code:"7394376616566", label:"Oatly" },
  { code:"5701029015306", label:"Lurpak" },
];

export const SCREENS = {
  WELCOME:"welcome", LOGIN:"login", ONBOARD:"onboard",
  // VERIFYEMAIL: "Bekræft din e-mail" efter oprettelse. BOOT: tom skærm mens
  // onboarding-status hentes ved appstart (se useAuth.js, ONBOARDED_KEY).
  VERIFYEMAIL:"verifyemail", BOOT:"boot",
  // RESETPASSWORD: "Vælg ny adgangskode" efter linket i "Glemt adgangskode"-mailen.
  RESETPASSWORD:"resetpassword",
  HOME:"home",
  LIST:"list", PROFILE:"profile", FAMILY:"family",
  RESULT:"result", HISTORY:"history",
  NOTFOUND:"notfound", SUBMITTED:"submitted",
  ADMIN:"admin", FAVORITES:"favorites",
  MADPAS:"madpas", RECIPES:"recipes", EDITPROFILE:"editprofile", EDITPREFERENCES:"editpreferences", SUGGEST_EDIT:"suggest_edit",
  KNOWLEDGE:"knowledge",
  SETTINGS:"settings",
  // Beskeder (30. sept. 2026): liste over egne notifikationer + den fulde besked,
  // som push åbner via ?notification={id}.
  NOTIFICATIONS:"notifications", NOTIFICATION:"notification", TICKET:"ticket",
  // Brugsvilkår/Privatlivspolitik (29. sept. 2026, "Opdater siderne...med
  // tydelig navigation tilbage") — almindelige undersider, ikke modaler, se
  // TermsScreen.jsx/PrivacyScreen.jsx + App.jsx's openLegal/legalReturnScreen.
  TERMS:"terms", PRIVACY:"privacy",
};

export const PAGE_IDS = {
  welcome:"SCR-01", login:"SCR-02", onboard:"SCR-03",
  home:"SCR-04", search:"SCR-06",
  list:"SCR-07", profile:"SCR-08", family:"SCR-09",
  result:"SCR-10", history:"SCR-11", notfound:"SCR-12",
  submitted:"SCR-13", admin:"SCR-14", favorites:"SCR-15",
  madpas:"SCR-16", recipes:"SCR-17", editprofile:"SCR-18",
  knowledge:"SCR-19", settings:"SCR-21",
  terms:"SCR-22", privacy:"SCR-23",
  notifications:"SCR-24", notification:"SCR-25", ticket:"SCR-26",
};

export const DUMMY_PRODUCT = {
  code: "3017620422003",
  ean: "3017620422003",
  name: "Nutella",
  brand: "Ferrero",
  image_url: "https://images.openfoodfacts.org/images/products/301/762/042/2003/front_en.820.400.jpg",
  category: "Chokolade",
  status: "danger",
  headline: "Indeholder allergen",
  summary: "Produktet indeholder Laktose, Nødder.",
  source: "open_food_facts",
  verified_status: "unverified",
  hasUnknown: false,
  matchedDanger: ["laktose", "noedder"],
  matchedWarning: ["soja"],
  familyImpact: [],
  allergen_flags: {
    gluten: "no", laktose: "yes", aeg: "no",
    noedder: "yes", jordnoedder: "no", soja: "traces",
    fisk: "no", skaldyr: "no", selleri: "no",
    sennep: "no", sesam: "no", svovl: "no",
    lupin: "no", bloeddyr: "no",
  },
  ingredients: "Sucre, huile de palme, NOISETTES 13%, cacao maigre 7,4%, LAIT écrémé en poudre 6,6%, LACTOSERUM en poudre, émulsifiants: lécithines (SOJA), vanilline.",
  tags: ["vegetarian"],
  nutrition: {
    energy_kcal: 539,
    fat: 30.9,
    saturated_fat: 10.6,
    carbohydrates: 57.5,
    sugars: 56.3,
    fiber: 3.4,
    protein: 6.3,
    salt: 0.11,
  },
  flags: [
    { type:"bad", text:"Indeholder Laktose" },
    { type:"bad", text:"Indeholder Nødder" },
    { type:"maybe", text:"Kan indeholde spor af Soja" },
  ],
  timestamp: Date.now(),
};

// Mock produkter med fuld data til test

export const MOCK_PRODUCTS = [
  {
    id: "mock-1", ean: "5701029015306", name: "Lurpak Smør", brand: "Lurpak",
    category: "Mejeri", verified_status: "verified", source: "verified",
    image_url: null,
    allergen_flags: { gluten:"no", laktose:"yes", aeg:"no", noedder:"no", jordnoedder:"no", soja:"no", fisk:"no", skaldyr:"no", selleri:"no", sennep:"no", sesam:"no", svovl:"no", lupin:"no", bloeddyr:"no" },
    ingredients: "Pasteuriseret fløde (mælk), salt.",
    nutrition: { energy_kcal:717, fat:80, saturated_fat:52, carbohydrates:0.6, sugars:0.6, fiber:0, protein:0.6, salt:1.5 },
    tags: ["vegetarian"],
  },
  {
    id: "mock-2", ean: "5000112546415", name: "Coca-Cola Original", brand: "Coca-Cola",
    category: "Drikkevarer", verified_status: "verified", source: "verified",
    image_url: null,
    allergen_flags: { gluten:"no", laktose:"no", aeg:"no", noedder:"no", jordnoedder:"no", soja:"no", fisk:"no", skaldyr:"no", selleri:"no", sennep:"no", sesam:"no", svovl:"no", lupin:"no", bloeddyr:"no" },
    ingredients: "Vand, sukker, kuldioxid, farve (E150d), surheds regulerende middel (E338), naturlige aromaer inkl. koffein.",
    nutrition: { energy_kcal:42, fat:0, saturated_fat:0, carbohydrates:10.6, sugars:10.6, fiber:0, protein:0, salt:0 },
    tags: ["vegan", "vegetarian"],
  },
  {
    id: "mock-3", ean: "7394376616566", name: "Oatly Havredrik", brand: "Oatly",
    category: "Plantebaseret", verified_status: "verified", source: "verified",
    image_url: null,
    allergen_flags: { gluten:"traces", laktose:"no", aeg:"no", noedder:"no", jordnoedder:"no", soja:"no", fisk:"no", skaldyr:"no", selleri:"no", sennep:"no", sesam:"no", svovl:"no", lupin:"no", bloeddyr:"no" },
    ingredients: "Vand, havre 10%, rapsolie, calcium, vitaminer (D2, riboflavin, B12), salt.",
    nutrition: { energy_kcal:46, fat:1.5, saturated_fat:0.2, carbohydrates:6.7, sugars:4, fiber:0.8, protein:1, salt:0.07 },
    tags: ["vegan", "vegetarian"],
  },
];

// Kostpræferencer (diæter) er sat på pause (2. okt. 2026, Jans beslutning): de vises ikke i appen og indgår
// ikke i vurderinger, Madpas eller indstillinger, men al kode, alle data og al logik er bevaret. Sæt til true
// for at tage funktionen i brug igen (se "Kostpræferencer sat på pause" i CLAUDE.md).
export const DIETS_ENABLED = false;

export const DIETS = [
  { id:"vegan",       label:"Vegansk",       desc:"Ingen animalske produkter" },
  { id:"vegetarian",  label:"Vegetarisk",    desc:"Ingen kød eller fisk" },
  { id:"pescetarian", label:"Pescetarisk",   desc:"Ingen kød, men fisk ok" },
  { id:"gluten-free", label:"Glutenfri",     desc:"Ingen gluten" },
  { id:"keto",        label:"Keto",          desc:"Lavt kulhydratindhold" },
];

export const AVATAR_COLORS = ["#52b788","#74c69d","#40916c","#b7e4c7","#2d6a4f","#95d5b2","#f4a261","#e76f51"];

// ─── HJÆLPEFUNKTIONER ────────────────────────────────────────────────────────

export const uid = () => Math.random().toString(36).slice(2,9);

// Pæn ingrediensliste — fremhæver allergener med STORE BOGSTAVER

export const MADPAS_LANGUAGES = [
  { code:"da", flag:"🇩🇰", name:"Dansk",      bcp:"da-DK" },
  { code:"en", flag:"🇬🇧", name:"English",    bcp:"en-GB" },
  { code:"de", flag:"🇩🇪", name:"Deutsch",    bcp:"de-DE" },
  { code:"fr", flag:"🇫🇷", name:"Français",   bcp:"fr-FR" },
  { code:"es", flag:"🇪🇸", name:"Español",    bcp:"es-ES" },
  { code:"it", flag:"🇮🇹", name:"Italiano",   bcp:"it-IT" },
  { code:"nl", flag:"🇳🇱", name:"Nederlands", bcp:"nl-NL" },
  { code:"pt", flag:"🇵🇹", name:"Português",  bcp:"pt-PT" },
  { code:"pl", flag:"🇵🇱", name:"Polski",     bcp:"pl-PL" },
  { code:"sv", flag:"🇸🇪", name:"Svenska",    bcp:"sv-SE" },
  { code:"no", flag:"🇳🇴", name:"Norsk",      bcp:"nb-NO" },
  { code:"ja", flag:"🇯🇵", name:"日本語",      bcp:"ja-JP" },
  { code:"zh", flag:"🇨🇳", name:"中文",        bcp:"zh-CN" },
  { code:"ar", flag:"🇸🇦", name:"العربية",    bcp:"ar-SA", rtl:true },
  { code:"tr", flag:"🇹🇷", name:"Türkçe",     bcp:"tr-TR" },
  { code:"th", flag:"🇹🇭", name:"ภาษาไทย",    bcp:"th-TH" },
  { code:"el", flag:"🇬🇷", name:"Ελληνικά",   bcp:"el-GR" },
];
