// @ts-nocheck
// ─────────────────────────────────────────────────────────────────────────────
// styleUtils.js
// Delte style-objekter for de mest gentagne inline style={{...}}-mønstre på
// tværs af skærmene. Hvert felt her matcher et objekt der optrådte identisk
// mindst 4 steder i kodebasen — udtrukket for at undgå at samme objekt-
// literal allokeres på ny ved hvert render, og for at gøre disse gentagne
// stilarter til ét sted at rette i stedet for dusinvis.
//
// Rent mekanisk oprydning: hvert UI.xxx herunder er byte-for-byte identisk
// med de inline style={{...}} den erstatter — ingen visuel eller funktionel
// ændring tilsigtet.
// ─────────────────────────────────────────────────────────────────────────────

export const UI = {
  flex1:        { flex:1 },
  flexMin:      { flex:1, minWidth:0 },
  shrink0:      { flexShrink:0 },
  hr:           { flex:1, height:1, background:"var(--border)" },

  mb4:  { marginBottom:4 },
  mb6:  { marginBottom:6 },
  mb8:  { marginBottom:8 },
  mb10: { marginBottom:10 },
  mb12: { marginBottom:12 },
  mb14: { marginBottom:14 },
  mb16: { marginBottom:16 },
  mb20: { marginBottom:20 },
  mt8:  { marginTop:8 },
  mt12: { marginTop:12 },
  pb120: { paddingBottom:120 },

  fs16: { fontSize:16 },
  fs18: { fontSize:18 },
  fs20: { fontSize:20 },
  fs20Shrink0: { fontSize:20, flexShrink:0 },
  emoji48mb12: { fontSize:48, marginBottom:12 },

  red:   { color:"var(--red)" },
  muted: { color:"var(--muted)" },
  redBadge9: { fontSize:9, fontWeight:800, color:"var(--red)" },

  muted10:      { fontSize:10, color:"var(--muted)" },
  muted11:      { fontSize:11, color:"var(--muted)" },
  muted11mt1:   { fontSize:11, color:"var(--muted)", marginTop:1 },
  muted11mt2:   { fontSize:11, color:"var(--muted)", marginTop:2 },
  muted12mt2:   { fontSize:12, color:"var(--muted)", marginTop:2 },
  muted13:      { fontSize:13, color:"var(--muted)" },
  muted2_12lh:  { fontSize:12, color:"var(--muted2)", lineHeight:1.5 },

  boldInk12:    { fontSize:12, fontWeight:700, color:"var(--ink)" },
  boldInk13:    { fontSize:13, fontWeight:800, color:"var(--ink)" },
  boldInk13mb2: { fontSize:13, fontWeight:700, color:"var(--ink)", marginBottom:2 },
  boldInk14:    { fontSize:14, fontWeight:700, color:"var(--ink)" },

  sectionLbl6:     { fontSize:11, fontWeight:700, color:"var(--muted)", textTransform:"uppercase", letterSpacing:"1px", marginBottom:6 },
  sectionLbl8:     { fontSize:11, fontWeight:700, color:"var(--muted)", textTransform:"uppercase", letterSpacing:"1px", marginBottom:8 },
  sectionLbl4Ink:  { fontSize:10, fontWeight:700, color:"var(--muted)", textTransform:"uppercase", letterSpacing:".5px", marginBottom:4 },
  sectionLblInk3:  { fontSize:11, fontWeight:700, color:"var(--ink3)", textTransform:"uppercase", letterSpacing:"1.2px", marginBottom:8 },

  colGap8:      { display:"flex", flexDirection:"column", gap:8 },
  rowGap8:      { display:"flex", gap:8 },
  wrapGap4:     { display:"flex", flexWrap:"wrap", gap:4 },
  wrapGap5:     { display:"flex", flexWrap:"wrap", gap:5 },
  wrapGap7:     { display:"flex", flexWrap:"wrap", gap:7 },
  rowBetweenMb10: { display:"flex", alignItems:"center", justifyContent:"space-between", marginBottom:10 },
  rowBetweenMb16: { display:"flex", alignItems:"center", justifyContent:"space-between", marginBottom:16 },
  avatarRow:    { display:"flex", alignItems:"center", gap:12, padding:"16px 0 14px" },
  grid2gap6:    { display:"grid", gridTemplateColumns:"1fr 1fr", gap:6 },
  grid2gap8:    { display:"grid", gridTemplateColumns:"1fr 1fr", gap:8 },

  card:    { background:"var(--surface)", border:"1px solid var(--border)", borderRadius:14, padding:"14px 16px", marginBottom:12, boxShadow:"var(--sh)" },
  iconBtn: { background:"none", border:"none", cursor:"pointer", padding:4 },

  // ── Anden runde: mønstre der optrådte 2-3 gange (se dedupe-styles-2.mjs) ──
  udflex_aicenter_g12_mb16: { display:"flex", alignItems:"center", gap:12, marginBottom:16 },
  ubgsurface2_bdnone_br50_w32_h32_curpointer_fs18_cmuted: { background:"var(--surface2)", border:"none", borderRadius:"50%", width:32, height:32, cursor:"pointer", fontSize:18, color:"var(--muted)" },
  ubgsurface_br8_p8px10px_mt6: { background:"var(--surface)", borderRadius:8, padding:"8px 10px", marginTop:6 },
  ufs9_cmuted_fw700_ttuppercas_ls4px_mb4: { fontSize:9, color:"var(--muted)", fontWeight:700, textTransform:"uppercase", letterSpacing:".4px", marginBottom:4 },
  ufs11_cink_fw600: { fontSize:11, color:"var(--ink)", fontWeight:600 },
  udflex_aicenter_g10: { display:"flex", alignItems:"center", gap:10 },
  ufs13_fw700_cink_ovhidden_toellipsis_wsnowrap: { fontSize:13, fontWeight:700, color:"var(--ink)", overflow:"hidden", textOverflow:"ellipsis", whiteSpace:"nowrap" },
  ufs18_fw900_cink: { fontSize:18, fontWeight:900, color:"var(--ink)" },
  ufs17_fw800_cink: { fontSize:17, fontWeight:800, color:"var(--ink)" },
  ufs12_cink: { fontSize:12, color:"var(--ink)" },
  ufs13_fw800_cink_mb10: { fontSize:13, fontWeight:800, color:"var(--ink)", marginBottom:10 },
  ufs12_cmuted_mb16_lh15: { fontSize:12, color:"var(--muted)", marginBottom:16, lineHeight:1.5 },
  ubgsurface_bd1pxsolid_br12_ovhidden: { background:"var(--surface)", border:"1px solid var(--border)", borderRadius:12, overflow:"hidden" },
  ufs12_cmuted: { fontSize:12, color:"var(--muted)" },
  ufs48_mb10: { fontSize:48, marginBottom:10 },
  uw20_h20_br50_bggreen_dflex_aicenter_jccenter_fs10_fw800_cin: { width:20,height:20,borderRadius:"50%",background:"var(--green)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:10,fontWeight:800,color:"var(--ink)" },
  ufs12_cmuted2_lh16: { fontSize:12, color:"var(--muted2)", lineHeight:1.6 },
  ufs12_fw700_cink_dblock_mb6: { fontSize:12, fontWeight:700, color:"var(--ink)", display:"block", marginBottom:6 },
  udflex_aicenter_g8: { display:"flex", alignItems:"center", gap:8 },
  ufw700: { fontWeight:700 },
  ufs13_fw700_cink_mb4: { fontSize:13, fontWeight:700, color:"var(--ink)", marginBottom:4 },
  ufs11_cmuted_curpointer_fw600_dflex_aicenter_g4: { fontSize:11, color:"var(--muted)", cursor:"pointer", fontWeight:600, display:"flex", alignItems:"center", gap:4 },
  udflex_flewrap_g6_mb10: { display:"flex", flexWrap:"wrap", gap:6, marginBottom:10 },
  ucgreen_fw700_curpointer: { color:"var(--green)", fontWeight:700, cursor:"pointer" },
  udflex_g10_aiflexstar: { display:"flex", gap:10, alignItems:"flex-start" },
  udflex_g8_mt14: { display:"flex", gap:8, marginTop:14 },
  ufs13_fw700_cink: { fontSize:13, fontWeight:700, color:"var(--ink)" },
  udflex_flewrap_g6: { display:"flex", flexWrap:"wrap", gap:6 },
  utacenter: { textAlign:"center" },
  ufs12_cmuted2: { fontSize:12, color:"var(--muted2)" },
  ubggreenlt_cgreen_bdcgreenmid: { background:"var(--green-lt)", color:"var(--green)", borderColor:"var(--green-mid)" },
  ufs18_fw800_cink: { fontSize:18, fontWeight:800, color:"var(--ink)" },
  ubgpaper2_cmuted2_bdcborder: { background:"var(--paper2)", color:"var(--muted2)", borderColor:"var(--border)" },
  udflex_aicenter_g6_p8px12px_bgsurface_bd1pxsolid_br10: { display:"flex", alignItems:"center", gap:6, padding:"8px 12px", background:"var(--surface)", border:"1px solid var(--border2)", borderRadius:10 },
  ufs12_cmuted_shr0: { fontSize:12, color:"var(--muted)", flexShrink:0 },
  uw100_bgnone_bdnone_cink_fff_fs13_outnone: { width:"100%", background:"none", border:"none", color:"var(--ink)", fontFamily:"var(--f)", fontSize:13, outline:"none" },
  ufs9_op06: { fontSize:9, opacity:.6 },
  udflex_aicenter_jcspacebet_mb8: { display:"flex", alignItems:"center", justifyContent:"space-between", marginBottom:8 },
  udflex_fdcolumn_aicenter_g4_curpointer: { display:"flex", flexDirection:"column", alignItems:"center", gap:4, cursor:"pointer" },
  ubgsheet_br20px20px_p20px16px_w100_mxh90vh_ovyauto: { background:"var(--sheet)", borderRadius:"20px 20px 0 0", padding:"20px 16px 140px", width:"100%", maxHeight:"90vh", overflowY:"auto" },
  udflex_g6_mb14: { display:"flex", gap:6, marginBottom:14 },
  ubgsurface_bd1pxsolid_br12_p14px_mb10: { background:"var(--surface)", border:"1px solid var(--border)", borderRadius:12, padding:"14px", marginBottom:10 },
  ufs11_cmuted_fw700_mb8: { fontSize:11, color:"var(--muted)", fontWeight:700, marginBottom:8 },
  uw100_bggreen_bdnone_br10_p10px_fff_fs13_fw700_congreen_curp: { width:"100%", background:"var(--green)", border:"none", borderRadius:10, padding:"10px", fontFamily:"var(--f)", fontSize:13, fontWeight:700, color:"var(--on-green)", cursor:"pointer" },
  ufs22: { fontSize:22 },
  udgrid_gri1fr1fr_g8_mb14: { display:"grid", gridTemplateColumns:"1fr 1fr", gap:8, marginBottom:14 },
  ufs24: { fontSize:24 },
  udflex_fdcolumn_g6: { display:"flex", flexDirection:"column", gap:6 },
  utacenter_p48px0: { textAlign:"center", padding:"48px 0" },
  ufs16_fw800_cink: { fontSize:16, fontWeight:800, color:"var(--ink)" },
  udflex_flewrap_g5_mb14: { display:"flex", flexWrap:"wrap", gap:5, marginBottom:14 },
  uw100_p11px_bgsurface2_bd1pxsolid_br12_fff_fs12_fw700_cink_c: { width:"100%", padding:"11px", background:"var(--surface2)", border:"1px solid var(--border)", borderRadius:12, fontFamily:"var(--f)", fontSize:12, fontWeight:700, color:"var(--ink)", cursor:"pointer" },
  udflex_aicenter_g12_mb12: { display:"flex", alignItems:"center", gap:12, marginBottom:12 },
  ufs11_cmuted_fw600_mb4: { fontSize:11, color:"var(--muted)", fontWeight:600, marginBottom:4 },
  ufs10_cmuted_fw600_mb4: { fontSize:10, color:"var(--muted)", fontWeight:600, marginBottom:4 },
  ucgreen: { color:"var(--green)" },
  udflex_aicenter_g10_p12px14px_bgsurface_bd1pxsolid_br12_mb12: { display:"flex", alignItems:"center", gap:10, padding:"12px 14px", background:"var(--surface)", border:"1px solid var(--border)", borderRadius:12, marginBottom:12 },
  uw16_h16_bd2pxsolid_borgreen_br50_anspin7sli_shr0: { width:16, height:16, border:"2px solid var(--border2)", borderTopColor:"var(--green)", borderRadius:"50%", animation:"spin .7s linear infinite", flexShrink:0 },
  ufs15_fw800_cink: { fontSize:15, fontWeight:800, color:"var(--ink)" },
  udflex_jcspacebet_aicenter_mb12: { display:"flex", justifyContent:"space-between", alignItems:"center", marginBottom:12 },
  ufs14_fw800_cink: { fontSize:14, fontWeight:800, color:"var(--ink)" },
  ufs11_cmuted_mb10: { fontSize:11, color:"var(--muted)", marginBottom:10 },
  udgrid_gri1fr1fr_g8_mb8: { display:"grid", gridTemplateColumns:"1fr 1fr", gap:8, marginBottom:8 },
  up8px10px_br10_bd1pxsolid_bgpaper_cink_fff_fs13_outnone: { padding:"8px 10px", borderRadius:10, border:"1px solid var(--border2)", background:"var(--paper)", color:"var(--ink)", fontFamily:"var(--f)", fontSize:13, outline:"none" },
  utacenter_p48px20px: { textAlign:"center", padding:"48px 20px" },
  umxh320_ovyauto_bd1pxsolid_br8: { maxHeight:320, overflowY:"auto", border:"1px solid var(--border)", borderRadius:8 },
  ufs22_shr0: { fontSize:22, flexShrink:0 },
  ufs13_fw800_cink_mb3: { fontSize:13, fontWeight:800, color:"var(--ink)", marginBottom:3 },
  ufs52_mb16: { fontSize:52, marginBottom:16 },
  udflex_fdcolumn_g10: { display:"flex", flexDirection:"column", gap:10 },
  utacenter_mb20: { textAlign:"center", marginBottom:20 },
  ufs13_fw700_cink_mb8: { fontSize:13, fontWeight:700, color:"var(--ink)", marginBottom:8 },
  udnone: { display:"none" },
  ucink: { color:"var(--ink)" },
  ufs10_cmuted_fw700_mb4: { fontSize:10, color:"var(--muted)", fontWeight:700, marginBottom:4 },
  udflex_aicenter_g8_mb12: { display:"flex", alignItems:"center", gap:8, marginBottom:12 },
  ufs10_fw700_cgreen_bggreenlt_bd1pxsolid_br100_p1px7px: { fontSize:10, fontWeight:700, color:"var(--green)", background:"var(--green-lt)", border:"1px solid var(--green-mid)", borderRadius:100, padding:"1px 7px" },
  ufs11_p3px8px: { fontSize:11, padding:"3px 8px" },
  uwsnowrap: { whiteSpace:"nowrap" },
  udflex_fdcolumn: { display:"flex", flexDirection:"column" },
  ufs13_cmuted2_lh15: { fontSize:13, color:"var(--muted2)", lineHeight:1.5 },
  ufs12_c555: { fontSize:12, color:"#555" },
  umb24: { marginBottom:24 },
  ufs13_fw700_ttuppercas_ls1px_c555_mb12: { fontSize:13, fontWeight:700, textTransform:"uppercase", letterSpacing:"1px", color:"#555", marginBottom:12 },
  udflex_flewrap_g8: { display:"flex", flexWrap:"wrap", gap:8 },
  ufs10_cmuted_mt1: { fontSize:10, color:"var(--muted)", marginTop:1 },
  udflex_aicenter_jccenter_g8_w100_p13px_br12_curpointer_bgsur: { display:"flex", alignItems:"center", justifyContent:"center", gap:8, width:"100%", padding:"13px", borderRadius:12, cursor:"pointer", background:"var(--surface)", border:"1px solid var(--border2)", color:"var(--ink2)", fontSize:13, fontWeight:600, marginBottom:10 },
  uw100_bgnone_bdnone_curpointer_fs12_cmuted_p8px0_fff: { width:"100%", background:"none", border:"none", cursor:"pointer", fontSize:12, color:"var(--muted)", padding:"8px 0", fontFamily:"var(--f)" },
  ubgsurface_bd1pxsolid_br12_p14px_mb14: { background:"var(--surface)", border:"1px solid var(--border)", borderRadius:12, padding:"14px", marginBottom:14 },
  uw100_bgnone_bdnone_curpointer_fs12_cmuted_p10px0_fff: { width:"100%", background:"none", border:"none", cursor:"pointer", fontSize:12, color:"var(--muted)", padding:"10px 0", fontFamily:"var(--f)" },
  ubgsurface_bd1pxsolid_br14_p14px16px_mb12: { background:"var(--surface)", border:"1px solid var(--border)", borderRadius:14, padding:"14px 16px", marginBottom:12 },
  ufs12_fw800_cink: { fontSize:12, fontWeight:800, color:"var(--ink)" },
  udflex_g8_aicenter: { display:"flex", gap:8, alignItems:"center" },
  ufs11_cgreen_fw700: { fontSize:11, color:"var(--green)", fontWeight:700 },
  ufs12_camber_fw600_p8px10px_bgamberlt_br8_mb10: { fontSize:12, color:"var(--amber)", fontWeight:600, padding:"8px 10px", background:"var(--amber-lt)", borderRadius:8, marginBottom:10 },
  udflex_aicenter_g5_p5px10px_bgpaper2_bd1pxsolid_br20: { display:"flex", alignItems:"center", gap:5, padding:"5px 10px", background:"var(--paper2)", border:"1px solid var(--border)", borderRadius:20 },
  ucurpointer_cmuted_fs14_lh1_p6_m6px6px6p: { cursor:"pointer", color:"var(--muted)", fontSize:14, lineHeight:1, padding:6, margin:"-6px -6px -6px 2px" },
  uflex1_fs12: { flex:1, fontSize:12 },
  uffmonospac: { fontFamily:"monospace" },
  udflex_g8_aiflexstar_p10px12px_bgpaper2_br10_mb14: { display:"flex", gap:8, alignItems:"flex-start", padding:"10px 12px", background:"var(--paper2)", borderRadius:10, marginBottom:14 },
  ushr0_mt1: { flexShrink:0, marginTop:1 },
  udflex_g6_flewrap: { display:"flex", gap:6, flexWrap:"wrap" },
  utacenter_mb16: { textAlign:"center", marginBottom:16 },
  ufs15_fw700_cink: { fontSize:15, fontWeight:700, color:"var(--ink)" },
  ufs12_cmuted_mt4: { fontSize:12, color:"var(--muted)", marginTop:4 },
  ufdcolumn_aiflexstar_g4: { flexDirection:"column", alignItems:"flex-start", gap:4 },
  ufw800: { fontWeight:800 },
  ufw500_fs12_lh15: { fontWeight:500, fontSize:12, lineHeight:1.5 },
  utacenter_mt12_fs12_cmuted: { textAlign:"center", marginTop:12, fontSize:12, color:"var(--muted)" },
  ufs11_cmuted_fw500: { fontSize:11, color:"var(--muted)", fontWeight:500 },
  udflex_aicenter_g10_mb8: { display:"flex", alignItems:"center", gap:10, marginBottom:8 },
  utacenter_p20px20px: { textAlign:"center", padding:"20px 20px 14px" },
  ufs17_fw900_cink_mb6: { fontSize:17, fontWeight:900, color:"var(--ink)", marginBottom:6 },
  udflex_aicenter_jcspacebet_mb12: { display:"flex", alignItems:"center", justifyContent:"space-between", marginBottom:12 },
  ufs13_cmuted2_mb8: { fontSize:13, color:"var(--muted2)", marginBottom:8 },
  ufs28_shr0: { fontSize:28, flexShrink:0 },
  ubgsurface_bd1pxsolid_br14_p14px16px_mb10: { background:"var(--surface)", border:"1px solid var(--border)", borderRadius:14, padding:"14px 16px", marginBottom:10 },
  ufs11_cmuted_mb8: { fontSize:11, color:"var(--muted)", marginBottom:8 },
  ucurpointer: { cursor:"pointer" },
  ufs12_cmuted_mt1: { fontSize:12, color:"var(--muted)", marginTop:1 },
  up12px14px: { padding:"12px 14px" },
  ufs13_fw800_cink_mb4: { fontSize:13, fontWeight:800, color:"var(--ink)", marginBottom:4 },
  ufs12_fw800: { fontSize:12, fontWeight:800 },
  ufs12_fw800_ls01em_ttuppercas: { fontSize:12, fontWeight:800, letterSpacing:".01em", textTransform:"uppercase" },
  ufs10_cmuted_lh15: { fontSize:10, color:"var(--muted)", lineHeight:1.5 },
  ufs12_cmuted_mb12: { fontSize:12, color:"var(--muted)", marginBottom:12 },
  ufs12_fw700_cmuted_ttuppercas_ls1px_mb10: { fontSize:12, fontWeight:700, color:"var(--muted)", textTransform:"uppercase", letterSpacing:"1px", marginBottom:10 },
  uw100_p9px_br10_bd1pxdashe_bgnone_cmuted_fff_fs13_curpointer: { width:"100%", padding:"9px", borderRadius:10, border:"1px dashed var(--border2)", background:"none", color:"var(--muted)", fontFamily:"var(--f)", fontSize:13, cursor:"pointer" },
  ufs12_cink3_mb8: { fontSize:12, color:"var(--ink3)", marginBottom:8 },
  ufs12_cmuted_lh15: { fontSize:12, color:"var(--muted)", lineHeight:1.5 },
  uw32_h32_br50_bgrgba2552_bdnone_curpointer_dflex_aicenter_jc: { width:32, height:32, borderRadius:"50%", background:"rgba(255,255,255,.92)", border:"none", cursor:"pointer",
              display:"flex", alignItems:"center", justifyContent:"center", boxShadow:"0 2px 8px rgba(21,32,26,.18)" },
  udflex_fdcolumn_g4: { display:"flex", flexDirection:"column", gap:4 },
  ufs10_cmuted_mt8: { fontSize:10, color:"var(--muted)", marginTop:8 },
  udflex_aicenter_g10_p12px14px_bgsurface_bd1pxsolid_br12: { display:"flex", alignItems:"center", gap:10, padding:"12px 14px", background:"var(--surface)", border:"1px solid var(--border)", borderRadius:12 },
  uflex1_p10px_bggreen_bdnone_br10_fff_fs13_fw800_congreen_cur: { flex:1, padding:"10px", background:"var(--green)", border:"none", borderRadius:10,
              fontFamily:"var(--f)", fontSize:13, fontWeight:800, color:"var(--on-green)", cursor:"pointer" },
  uw34_h34_bgsurface2_br9_dflex_aicenter_jccenter_shr0: { width:34, height:34, background:"var(--surface2)", borderRadius:9, display:"flex", alignItems:"center", justifyContent:"center", flexShrink:0 },
  ufs13_fw700: { fontSize:13, fontWeight:700 },
  ufs16_cmuted2: { fontSize:16, color:"var(--muted2)" },
  ubgsurface_br14_p12px14px_mt12_bd1pxsolid: { background:"var(--surface)", borderRadius:14, padding:"12px 14px", marginTop:12, border:"1px solid var(--border)" },
  up3px9px_br20_bggreenlt_bd1pxsolid_fs10_cgreen_fw700: { padding:"3px 9px", borderRadius:20, background:"var(--green-lt)", border:"1px solid var(--green-mid)", fontSize:10, color:"var(--green)", fontWeight:700 },
  ufs9_cmuted2: { fontSize:9, color:"var(--muted2)" },
};
