-- Allergileksikon: faglig kvalitetssikring (30. sept. 2026, Bjørn).
-- Fuld kopi af tabellen før ændringerne ligger i knowledge_base_backup_20260930
-- (RLS slået til, ingen API-adgang). Rul tilbage ved at genindsætte derfra.

create table if not exists public.knowledge_base_backup_20260930 as select * from public.knowledge_base;
alter table public.knowledge_base_backup_20260930 enable row level security;
revoke all on public.knowledge_base_backup_20260930 from anon, authenticated;

-- "Faglig status" pr. opslag (fx "Fødevareallergi", "Intolerance – ikke allergi").
alter table public.knowledge_base add column if not exists status_label text;

-- Ny kategori "dish" (Retter og produkter): færdige retter, bagværk, slik,
-- drikkevarer og færdigprodukter, som tidligere lå under Ingredienser.
alter table public.knowledge_base drop constraint knowledge_base_category_check;
alter table public.knowledge_base add constraint knowledge_base_category_check
  check (category = any (array['allergen','e_number','ingredient','diet','cross_reaction','faq','fun_fact','dish']));

-- Risikoniveauer fjernes: "Høj risiko"/"Moderat" kunne læses som en
-- universel medicinsk vurdering, men alvoren afhænger af personen.
update public.knowledge_base set risk_level = null where risk_level is not null;


-- ── Allergener: EU's 14 mærkningspligtige allergener + hvede ──
update public.knowledge_base set status_label = $q$Fødevareallergi$q$, summary = $q$En af de hyppigste fødevareallergier hos børn. Både æggehvide og æggeblomme kan give reaktioner.$q$, description = $q$Ved ægallergi reagerer immunforsvaret på proteiner i æg, især i æggehviden (fx ovalbumin og ovomucoid), men også æggeblommen kan give reaktioner. Mange børn vokser fra allergien. Nogle tåler gennembagt æg, fordi varme ændrer en del af proteinerne, mens andre reagerer på alle former. Symptomerne varierer fra person til person.$q$, health_notes = $q$Hvilke former for æg den enkelte tåler, afklares bedst med egen læge. Æg kan stå i ingredienslister som fx albumin, ovalbumin eller lysozym.$q$, updated_at = now() where slug = $q$aeg$q$;
update public.knowledge_base set status_label = $q$Fødevareallergi$q$, summary = $q$Allergi over for proteiner i fisk, især parvalbumin. Allergien er ofte langvarig.$q$, description = $q$Fiskeallergi skyldes oftest parvalbumin, et protein der findes i mange fiskearter. Nogle reagerer på flere arter, andre kun på enkelte. Allergien er ofte langvarig. Fiskeallergi er forskellig fra allergi over for skaldyr og bløddyr, og man kan have den ene uden den anden. Hos nogle kan dampe fra tilberedning give symptomer.$q$, health_notes = $q$Fisk kan indgå i fx fiskesauce, Worcestershire-sauce, surimi, tapenade og visse omega-3-tilskud.$q$, updated_at = now() where slug = $q$fisk$q$;
update public.knowledge_base set title = $q$Glutenholdige kornsorter$q$, status_label = $q$Cøliaki og hvedeallergi$q$, summary = $q$Hvede (inkl. spelt og kamut), rug, byg og havre. Relevant ved cøliaki og hvedeallergi, som er to forskellige tilstande.$q$, description = $q$Glutenholdige kornsorter er en af de 14 allergengrupper, der skal fremhæves i ingredienslisten i EU. Gruppen dækker hvede (inkl. spelt og kamut), rug, byg og havre.

Cøliaki er en autoimmun sygdom, hvor gluten skader tyndtarmens slimhinde. Det er ikke en allergi. Behandlingen er livslang glutenfri kost.

Hvedeallergi er en fødevareallergi, hvor immunforsvaret reagerer på proteiner i hvede og ikke kun på gluten. Produkter mærket glutenfri kan indeholde hvedestivelse og er derfor ikke nødvendigvis egnede ved hvedeallergi.

Glutenfølsomhed uden cøliaki bruges om symptomer efter gluten, hvor både cøliaki og hvedeallergi er udelukket.$q$, health_notes = $q$Et produkt må kaldes glutenfrit, når det indeholder højst 20 mg gluten pr. kg. Havre er naturligt uden gluten, men forurenes ofte med andre kornsorter; se efter havre mærket glutenfri.$q$, allergen_ids = array[$q$gluten$q$,$q$hvede$q$]::text[], updated_at = now() where slug = $q$gluten$q$;
update public.knowledge_base set status_label = $q$Fødevareallergi$q$, summary = $q$En bælgfrugt og ikke en nød. Allergien begynder ofte i barndommen og er hos mange langvarig.$q$, description = $q$Jordnødder er bælgfrugter og ikke botanisk beslægtet med trænødder, men en del med jordnøddeallergi reagerer også på trænødder. Allergien begynder ofte i barndommen og er hos mange langvarig. Jordnøddeproteinerne tåler varme, så ristning og forarbejdning fjerner dem ikke. Hvor kraftige reaktionerne er, varierer meget fra person til person.$q$, health_notes = $q$Nogle med jordnøddeallergi reagerer også på lupin eller andre bælgfrugter. Raffineret jordnøddeolie indeholder kun lidt protein, men om den tåles, er individuelt.$q$, updated_at = now() where slug = $q$jordnoedder$q$;
update public.knowledge_base set status_label = $q$Fødevareallergi$q$, summary = $q$Bælgfrugt brugt som mel og protein. En del med jordnøddeallergi reagerer også på lupin.$q$, description = $q$Lupinfrø bruges som mel og proteinkilde i fx glutenfrit bagværk, pasta og plantebaserede produkter. Lupin er et af de 14 allergener, der skal fremhæves i ingredienslisten i EU. En del personer med jordnøddeallergi reagerer også på lupin, fordi proteinerne ligner hinanden.$q$, health_notes = $q$Lupin kan stå som lupin, lupinmel eller lupinprotein i ingredienslisten.$q$, updated_at = now() where slug = $q$lupin$q$;
update public.knowledge_base set title = $q$Mælk (mælkeprotein)$q$, status_label = $q$Fødevareallergi$q$, summary = $q$Allergi over for proteiner i mælk (kasein og valle). Ikke det samme som laktoseintolerance.$q$, description = $q$Ved mælkeallergi reagerer immunforsvaret på proteiner i mælk, primært kasein og valleproteiner. Det er en af de hyppigste fødevareallergier hos små børn, og de fleste vokser fra den. Mælkeallergi er noget andet end laktoseintolerance, hvor det er mælkesukkeret og ikke proteinerne, der giver problemer. Derfor er laktosefri mælk ikke egnet ved mælkeallergi. Mælk fra ged og får ligner komælk og giver ofte også reaktioner.$q$, health_notes = $q$Mælkeprotein kan stå som fx kasein, kaseinat, valle, valleprotein, laktalbumin eller mælkepulver.$q$, allergen_ids = array[$q$maelkeallergi$q$]::text[], updated_at = now() where slug = $q$maelkeallergi$q$;
update public.knowledge_base set status_label = $q$Fødevareallergi$q$, summary = $q$Trænødder som mandel, hasselnød, valnød og cashew. Man reagerer ikke nødvendigvis på alle typer.$q$, description = $q$Gruppen dækker mandler, hasselnødder, valnødder, cashewnødder, pekannødder, paranødder, pistacienødder og macadamianødder. Nøddeallergi er ofte langvarig. Nogle reagerer på flere nøddetyper, andre kun på én. Jordnødder hører ikke til gruppen, da de er bælgfrugter. Hos personer med birkepollenallergi kan især hasselnød give kløe i munden.$q$, health_notes = $q$Kokos og muskatnød er ikke trænødder og er ikke omfattet af mærkningskravet for nødder.$q$, updated_at = now() where slug = $q$noedder$q$;
update public.knowledge_base set status_label = $q$Fødevareallergi$q$, summary = $q$Både knoldselleri, bladselleri og sellerifrø kan give reaktioner. Ses oftere i Centraleuropa end i Danmark.$q$, description = $q$Selleriallergi omfatter knoldselleri, bladselleri og sellerifrø. Allergien ses oftere i Centraleuropa end i Danmark. Hos nogle hænger den sammen med pollenallergi, især over for birk og bynke. Nogle af selleriens proteiner nedbrydes ved opvarmning, andre ikke, så om tilberedt selleri tåles, er individuelt.$q$, health_notes = $q$Selleri indgår ofte i bouillon, supper, krydderiblandinger og sellerisalt.$q$, updated_at = now() where slug = $q$selleri$q$;
update public.knowledge_base set status_label = $q$Fødevareallergi$q$, summary = $q$Frø fra gul, brun og sort sennep. Findes ofte i dressinger, marinader og krydderiblandinger.$q$, description = $q$Sennepsallergi skyldes proteiner i sennepsfrø. Sennep bruges i mange saucer, dressinger, marinader, pølser og krydderiblandinger, også hvor det ikke er den tydeligste smag. Sennep tilhører korsblomstfamilien, og nogle reagerer også på beslægtede planter som raps, peberrod og wasabi.$q$, health_notes = $q$Sennep kan indgå i fx karry og krydderiblandinger, men skal altid fremhæves i ingredienslisten.$q$, alternatives = array[]::text[], updated_at = now() where slug = $q$sennep$q$;
update public.knowledge_base set status_label = $q$Fødevareallergi$q$, summary = $q$Sesamfrø og sesamolie. Findes i bl.a. brød, hummus, tahini og asiatisk mad.$q$, description = $q$Sesamallergi skyldes proteiner i sesamfrø. Sesam bruges i bagværk, tahini, hummus, halva og mange asiatiske retter. Koldpresset sesamolie kan indeholde protein fra frøet. Nogle med sesamallergi reagerer også på nødder eller jordnødder.$q$, health_notes = $q$Sesam kan stå som sesamfrø, sesamolie, tahini eller sesampasta.$q$, updated_at = now() where slug = $q$sesam$q$;
update public.knowledge_base set title = $q$Skaldyr (krebsdyr)$q$, status_label = $q$Fødevareallergi$q$, summary = $q$Rejer, hummer, krabber, jomfruhummer og krebs. En separat allergengruppe fra bløddyr og fisk.$q$, description = $q$Skaldyrsallergi (allergi over for krebsdyr) skyldes oftest proteinet tropomyosin. Allergien kan opstå både hos børn og voksne og er ofte langvarig. Tropomyosin ligner et protein i husstøvmider, så nogle med husstøvmideallergi reagerer også på skaldyr. Bløddyr som muslinger og blæksprutter er en separat allergengruppe, men nogle reagerer på begge.$q$, health_notes = $q$Skaldyr kan indgå i fx fiskefars, bisque, paella og asiatiske saucer og pastaer.$q$, updated_at = now() where slug = $q$skaldyr$q$;
update public.knowledge_base set status_label = $q$Fødevareallergi$q$, summary = $q$Bælgfrugt, der bruges bredt i forarbejdede fødevarer. Allergien er hyppigst hos børn.$q$, description = $q$Sojaallergi ses oftest hos børn, og mange vokser fra den. Soja bruges i mange former, fx tofu, sojadrik, sojaprotein, sojasauce og sojalecitin. Højt forarbejdede ingredienser som sojalecitin og raffineret sojaolie indeholder kun lidt protein, men om de tåles, er individuelt.$q$, health_notes = $q$Soja kan stå som soja, sojaprotein, sojamel, sojalecitin (E322) eller edamame.$q$, updated_at = now() where slug = $q$soja$q$;
update public.knowledge_base set status_label = $q$Overfølsomhed – sjældent allergi$q$, summary = $q$Konserveringsmidler (E220–E228). Reaktioner er oftest overfølsomhed og kun sjældent egentlig allergi.$q$, description = $q$Svovldioxid og sulfitter bruges til at konservere og forhindre misfarvning i fx vin, tørret frugt og kartoffelprodukter. Reaktioner på sulfitter er som regel ikke en klassisk allergi, men en overfølsomhed, der især ses hos nogle personer med astma. Symptomerne kan fx være hoste, åndenød eller udslæt. Sulfitter skal angives, når indholdet er over 10 mg pr. kg eller pr. liter.$q$, health_notes = $q$Sulfitter har E-numrene E220–E228.$q$, updated_at = now() where slug = $q$svovl$q$;
update public.knowledge_base set status_label = $q$Fødevareallergi$q$, summary = $q$Muslinger, østers, blæksprutter og snegle. En separat allergengruppe fra skaldyr (krebsdyr).$q$, description = $q$Bløddyrallergi omfatter bl.a. muslinger, østers, kammuslinger, blæksprutter og snegle. Allergien skyldes ofte tropomyosin, et protein der også findes i krebsdyr. Derfor reagerer nogle på både bløddyr og skaldyr, mens andre kun reagerer på den ene gruppe.$q$, health_notes = $q$Bløddyr kan indgå i fx østerssauce og andre asiatiske saucer.$q$, alternatives = array[]::text[], updated_at = now() where slug = $q$bloeddyr$q$;
insert into public.knowledge_base (category, title, slug, emoji, summary, description, health_notes, found_in, alternatives, aliases, allergen_ids, sources, status_label, sort_order, updated_at)
select 'allergen', 'Hvede', 'hvede', '🌾',
 $q$Allergi over for proteiner i hvede. Forskellig fra cøliaki, og glutenfri produkter er ikke altid egnede.$q$,
 $q$Ved hvedeallergi reagerer immunforsvaret på et eller flere proteiner i hvede. Det er en fødevareallergi og ikke det samme som cøliaki, der er en autoimmun sygdom udløst af gluten. Hvedeallergi er hyppigst hos børn, og mange vokser fra den. Da allergien retter sig mod hvedens proteiner generelt, kan produkter mærket glutenfri stadig indeholde hvede i form af hvedestivelse. Om man tåler andre kornsorter som rug og byg, er individuelt.$q$,
 $q$Hvede kan stå som fx hvedemel, durum, semulje, spelt, kamut, hvedestivelse eller hvedeprotein.$q$,
 array['Brød og bagværk','Pasta og couscous','Panering','Saucer jævnet med mel','Øl','Mange færdigretter'],
 array['Ris','Majs','Boghvede','Quinoa','Hirse'],
 array['Wheat','Hvedemel','Durum','Semulje','Spelt','Kamut','Hvedestivelse'],
 array['hvede'],
 (select sources from public.knowledge_base where slug='gluten'),
 'Fødevareallergi', 0, now()
where not exists (select 1 from public.knowledge_base where slug='hvede');

-- Laktose er ikke en allergen: flyttes til Ingredienser som stof, med intolerance-status.
update public.knowledge_base set category = $q$ingredient$q$, title = $q$Laktose (mælkesukker)$q$, status_label = $q$Intolerance – ikke allergi$q$, summary = $q$Sukkeret i mælk. Laktoseintolerance er en fordøjelsesreaktion og ikke en allergi.$q$, description = $q$Laktose er det naturlige sukker i mælk. For at fordøje laktose skal tarmen bruge enzymet laktase. Ved laktoseintolerance dannes der for lidt laktase, og ufordøjet laktose kan give fx oppustethed, mavesmerter og diarré. Det er ikke en allergi, og immunforsvaret er ikke involveret. De fleste med laktoseintolerance tåler mindre mængder, og indholdet er lavt i fx lagret ost og smør. Laktoseintolerance er noget andet end mælkeallergi, hvor man reagerer på mælkens proteiner.$q$, health_notes = $q$Laktosefri produkter indeholder stadig mælkeprotein og er derfor ikke egnede ved mælkeallergi.$q$, aliases = array[$q$Mælkesukker$q$,$q$Lactose$q$]::text[], updated_at = now() where slug = $q$laktose$q$;

-- ── Allergen-id'er: mælkeprotein og hvede adskilt fra laktose og gluten ──
update public.knowledge_base set allergen_ids = array_append(allergen_ids, 'maelkeallergi'), updated_at = now()
where 'laktose' = any(allergen_ids) and not ('maelkeallergi' = any(allergen_ids))
  and slug not in ('laktose','diaet-laktosefri','e-966','e-441','cross-maelk-oksekod','cross-ko-ged-maelk');
update public.knowledge_base set allergen_ids = array_remove(allergen_ids, 'laktose'), updated_at = now() where slug = 'e-441';
update public.knowledge_base set allergen_ids = array['maelkeallergi'], updated_at = now() where slug in ('cross-maelk-oksekod','cross-ko-ged-maelk');
update public.knowledge_base set allergen_ids = array_append(coalesce(allergen_ids,'{}'), 'hvede'), updated_at = now()
where slug in ($q$ing-hvedemel$q$,$q$ing-hvede-gluten$q$,$q$ing-hvede$q$,$q$ing-tortilla$q$,$q$ing-ramen-nudler$q$,$q$ing-soba-nudler$q$,$q$ing-aeggenudler$q$,$q$ing-spelt$q$,$q$ing-bulgur$q$,$q$ing-couscous$q$,$q$ing-vital-wheat-gluten$q$,$q$ing-hvedeklid$q$,$q$ing-fuldkorn-hvedemel$q$,$q$ing-tipo00$q$,$q$ing-manitobamel$q$,$q$ing-durum-wrap$q$,$q$ing-sojasauce$q$,$q$ing-naan$q$,$q$ing-pitabroed$q$,$q$ing-frikadeller$q$,$q$ing-karbonader$q$,$q$ing-klejner$q$,$q$ing-brunkager$q$,$q$ing-pebernodder$q$,$q$ing-aebleskiver$q$,$q$ing-wienerbroed$q$,$q$ing-stegt-flaesk$q$,$q$faq-hvede-vs-gluten$q$) and not ('hvede' = any(coalesce(allergen_ids,'{}')));

-- ── Ingredienser = det, der kan stå i en ingrediensliste. Retter/produkter flyttes ──
update public.knowledge_base set category = 'dish', updated_at = now() where category = 'ingredient' and slug in ($q$ing-babymos$q$,$q$ing-biksemad$q$,$q$ing-blodpolse$q$,$q$ing-brunede-kartofler$q$,$q$ing-brunkager$q$,$q$ing-cornflakes$q$,$q$ing-durum-wrap$q$,$q$ing-energidrik$q$,$q$ing-falafel$q$,$q$ing-flaeskesvaer$q$,$q$ing-hotdogpolse$q$,$q$ing-frikadeller$q$,$q$ing-faerdigsalat$q$,$q$ing-hummus$q$,$q$ing-mejeri-is$q$,$q$ing-softice$q$,$q$ing-sodavand-farve$q$,$q$ing-karbonader$q$,$q$ing-kebabkod$q$,$q$ing-klejner$q$,$q$ing-knaekbroed$q$,$q$ing-kombucha$q$,$q$ing-chai$q$,$q$ing-salt-lakrids$q$,$q$ing-leverpostej$q$,$q$ing-marshmallows$q$,$q$ing-modermaelkserstatning$q$,$q$ing-most$q$,$q$ing-muesli$q$,$q$ing-cerealbar$q$,$q$ing-musli-yoghurt$q$,$q$ing-chokolade-muslibar$q$,$q$ing-naan$q$,$q$ing-nougat$q$,$q$ing-pebernodder$q$,$q$ing-pitabroed$q$,$q$ing-pommes-frites$q$,$q$ing-proteinbar$q$,$q$ing-valleprotein$q$,$q$ing-risalamande$q$,$q$ing-rugbroed$q$,$q$ing-shawarma$q$,$q$ing-skumfiduser$q$,$q$ing-smoothie$q$,$q$ing-sodavand$q$,$q$ing-sorbet$q$,$q$ing-spegepolse$q$,$q$ing-stegt-flaesk$q$,$q$ing-tortilla$q$,$q$ing-wienerbroed$q$,$q$ing-aebleskiver$q$,$q$ing-aeggekage$q$,$q$ing-skyr-drik$q$,$q$ing-frugtjuice$q$,$q$ing-te-typer$q$,$q$ing-kamillete$q$,$q$ing-rooibos$q$,$q$ing-mate$q$,$q$ing-naeldete$q$,$q$ing-kaffefloede-pulver$q$,$q$ing-fritter-remoulade$q$);

-- ── Dubletter (samme opslag to gange) — den svageste slettes, backup ovenfor ──
delete from public.knowledge_base where slug in ($q$ing-horfrø$q$,$q$ing-chiafrø$q$,$q$ing-solsikkefor$q$,$q$ing-gelatin$q$,$q$ing-tahini$q$,$q$ing-karry$q$,$q$ing-salt$q$,$q$ing-havremaelk$q$,$q$ing-mandelmaelk$q$,$q$ing-sojamaelk$q$,$q$ing-naturlig-aroma$q$,$q$ing-baegegaer$q$,$q$ing-e471$q$,$q$ing-kokosnod$q$,$q$kryds-birk$q$,$q$kryds-latex$q$,$q$kryds-skaldyr-mider$q$,$q$faq-allergi-vs-intolerance$q$,$q$cross-hvede-korn$q$);

-- ── Ingredienser: neutrale korte beskrivelser ──
update public.knowledge_base set summary = $q$Det mest brugte mel i Danmark. Indeholder hvede og gluten.$q$, updated_at = now() where slug = $q$ing-hvedemel$q$;
update public.knowledge_base set summary = $q$Olie presset af oliven. Extra virgin er den mindst forarbejdede type.$q$, updated_at = now() where slug = $q$ing-olivenolie$q$;
update public.knowledge_base set summary = $q$Sukkeralkohol brugt som sødemiddel, fx i tyggegummi. Større mængder kan give løs mave.$q$, updated_at = now() where slug = $q$ing-xylitol$q$;
update public.knowledge_base set summary = $q$Konserveringsmiddel (E211) i fx læskedrikke og saucer. Kan sammen med C-vitamin danne små mængder benzen.$q$, updated_at = now() where slug = $q$ing-natriumbenzoat$q$;
update public.knowledge_base set summary = $q$Smagsforstærker (E621), der giver umamismag. Godkendt i EU som tilsætningsstof.$q$, updated_at = now() where slug = $q$ing-msg$q$;
update public.knowledge_base set summary = $q$Rødt farvestof (E120) udvundet af cochenillelus. Ikke vegansk og kan hos enkelte give allergiske reaktioner.$q$, updated_at = now() where slug = $q$ing-karminsyre$q$;
update public.knowledge_base set summary = $q$C-vitamin (E300), der bruges som antioxidant i fødevarer.$q$, updated_at = now() where slug = $q$ing-ascorbinsyre$q$;
update public.knowledge_base set summary = $q$Koncentreret hvedeprotein brugt som kødalternativ. Ikke egnet ved cøliaki eller hvedeallergi.$q$, updated_at = now() where slug = $q$ing-hvede-gluten$q$;
update public.knowledge_base set summary = $q$Fedtsyrer, som kroppen ikke selv kan danne. Findes især i fed fisk, alger og visse frø.$q$, updated_at = now() where slug = $q$ing-omega3$q$;
update public.knowledge_base set summary = $q$Korn, der er naturligt uden gluten, men ofte forurenes med hvede, rug eller byg. Glutenfri havre findes.$q$, updated_at = now() where slug = $q$ing-havre$q$;
update public.knowledge_base set summary = $q$Knold- og bladselleri. Selleri er et af de 14 allergener, der skal fremhæves i ingredienslisten.$q$, updated_at = now() where slug = $q$ing-selleri$q$;
update public.knowledge_base set summary = $q$Frø med omega-3 og fiber. Danner gel i væske og bruges fx som ægerstatning.$q$, updated_at = now() where slug = $q$ing-chiafor$q$;
update public.knowledge_base set summary = $q$Protein udvundet af dyrehud og knogler, ofte fra svin. Ikke vegansk og kun halal, hvis kilden er det.$q$, updated_at = now() where slug = $q$ing-gelatine$q$;
update public.knowledge_base set summary = $q$Kålsort med mange vitaminer og mineraler, bl.a. K-vitamin.$q$, updated_at = now() where slug = $q$ing-gronkal$q$;
update public.knowledge_base set summary = $q$Grøntsag fra korsblomstfamilien med fibre og C-vitamin.$q$, updated_at = now() where slug = $q$ing-broccoli$q$;
update public.knowledge_base set summary = $q$Bær fra en sydamerikansk palme. Sælges i Danmark mest frosset eller som pulver.$q$, updated_at = now() where slug = $q$ing-acai$q$;
update public.knowledge_base set summary = $q$Kødalternativ lavet af svampeprotein (mykoprotein). Kan give reaktioner hos personer, der ikke tåler svampe.$q$, updated_at = now() where slug = $q$ing-quorn$q$;
update public.knowledge_base set summary = $q$Frugt fra kokospalmen og ikke en trænød. Kokos er ikke blandt de 14 mærkningspligtige allergener.$q$, updated_at = now() where slug = $q$ing-kokosnoed$q$;
update public.knowledge_base set summary = $q$Plantedrik lavet af havre. Bruges som alternativ til mælk, fx i kaffe og på morgenmad.$q$, updated_at = now() where slug = $q$ing-havredrik$q$;
update public.knowledge_base set summary = $q$Pasta af malede sesamfrø. Indgår i hummus og baba ghanoush og indeholder sesam.$q$, updated_at = now() where slug = $q$ing-tahin$q$;
update public.knowledge_base set summary = $q$Frø med omega-3, fiber og lignaner. Skal knuses eller males for at næringsstofferne optages.$q$, updated_at = now() where slug = $q$ing-horfro$q$;
update public.knowledge_base set title = $q$Karry (krydderiblanding)$q$, updated_at = now() where slug = $q$ing-karryblanding$q$;
update public.knowledge_base set title = $q$Salt (natriumchlorid)$q$, updated_at = now() where slug = $q$ing-natriumchlorid$q$;

-- ── Diæter ──
update public.knowledge_base set title = $q$Lav-FODMAP$q$, summary = $q$Kost med få fermenterbare kulhydrater. Bruges tidsbegrænset ved irritabel tyktarm, gerne med hjælp fra en diætist.$q$, updated_at = now() where slug = $q$diaet-fodmap$q$;
update public.knowledge_base set summary = $q$Planter udgør hoveddelen af kosten, men mindre mængder animalske produkter kan indgå. Ikke nødvendigvis vegansk.$q$, description = $q$Plantebaseret kost har planter som den primære del af kosten, men kan i modsætning til vegansk kost indeholde mindre mængder animalske produkter. Betegnelsen er ikke fast defineret, så et produkt mærket plantebaseret er ikke nødvendigvis vegansk. Tjek ingredienslisten, hvis du undgår bestemte animalske ingredienser.$q$, health_notes = null, updated_at = now() where slug = $q$diaet-plantebaseret$q$;
update public.knowledge_base set health_notes = $q$Ved vegansk kost anbefales tilskud af B12-vitamin. Vær desuden opmærksom på D-vitamin, jern, calcium, jod og omega-3.$q$, updated_at = now() where slug = $q$diaet-vegansk$q$;

-- ── Krydsreaktioner ──
update public.knowledge_base set title = $q$Birkepollen ↔ Æbler og stenfrugter$q$, summary = $q$Birkepollen og visse rå frugter har lignende proteiner. Det kan give kløe i munden (oral allergi-syndrom).$q$, updated_at = now() where slug = $q$cross-birk-aebel$q$;
update public.knowledge_base set summary = $q$Nogle med græspollenallergi får kløe i munden af rå tomat og melon.$q$, updated_at = now() where slug = $q$cross-graes-tomat$q$;
update public.knowledge_base set summary = $q$Nogle med latexallergi reagerer også på avocado, banan, kiwi og kastanje (latex-frugt-syndrom).$q$, updated_at = now() where slug = $q$cross-latex-frugt$q$;
update public.knowledge_base set summary = $q$Jordnødder og lupin har lignende proteiner. En del med jordnøddeallergi reagerer også på lupin.$q$, updated_at = now() where slug = $q$cross-jordnod-lupin$q$;
update public.knowledge_base set summary = $q$Tropomyosin findes i både skaldyr og husstøvmider. Nogle med mideallergi reagerer derfor på skaldyr.$q$, updated_at = now() where slug = $q$cross-skaldyr-husstov$q$;
update public.knowledge_base set summary = $q$Et protein i komælk (serumalbumin) findes også i oksekød. Enkelte med mælkeallergi reagerer på kød, der ikke er gennemstegt.$q$, updated_at = now() where slug = $q$cross-maelk-oksekod$q$;
update public.knowledge_base set summary = $q$Sjælden sammenhæng mellem allergi over for fugle, æggeblomme og fjerkrækød (æg-fugl-syndrom).$q$, updated_at = now() where slug = $q$cross-aeg-fjerkrae$q$;
update public.knowledge_base set title = $q$Bynkepollen ↔ Selleri og krydderier$q$, summary = $q$Bynkepollen (Artemisia) kan krydsreagere med selleri, gulerod og visse krydderier.$q$, updated_at = now() where slug = $q$cross-artemisia-selleri$q$;
update public.knowledge_base set title = $q$Fisk ↔ Andre fiskearter$q$, summary = $q$Mange med fiskeallergi reagerer på flere fiskearter, fordi proteinet parvalbumin ligner hinanden på tværs af arter.$q$, updated_at = now() where slug = $q$cross-fisk-kryds$q$;
update public.knowledge_base set summary = $q$Soja og andre bælgfrugter har lignende proteiner, men krydsreaktioner i praksis er sjældne.$q$, updated_at = now() where slug = $q$cross-soja-baelg$q$;
update public.knowledge_base set title = $q$Trænødder indbyrdes$q$, summary = $q$Krydsreaktioner mellem trænødder forekommer, fx mellem cashew og pistacie, men er ikke givet.$q$, updated_at = now() where slug = $q$cross-nodder-interne$q$;
update public.knowledge_base set summary = $q$Proteinerne i ged- og fåremælk ligner komælkens, så de fleste med komælksallergi reagerer også på dem.$q$, updated_at = now() where slug = $q$cross-ko-ged-maelk$q$;
update public.knowledge_base set summary = $q$Peberrod, sennep, wasabi og raps tilhører korsblomstfamilien. Nogle reagerer på flere af dem.$q$, updated_at = now() where slug = $q$cross-peberrod-sennep$q$;
update public.knowledge_base set summary = $q$Nogle med jordnøddeallergi reagerer også på andre bælgfrugter. Lupin er den hyppigste.$q$, updated_at = now() where slug = $q$kryds-jordnod-baelg$q$;
update public.knowledge_base set description = $q$Parvalbumin er det vigtigste allergen i fisk og ligner hinanden på tværs af mange fiskearter. Derfor reagerer mange med fiskeallergi på flere arter. Indholdet varierer dog mellem arter, og nogle tåler enkelte fiskearter. Parvalbumin er ikke det samme som tropomyosin i skaldyr, så fiskeallergi og skaldyrsallergi er to forskellige allergier.$q$, health_notes = $q$Hvilke fiskearter den enkelte tåler, afklares med lægen.$q$, alternatives = array[]::text[], updated_at = now() where slug = $q$cross-fisk-kryds$q$;
update public.knowledge_base set description = $q$Peberrod, sennep, wasabi, raps og kål tilhører korsblomstfamilien (Brassicaceae), og nogle af deres proteiner ligner hinanden. Ved sennepsallergi kan særligt wasabi og peberrod give reaktioner. Klinisk krydsreaktion med kål og broccoli er sjælden. Sennep er et af de 14 allergener, der skal fremhæves i ingredienslisten.$q$, health_notes = $q$Ved sennepsallergi kan wasabi og peberrod også give reaktioner.$q$, updated_at = now() where slug = $q$cross-peberrod-sennep$q$;
update public.knowledge_base set health_notes = $q$Latex-frugt-syndrom kan hos nogle give kraftige reaktioner.$q$, updated_at = now() where slug = $q$cross-latex-frugt$q$;
update public.knowledge_base set health_notes = $q$Lupin skal fremhæves i ingredienslisten i EU.$q$, updated_at = now() where slug = $q$cross-jordnod-lupin$q$;
update public.knowledge_base set health_notes = null, updated_at = now() where slug = $q$cross-skaldyr-husstov$q$;
update public.knowledge_base set health_notes = null, updated_at = now() where slug = $q$cross-aeg-fjerkrae$q$;
update public.knowledge_base set health_notes = $q$Gennemstegt oksekød tåles af de fleste.$q$, updated_at = now() where slug = $q$cross-maelk-oksekod$q$;
update public.knowledge_base set health_notes = $q$Ost af gede- og fåremælk, fx feta, er derfor som regel ikke et alternativ ved komælksallergi.$q$, description = $q$Proteinerne i ko-, gede- og fåremælk, især kasein, ligner hinanden meget. De fleste børn med komælksallergi reagerer derfor også på gede- og fåremælk og ost lavet af dem, fx feta. Mælk fra kamel og æsel ligner komælk mindre.$q$, updated_at = now() where slug = $q$cross-ko-ged-maelk$q$;
update public.knowledge_base set health_notes = $q$Hos nogle kan reaktionen på selleri være kraftig.$q$, description = $q$Bynkepollen (Artemisia) kan krydsreagere med selleri, gulerod, persillerod og krydderier som anis, koriander og fennikel. Sammenhængen mellem bynke og selleri kaldes selleri-bynke-krydderi-syndromet. Hos nogle giver den kun kløe i munden, hos andre kraftigere reaktioner.$q$, updated_at = now() where slug = $q$cross-artemisia-selleri$q$;
update public.knowledge_base set health_notes = $q$Klinisk krydsreaktion mellem soja og andre bælgfrugter er sjælden.$q$, updated_at = now() where slug = $q$cross-soja-baelg$q$;
update public.knowledge_base set health_notes = null, updated_at = now() where slug = $q$cross-nodder-interne$q$;
update public.knowledge_base set health_notes = $q$Lupin skal fremhæves i ingredienslisten i EU.$q$, updated_at = now() where slug = $q$kryds-jordnod-baelg$q$;

-- ── Ofte stillede spørgsmål ──
update public.knowledge_base set title = $q$Hvad er forskellen på gluten, cøliaki og hvedeallergi?$q$, summary = $q$Gluten er et protein. Cøliaki er en autoimmun sygdom. Hvedeallergi er en fødevareallergi mod hvedens proteiner.$q$, description = $q$Gluten er en gruppe proteiner i hvede, rug og byg. Havre er naturligt uden gluten, men forurenes ofte med de andre kornsorter.

Cøliaki er en autoimmun sygdom, hvor gluten får immunforsvaret til at skade tyndtarmens slimhinde. Det er ikke en allergi. Behandlingen er livslang glutenfri kost.

Hvedeallergi er en fødevareallergi, hvor immunforsvaret reagerer på proteiner i hvede. Her er det hveden og ikke kun glutenet, der er problemet, så glutenfri produkter med hvedestivelse er ikke nødvendigvis egnede. Om andre kornsorter tåles, er individuelt.

Glutenfølsomhed uden cøliaki bruges om symptomer efter gluten, hvor cøliaki og hvedeallergi er udelukket.$q$, health_notes = $q$Tilstandene kræver hver sin udredning hos lægen.$q$, updated_at = now() where slug = $q$faq-hvede-vs-gluten$q$;
update public.knowledge_base set title = $q$Hvad er cøliaki?$q$, summary = $q$En autoimmun sygdom, hvor gluten skader tyndtarmens slimhinde. Cøliaki er ikke en allergi.$q$, health_notes = $q$Udredning for cøliaki kræver, at man spiser gluten frem til testen. Tal med lægen, før du ændrer kosten.$q$, updated_at = now() where slug = $q$faq-coeliaki$q$;
update public.knowledge_base set title = $q$Hvad er forskellen på allergi og intolerance?$q$, summary = $q$Ved allergi reagerer immunforsvaret. Ved intolerance er immunforsvaret ikke involveret, fx ved laktoseintolerance.$q$, description = $q$Ved allergi reagerer immunforsvaret på et ellers harmløst protein, typisk ved at danne IgE-antistoffer. Hos nogle kan selv små mængder give reaktioner. Ved intolerance er immunforsvaret ikke involveret. Laktoseintolerance skyldes fx for lidt af enzymet laktase og giver fordøjelsesgener. Mælkeallergi er derimod en reaktion på mælkens proteiner. Cøliaki er en tredje type: en autoimmun sygdom udløst af gluten.$q$, health_notes = $q$Lægen kan hjælpe med at skelne allergi fra intolerance.$q$, updated_at = now() where slug = $q$faq-allergi-vs-intolerans$q$;
update public.knowledge_base set summary = $q$Følg den handleplan, du har fået af lægen. Ved tegn på anafylaksi gives adrenalin, og der ringes 112.$q$, health_notes = $q$Følg altid din egen handleplan fra lægen.$q$, updated_at = now() where slug = $q$faq-epipen$q$;
update public.knowledge_base set summary = $q$Tilsætningsstoffer, der er godkendt i EU, får et E-nummer. Nummeret viser, at stoffet er vurderet og godkendt.$q$, updated_at = now() where slug = $q$faq-e-numre$q$;
update public.knowledge_base set title = $q$Er alle E-numre ens?$q$, summary = $q$Alle E-numre er godkendt i EU, men vurderingerne opdateres løbende, og nogle har særlige mærkningskrav.$q$, description = $q$Alle E-numre er godkendt af EU på baggrund af EFSA's (European Food Safety Authority) vurderinger, og vurderingerne ændres, når der kommer ny viden. Fx blev E171 (titandioxid) forbudt i 2022. Nogle stoffer har særlige mærkningskrav: seks azofarvestoffer (fx E102 og E110) kræver en advarsel om mulig påvirkning af børns aktivitet og opmærksomhed. Enkelte personer kan desuden være overfølsomme over for bestemte tilsætningsstoffer, fx sulfitter.$q$, health_notes = $q$EFSA opdaterer løbende sine vurderinger.$q$, updated_at = now() where slug = $q$faq-e-numre-vurdering$q$;
update public.knowledge_base set category = $q$faq$q$, title = $q$Hvad er protein?$q$, summary = $q$Protein er bygget af aminosyrer. Kroppen skal have nogle af dem gennem kosten.$q$, health_notes = null, updated_at = now() where slug = $q$ing-protein$q$;
update public.knowledge_base set category = $q$faq$q$, title = $q$Kan man bruge solsikkeolie ved solsikkeallergi?$q$, summary = $q$Raffineret solsikkeolie indeholder kun meget lidt protein. Koldpresset olie og frø kan give reaktioner.$q$, description = $q$Under raffinering fjernes det meste af proteinet fra solsikkeolie, og raffineret olie tåles derfor af mange med solsikkeallergi. Koldpresset solsikkeolie kan indeholde protein, og solsikkefrø kan give reaktioner. Der er beskrevet krydsreaktioner med bynke- og kamillepollen.$q$, health_notes = $q$Om raffineret olie tåles, er individuelt.$q$, updated_at = now() where slug = $q$cross-solsikke$q$;

-- ── Vidste du at ──
update public.knowledge_base set title = $q$Hvidløg er undersøgt i kræftstudier$q$, summary = $q$Nogle befolkningsstudier finder en sammenhæng mellem et højt indtag af hvidløg og lavere risiko for visse kræftformer, men det er ikke påvist, at hvidløg forebygger kræft.$q$, updated_at = now() where slug = $q$fun-hvidlog-kraeft$q$;
update public.knowledge_base set title = $q$Selleri er et almindeligt allergen i Centraleuropa$q$, summary = $q$Selleri skal fremhæves i ingredienslisten i EU. Selleriallergi er hyppigere i Centraleuropa end i Danmark og hænger ofte sammen med pollenallergi.$q$, updated_at = now() where slug = $q$fun-selleri-allergi$q$;
