-- G1 (6. okt. 2026): godkendte nedgange. Jan har sagt ja til kun at sænke felter, hvor allergenet slet ikke nævnes i
-- ingredienslisten (ingen nøgleord på dansk, engelsk, tysk, hollandsk, svensk, norsk, finsk eller fransk som understreng).
-- Rører IKKE products; markerer kun rækker i gennemgangstabellen. Selve skrivningen sker først i allergen-reanalyze (apply_down).
alter table public.allergen_reanalysis_down_20261006 add column if not exists approved_allergens text[] not null default '{}';

create table if not exists public.products_allergen_down_backup_20261006 (
  product_id uuid primary key,
  old_flags jsonb,
  old_quality text,
  old_method text,
  saved_at timestamptz not null default now()
);
alter table public.products_allergen_down_backup_20261006 enable row level security;
grant all on public.products_allergen_down_backup_20261006 to service_role;

with kw(k, re) as (values
('gluten', 'gluten|rug|rye|secale|byg|barley|hordeum|havre|oats|oat|avena|spelt|kamut|dinkel|dinkelhvede|emmer|einkorn|khorasanhvede|hvedemel|wheat flour|rugmel|rugkerne|rugkerner|rugflager|rugbrød|rugsigte|rugskrå|rugsurdej|bygkerne|bygkorn|bygmel|bygekstrakt|byggryn|bygsirup|havremel|malt|maltekstrakt|malt extract|malteddike|maltsirup|øleddike|bryggersgær|hvedestivelse|wheat starch|stivelse af hvede|semulje|semolina|couscous|bulgur|farro|freekeh|seitan|breadcrumbs|rasp|panko|croutons|roggen|roggenmehl|gerste|gerstenmalz|gerstenmalzextrakt|hafer|haferflocken|hafermehl|grünkern|malzextrakt|weizenmehl|weizenstärke|weizengluten|tarwe|tarwebloem|tarwemeel|tarwezetmeel|tarwegluten|rogge|roggebrood|gerst|gerstemout|moutextract|havermout|havermeel|havervlokken|vete|vetemjöl|vetestärkelse|vetegluten|vetekli|råg|rågmjöl|rågflingor|rågkross|rågsurdeg|bygg|byggmalt|byggmjöl|kornmalt|kornmjöl|maltextrakt|hvete|hvetemel|vehnä|vehnäjauho|vehnätärkkelys|ohra|ohramallas|ruis|ruisjauho|kaura|gluteeni|blé|froment|seigle|orge|avoine|épeautre|bygmalt|perlebyg|bygflager|trigo|centeno|cebada'),
('hvede', 'hvede|wheat|triticum|hvedemel|wheat flour|mel|hvedeprotein|wheat protein|hvedestivelse|wheat starch|hvedegluten|hvedeklid|wheat bran|hvedekerne|wheat germ|durum|spelt|seitan|hvedekimolie|hvedegryn|weizen|weizenmehl|weizenstärke|weizeneiweiß|weizengluten|hartweizen|hartweizengrieß|weizengrieß|tarwe|tarwebloem|tarwemeel|tarwezetmeel|tarwegluten|vete|vetemjöl|vetestärkelse|vetegluten|vetekli|hvete|hvetemel|vehnä|vehnäjauho|vehnätärkkelys|blé|froment|épeautre'),
('maelkeallergi', 'mælk|milk|mælkeprotein|milk protein|mælkebestanddele|kasein|casein|kaseinat|caseinate|natriumkaseinat|kalciumkaseinat|kaliumkaseinat|sodium caseinate|potassium caseinate|calcium caseinate|valle|whey|valleprotein|whey protein|vallepulver|lactalbumin|laktalbumin|lactoglobulin|laktoglobulin|ost|oste|cheese|fromage|fløde|cream|creme fraiche|mozzarella|cheddar|parmesan|parmigiano|grana padano|feta|fetaost|gouda|brie|camembert|emmentaler|pecorino|edamer|havarti|burrata|halloumi|paneer|bagesmør|smør|butter|smørolie|butteroil|smøraroma|yoghurt|yogurt|kefir|skyr|kvark|quark|mascarpone|ricotta|ghee|mælkefedt|milk fat|dairy|tørmælk|mælkepulver|milk powder|non-fat dry milk|skummetmælkspulver|skimmed milk powder|sødmælkspulver|kærnemælk|buttermilk|flødepulver|mælketørstof|milk solids|laktoprotein|inddampet mælk|condensed milk|evaporated milk|animalsk fedtstof|animalsk olie|margarine|minarine|smørfedt|smørfedtstof|flødeost|flødeoste|smøreost|smøreoste|friskost|friskoste|hytteost|hytteoste|rygeost|rygeoste|gedeost|gedeoste|fåreost|fåreoste|ostepulver|ostemasse|ostecreme|ostesmag|ostearoma|osteekstrakt|milch|vollmilch|vollmilchpulver|magermilch|magermilchpulver|milchpulver|milcheiweiß|milchbestandteile|sahne|rahm|käse|molke|molken|molkenpulver|molkenerzeugnis|butterreinfett|joghurt|melk|melke|mykost|melkeiwit|melkpoeder|roomboter|wei|weipoeder|kaas|kwark|slagroom|mjölk|mjölkpulver|mjölkprotein|vassle|vasslepulver|smörfett|grädde|kvarg|filmjölk|mjølk|fløte|kesella|maito|maido|maitojauhe|maitoproteiini|heraproteiini|herajauhe|kerma|juusto|jogurtti|rahka|maitorasva|voita|lait|lactosérum|beurre|yaourt|caséine|petit-lait|crème fraîche|kumelk|kumelkprotein|kumjölk'),
('laktose', 'laktose|lactose|mælkesukker|milk sugar|mælk|milk|fløde|cream|ost|oste|cheese|mozzarella|cheddar|parmesan|feta|fetaost|gouda|brie|camembert|emmentaler|pecorino|creme fraiche|mascarpone|ricotta|kvark|quark|skyr|kefir|bagesmør|yoghurt|yogurt|kærnemælk|buttermilk|valle|whey|tørmælk|mælkepulver|milk powder|flødeost|flødeoste|smøreost|smøreoste|friskost|friskoste|hytteost|hytteoste|ostepulver|ostemasse|ostecreme|milchzucker|milch|sahne|rahm|käse|molke|molken|molkenpulver|joghurt|buttermilch|melk|melke|mykost|melkpoeder|roomboter|wei|weipoeder|kaas|kwark|slagroom|mjölk|mjölkpulver|vassle|vasslepulver|grädde|kvarg|filmjölk|mjølk|fløte|maito|maido|maitojauhe|heraproteiini|herajauhe|kerma|juusto|jogurtti|rahka|laktoosi|lait|lactosérum|beurre|yaourt|petit-lait|crème fraîche|kumelk|kumjölk'),
('aeg', 'æg|egg|eggs|ovum|hønseæg|æggehvide|egg white|æggeblomme|egg yolk|albumin|ovalbumin|ovomucoid|ovomucin|lysozym|lysozyme|globulin|mayonnaise|majonæse|remoulade|meringue|marengs|æggepulver|egg powder|dried egg|whole egg|pasteuriseret æg|skrabeæg|frilandsæg|helæg|helægspulver|buræg|kyllingeæg|andeæg|æggeblommer|æggehvider|æggeblommepulver|æggehvidepulver|æggemasse|æggeprotein|æggeprodukt|æggeprodukter|ei|eier|hühnerei|hühnereier|vollei|volleipulver|eigelb|eiklar|eipulver|eiweißpulver|eieren|eigeel|eipoeder|ägg|äggvita|äggula|äggpulver|äggprodukter|helägg|muna|kananmuna|munanvalkuainen|munankeltuainen|munajauhe|munia|munaa|munan|œuf|œufs|oeuf|oeufs|ægpulver|ægghvide|eggehvite|eggepulver|eggeplomme|eggeblomme|äggulor|äggvitor'),
('noedder', 'nødder|mandel|mandler|almond|hasselnød|hasselnødder|hazelnut|corylus|valnød|valnødder|walnut|juglans|cashew|cashewnød|cashewnødder|anacardium|pistacie|pistachio|pistacienød|pistacienødder|pekannød|pekannødder|pecan|macadamia|macadamianød|macadamianødder|paranød|paranødder|brazil nut|pinjekerne|pinjekerner|pinjenød|pinjenødder|pine nut|kokosnød|kokosnødder|chestnuts|kastanje|kastanjer|nødde|nøddepasta|nut paste|marcipan|marzipan|nougat|pesto|praline|gianduja|mandelmel|nøddemel|mandelsmør|nøddeolie|mandelekstrakt|hasselnøddepasta|haselnuss|haselnüsse|haselnusskerne|haselnussmark|mandeln|walnuss|walnüsse|cashewkerne|cashewnüsse|pistazie|pistazien|pekannuss|pekannüsse|macadamianuss|macadamianüsse|paranuss|paranüsse|schalenfrüchte|amandel|hazelnoot|hazelnoten|walnoot|walnoten|cashewnoten|pecannoten|paranoten|pistachenoten|nötter|hasselnöt|hasselnötter|valnöt|valnötter|cashewnöt|cashewnötter|pistasch|nötpasta|pähkinä|pähkinää|hasselpähkinä|manteli|mantelia|saksanpähkinä|cashewpähkinä|pistaasi|noisette|noisettes|amande|amandes|noix|cajou|pistache|pistaches|nuts|tree nuts|nut mix|nøtter|hasselnøtt|hasselnøtter|valnøtt|valnøtter|cashewnøtter'),
('jordnoedder', 'jordnød|jordnødder|peanut|peanuts|groundnut|arachis|arachide|jordnøddeolie|peanut oil|arachideolie|arachis oil|jordnøddesmør|peanut butter|satay|kacang|nut sauce|erdnuss|erdnüsse|erdnussöl|erdnussbutter|erdnussmus|pinda|pindas|pindakaas|pindapasta|jordnöt|jordnötter|maapähkinä|maapähkinää|arachides|cacahuète|cacahuètes'),
('soja', 'soja|soy|soya|glycine max|sojabønne|sojabønner|soybean|soybeans|tofu|miso|edamame|tempeh|natto|sojalecithin|soy lecithin|sojamel|soy flour|sojaprotein|soy protein|sojaolie|sojasauce|soy sauce|tamari|shoyu|sojadrik|sojamælk|textured vegetable protein|tvp|hydrolyseret sojaprotein|isoleret sojaprotein|lecithin|lecitin|sojabohnen|sojalecithine|sojaeiweiß|sojabonen|sojabloem|sojaproteïne|soija|soijalesitiini|soijaproteiini|lesitiini|lécithine|lécithines'),
('fisk', 'fisk|fish|ansjos|ansjoser|anchovy|anchovies|anchois|torsk|cod|gadus|laks|salmon|salmo|tun|tuna|thunnus|sild|herring|clupea|makrel|makreller|mackerel|rødspætte|rødspætter|plaice|sardin|sardiner|sardine|helleflynder|halibut|tilapia|fiskesauce|fish sauce|nam pla|nuoc mam|worcestershire sauce|worcestershiresauce|caesar dressing|bouillabaisse|fiskeolie|fish oil|surimi|tunekstrakt|tunsalat|tunfisk|tunkød|tunfiskekstrakt|fiskegelatine|fiskeekstrakt|fiskeboller|fiskemel|omega-3|rogn|roe|kaviar|caviar|fisch|fischsauce|lachs|thunfisch|sardellen|hering|kabeljau|seelachs|skrubbe|skrubber|skrubbefilet|ising|isingfilet|sej|mørksej|lyssej|kuller|hvilling|ørred|ørreder|regnbueørred|hellefisk|rødtunge|havtunge|gedde|aborre|sandart|knurhane|havtaske|brosme|sværdfisk|pangasius|pangas|pollock|alaska pollock|ål|ålefilet|stør|hajfinne|brisling|stenbiderrogn|lodderogn|fiskefilet|fiskefileter|fiskeprotein|fiskekød|fiskefars|fiskestykker|fiskeskind|fiskebouillon|fiskefond|fiskepålæg|ansjovis|haring|zalm|tonijn|kabeljauw|makreel|vissaus|visolie|visgelatine|viseiwit|lax|laxfilé|sill|makrill|tonfisk|fiskprotein|fiskextrakt|fiskbuljong|fiskolja|kala|kalaa|kalan|lohi|kirjolohi|silli|tonnikala|turska|makrilli|kalaöljy|poisson|saumon|thon|hareng|morue|huile de poisson|stenbidderrogn|fiskepulver|fiskegelantine|fiskekstrakt|bonito|vildlaks|rødlaks|alaskasej'),
('skaldyr', 'skaldyr|crustacean|rejer|reje|tigerrejer|shrimp|prawn|hummer|lobster|krabbe|krabber|crab|languster|langustere|langoustine|krebs|crayfish|krebsdyr|krebsedyr|krabbestang|krill|strandkrabbe|strandkrabber|krabbekød|rejeekstrakt|rejepulver|musling|muslinger|østers|blæksprutte|blæksprutter|kammusling|kammuslinger|mussel|oyster|squid|scallop|snegle|pilgrimsmusling|escargot|krebstiere|garnelen|krabben|shrimps|garnalen|schaaldieren|krab|kreeft|mosselen|oesters|inktvis|räkor|räka|skaldjur|krabba|kräftor|kräfta|musslor|bläckfisk|katkarapu|katkaravut|äyriäiset|rapu|simpukka|simpukat|osterit|mustekala|crevette|crevettes|crabe|homard|crustacés|moules|huître|huîtres|calmar|poulpe'),
('selleri', 'selleri|celery|apium|knoldselleri|celeriac|bladselleri|selleriolie|sellerisalt|celery salt|sellerifnug|selleripulver|celery seed|celery extract|sellerie|knollensellerie|selderij|selderie|céleri'),
('sennep', 'sennep|mustard|sinapis|sennepsfrø|mustard seed|sennepsolie|mustard oil|sennepspulver|mustard powder|sennepsmel|mustard flour|dijon|dijonsennep|engelsk sennep|grovkornet sennep|senf|senfsaat|senfmehl|senfkörner|mosterd|mosterdzaad|senap|senapsfrö|sinappi|moutarde'),
('sesam', 'sesam|sesame|sesamum|tahini|tahin|sesamolie|sesame oil|sesamfrø|sesame seed|sesampasta|sesammel|halva|halvah|gomashio|gingelly|sésame|seesami'),
('svovl', 'svovldioxid|svovl|sulphur dioxide|sulfur dioxide|sulfit|sulfitter|sulphite|sulfite|so2|e220|e221|e222|e223|e224|e225|e226|e227|e228|natriumsulfit|kaliumsulfit|natriummetabisulfit|schwefeldioxid|zwaveldioxide|svaveldioxid|rikkidioksidi|dioxyde de soufre|anhydride sulfureux'),
('lupin', 'lupin|lupine|lupinus|lupinfrø|lupinmel|lupin flour|lupin seed|lupin bean|lupinprotein|lupin protein|lupinfiber'),
('bloeddyr', 'bløddyr|mollusc|mollusk|musling|muslinger|mussel|østers|oyster|blæksprutte|blæksprutter|squid|octopus|snegl|snegle|snail|kammusling|kammuslinger|scallop|clam|abalone|vongole|weichtiere|muscheln|miesmuscheln|tintenfisch|weekdieren|mosselen|oesters|inktvis|musslor|blötdjur|bläckfisk|nilviäiset|simpukka|simpukat|osterit|mustekala|mollusques|moules|huître|huîtres|calmar|poulpe')),
rx(a, re) as (
  select m.a, string_agg(kw.re, '|') from (values ('gluten','gluten'),('gluten','hvede'),('hvede','gluten'),('hvede','hvede'),('maelkeallergi','maelkeallergi'),('maelkeallergi','laktose'),('laktose','maelkeallergi'),('laktose','laktose'),('aeg','aeg'),('noedder','noedder'),('jordnoedder','jordnoedder'),('soja','soja'),('fisk','fisk'),('skaldyr','skaldyr'),('selleri','selleri'),('sennep','sennep'),('sesam','sesam'),('svovl','svovl'),('lupin','lupin'),('bloeddyr','bloeddyr')) as m(a,k) join kw on kw.k = m.k group by m.a
)

update public.allergen_reanalysis_down_20261006 d
set approved_allergens = coalesce((
      select array_agg(u.al order by u.al)
      from unnest(d.down_allergens) as u(al)
      join rx on rx.a = u.al
      where d.old_flags->>u.al in ('yes', 'traces')
        and coalesce(d.new_flags->>u.al, 'no') = 'no'
        and d.ingredients_text !~* rx.re
    ), '{}'),
    decision = null
where d.applied_at is null;

update public.allergen_reanalysis_down_20261006
set decision = 'approved'
where cardinality(approved_allergens) > 0 and applied_at is null;
